### ISSUE TITLE
Offer reboot action when there are changes pending to the VM

### ISSUE THREAD

**Issue by skobyda** [cockpit-project/cockpit-machines#1004]
![Screenshot from 2023-04-03 13-14-29](https://user-images.githubusercontent.com/42733240/229748898-a6f805ee-5de7-46d1-a572-913eecee5864.png)

Popover which informs user that VM has pending changes should have a button which reboots the VM. But a simple OS reboot doesn't apply those changes, we need to shutdown the VM and then start it, since only this causes live libvirt XML to cease to exist and be replaced by updated offline libvirt XML.
We also need to replace all reboot actions wich shudown+start if there are actions pending

Split out from #998 , suggested by @garrett  [here](https://github.com/cockpit-project/cockpit-machines/pull/998#discussion_r1155850577):

**Comment by marusak** [comment]
The action is available very close to the popover. Clicking the button would require another confirmation modal...
