### ISSUE TITLE
Request: Shared folder host / virtual machine (libvirtd)

### ISSUE THREAD

**Issue by NovaDecker** [cockpit-project/cockpit-machines#103]
Page: 
Virtual Machine / Libvirtd

I wish it was an feature in cockpit to configure a shared folder between the host and the virtual machine. Currently it is possible to use NFS-share, and I have explored (googled) and figured out it would be possible with some custom configuration.

**Comment by KKoukiou** [comment]
This can be implemented virtio-FS. 
 https://libvirt.org/kbase/virtiofs.html

**Comment by NovaDecker** [comment]
I actually have problems with doing this, as i do not find any packages for virtio (virtiofsd) to install neither on the host machine or the guest. It would be good to make this possible to do via the GUI tho.

**Comment by NovaDecker** [comment]
I am running this:
`mount -t virtiofs vm_shared /www`
But I am getting:
`mount: /www: wrong fs type, bad option, bad superblock on vm_shared, missing codepage or helper program, or other error.`

I followed what it said here: `https://libvirt.org/kbase/virtiofs.html`

This is my .xml of guest, I have made a line break before and after the lines I did put in myself.

`<domain type='kvm'>
<name>webserver</name>
  <uuid>XXXXXX</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://centos.org/centos/8"/>
    </libosinfo:libosinfo>
    <cockpit_machines:data xmlns:cockpit_machines="https://github.com/cockpit-project/cockpit/tree/master/pkg/machines">
      <cockpit_machines:has_install_phase>false</cockpit_machines:has_install_phase>
      <cockpit_machines:install_source_type>os</cockpit_machines:install_source_type>
      <cockpit_machines:install_source/>
      <cockpit_machines:os_variant>centos8</cockpit_machines:os_variant>
    </cockpit_machines:data>
  </metadata>
  <memory unit='KiB'>4194304</memory>
  <currentMemory unit='KiB'>4194304</currentMemory>
  <vcpu placement='static'>2</vcpu>
  <resource>
    <partition>/machine</partition>
  </resource>
  <os>
    <type arch='x86_64' machine='pc-q35-rhel8.2.0'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <vmport state='off'/>
  </features>

  <memoryBacking>
   <hugepages>
    <page size='2' unit='M'/>
   </hugepages>
   <access mode='shared'/>
  </memoryBacking>

  <cpu mode='custom' match='exact' check='full'>

   <numa>
    <cell id='0' cpus='0-7' memory='4' unit='GiB' memAccess='shared'/>
   </numa>

    <model fallback='forbid'>IvyBridge-IBRS</model>
    <vendor>Intel</vendor>
    <feature policy='require' name='ss'/>
    <feature policy='require' name='pcid'/>
    <feature policy='require' name='hypervisor'/>
    <feature policy='require' name='arat'/>
    <feature policy='require' name='tsc_adjust'/>
    <feature policy='require' name='umip'/>
    <feature policy='require' name='md-clear'/>
    <feature policy='require' name='stibp'/>
    <feature policy='require' name='arch-capabilities'/>
    <feature policy='require' name='ssbd'/>
    <feature policy='require' name='xsaveopt'/>
    <feature policy='require' name='pdpe1gb'/>
    <feature policy='require' name='ibpb'/>
    <feature policy='require' name='amd-ssbd'/>
    <feature policy='require' name='skip-l1dfl-vmentry'/>
    <feature policy='require' name='pschange-mc-no'/>
  </cpu>
  <clock offset='utc'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled='no'/>
    <suspend-to-disk enabled='no'/>
  </pm>
  <devices>
    <emulator>/usr/libexec/qemu-kvm</emulator>


    <filesystem type='mount' accessmode='passthrough'>
     <driver type='virtiofs'>
     <source dir='/files/vm_shared'/>
     <target dir='vm_shared'/>
    </filesystem>


    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/files/webserver.qcow2'/>
      <backingStore/>
      <target dev='vda' bus='virtio'/>
      <address type='pci' domain='0x0000' bus='0x04' slot='0x00' function='0x0'/>
    </disk>
    <controller type='usb' index='0' model='qemu-xhci' ports='15'>
      <address type='pci' domain='0x0000' bus='0x02' slot='0x00' function='0x0'/>
    </controller>
    <controller type='sata' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x1f' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pcie-root'/>
    <controller type='pci' index='1' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='1' port='0x10'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0' multifunction='on'/>
    </controller>
    <controller type='pci' index='2' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='2' port='0x11'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x1'/>
    </controller>
    <controller type='pci' index='3' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='3' port='0x12'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x2'/>
    </controller>
    <controller type='pci' index='4' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='4' port='0x13'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x3'/>
    </controller>
    <controller type='pci' index='5' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='5' port='0x14'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x4'/>
    </controller>
    <controller type='pci' index='6' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='6' port='0x15'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x5'/>
    </controller>
    <controller type='pci' index='7' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='7' port='0x16'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x6'/>
    </controller>
    <controller type='virtio-serial' index='0'>
      <address type='pci' domain='0x0000' bus='0x03' slot='0x00' function='0x0'/>
    </controller>
    <interface type='network'>
      <mac address='XX:XX:XX:XX:XX'/>
      <source network='default'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x01' slot='0x00' function='0x0'/>
    </interface>
    <serial type='pty'>
      <target type='isa-serial' port='0'>
        <model name='isa-serial'/>
      </target>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <channel type='unix'>
      <target type='virtio' name='org.qemu.guest_agent.0'/>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
    </channel>
    <channel type='spicevmc'>
      <target type='virtio' name='com.redhat.spice.0'/>
      <address type='virtio-serial' controller='0' bus='0' port='2'/>
    </channel>
    <input type='tablet' bus='usb'>
      <address type='usb' bus='0' port='1'/>
    </input>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
    <graphics type='spice' autoport='yes' listen='127.0.0.1'>
      <listen type='address' address='127.0.0.1'/>
      <image compression='off'/>
    </graphics>
    <graphics type='vnc' port='-1' autoport='yes' listen='127.0.0.1'>
      <listen type='address' address='127.0.0.1'/>
    </graphics>
    <sound model='ich9'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x1b' function='0x0'/>
    </sound>
    <video>
      <model type='qxl' ram='65536' vram='65536' vgamem='16384' heads='1' primary='yes'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x0'/>
    </video>
    <redirdev bus='usb' type='spicevmc'>
      <address type='usb' bus='0' port='2'/>
    </redirdev>
    <redirdev bus='usb' type='spicevmc'>
      <address type='usb' bus='0' port='3'/>
    </redirdev>
    <memballoon model='virtio'>
      <address type='pci' domain='0x0000' bus='0x05' slot='0x00' function='0x0'/>
    </memballoon>
    <rng model='virtio'>
      <backend model='random'>/dev/urandom</backend>
      <address type='pci' domain='0x0000' bus='0x06' slot='0x00' function='0x0'/>
    </rng>
  </devices>
  <seclabel type='dynamic' model='dac' relabel='yes'/>
</domain>`

**Comment by KKoukiou** [comment]
Hey, @NovaDecker I suggest if you need help with setting up a virtiofs from the CLI you can ask help in the libvirt mailing list, or #virt channel on IRC on oftc server. Here this issue can serve as an RFE for cockpit to support it from the UI. virtiofs or generally shared directories like https://libvirt.org/formatdomain.html#filesystems.

**Comment by NovaDecker** [comment]
Hi again!
The problem is that my kernel is too old for virtio-fs. At the same time, I did see that CentOS 8 have EOL in 2021. Therefore I am in a process of going back to CentOS 7, and there I will use a newer kernel.

But anyway, the point of this thread was actually to ask you if you could implement this in the GUI. It would be nice.

I have seen that multiple persons do develop their own extensions to cockpit, could I get more info about what I do need to know to interact with the cockpit GUI? Do the cockpit have an api?

**Comment by KKoukiou** [comment]
> Hi again!
> The problem is that my kernel is too old for virtio-fs. At the same time, I did see that CentOS 8 have EOL in 2021. Therefore I am in a process of going back to CentOS 7, and there I will use a newer kernel.
> 
> But anyway, the point of this thread was actually to ask you if you could implement this in the GUI. It would be nice.

Just did :) I exposed this with virtIO-9p, because I also found out the virtiofs will not be supported for users with half of the distros releases with test against.

virtIO-9p suppport to be added in the future.

> 
> I have seen that multiple persons do develop their own extensions to cockpit,

Indeed! We try to keep some list here https://cockpit-project.org/applications.html.

> could I get more info about what I do need to know to interact with the cockpit GUI? Do the cockpit have an api?

Here is the place you can start https://cockpit-project.org/blog/cockpit-starter-kit.html
