### ISSUE TITLE
create VM dialog: Regression in helperText layout

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-machines#1034]
There's a regression for the memory helper text in the Create VM dialog...

![image](https://user-images.githubusercontent.com/10246/232816992-f1f98b17-e6c2-4436-8e10-e20bc60cfe62.png)

It should be under the entry; instead, it's to the side without any space.

**Comment by skobyda** [comment]
This was fixed by https://github.com/cockpit-project/cockpit-machines/pull/1036
