### ISSUE TITLE
Show the interface name (target dev) of a network interface

### ISSUE THREAD

**Issue by Britz** [cockpit-project/cockpit-machines#1047]
Network interfaces that are attached to VMs have a tun device on the host which is automatically generated and mostly named `vnetX`, where `X` is a consecutive number.  If you want to check manually, e.g., why the device is not working correctly, you need to know the interface name. It would be great to have that information in the network interfaces row as depicted in the following mokup.

<img width="1574" alt="Bildschirmfoto 2023-04-25 um 17 59 02" src="https://user-images.githubusercontent.com/2488427/234347089-3fabbcdf-064e-48a2-b049-ec130ba688f7.png">

Perhaps it could even be, similar to the source argument, a button which brings you to the device itself.

<img width="1572" alt="Bildschirmfoto 2023-04-25 um 17 58 40" src="https://user-images.githubusercontent.com/2488427/234347833-0dde1b90-b1f5-4b74-8b3c-fb24a37791d8.png">

Given the VM (domain) name and the MAC address, this information can be easily retrieved on the console, e.g., using `virsh dumpxml`, where it is given as the `dev` argument of the `target` element:

```shell
#> virsh dumpxml --xpath '//interface' "$DOMAIN" 
<interface type="bridge">
  <mac address="52:54:00:3f:2e:b8"/>
  <source bridge="bridge0"/>
  <target dev="vnet1"/>
  <model type="virtio"/>
  <alias name="net0"/>
  <address type="pci" domain="0x0000" bus="0x01" slot="0x00" function="0x0"/>
</interface>
```
and to get only the value `virsh dumpxml --xpath "//interface[mac[@address=\"$MAC\"]]/target/@dev" "$DOMAIN" | sed -nE 's/[^"]*="(.*)"/\1/p'` can be used.

Alternatively, `virsh domiflist` can also be used, which returns the value given in the first column, named `Interface`:

```shell
#> virsh domiflist "$DOMAIN" 
Interface   Type     Source    Model    MAC
------------------------------------------------------------
vnet1       bridge   bridge0   virtio   52:54:00:3f:2e:b8
```

and to get only the value, e.g., `virsh domiflist "$DOMAIN"  |  grep "$MAC" | awk '{ print $1 }'` can be used.

**Comment by skobyda** [comment]
Thanks for showing how to get a value. Looks like a simple feature, so I'll start working on it soon and sent a PR.
