### ISSUE TITLE
Machines list: misalignment of action widgets (needs lib sync?)

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-machines#105]
There was a regression in the alignment of the actions in the top-right of the machines list (probably related to a PF update), but it was fixed in Cockpit before the split. It has regressed again.

![Screenshot from 2021-04-14 11-25-38](https://user-images.githubusercontent.com/10246/114687598-37712200-9d14-11eb-9eed-4cc0e3b23dba.png)

As this was already fixed, syncing over the latest versions of the common libraries used by Cockpit would most likely fix this again.

**Comment by KKoukiou** [comment]
I don't think it's a regression, it was broken before as well.
It will be fixed when we update lib. 
```
diff --git Makefile Makefile
index 8b380a5..87c4fdc 100644
--- Makefile
+++ Makefile
@@ -180,7 +180,7 @@ test/common:
 # checkout Cockpit's PF/React/build library; again this has no API stability guarantee, so check out a stable tag
 $(LIB_TEST):
        flock Makefile sh -ec '\
-           git fetch --depth=1 https://github.com/cockpit-project/cockpit.git 241; \
+           git fetch --depth=1 https://github.com/cockpit-project/cockpit.git 242; \
            git checkout --force FETCH_HEAD -- pkg/lib; \
            git reset -- pkg/lib'
        mv pkg/lib src/ && rmdir -p pkg
```

**Comment by garrett** [comment]
> I don't think it's a regression, it was broken before as well.

By regression, I meant at some time in the distant past, it was aligned properly, and at some point in the less distant past, it became misaligned. And then we fixed it recently. (But perhaps after the split?)

I suppose the split happened before the fix? So, yeah, it wouldn't be a regression due to the split, if so.

Anyway, the details don't really matter, as we have a pending fix. :+1: 

> It will be fixed when we update lib.

Excellent! :+1:
