### ISSUE TITLE
Virtual machines Operating system dropdown list empty

### ISSUE THREAD

**Issue by ItzMiracleOwO** [cockpit-project/cockpit-machines#1075]
### Explain what happens

![image](https://github.com/cockpit-project/cockpit/assets/76854136/63132956-edfe-4add-a7b2-a761836b0fc9)
As in the screenshot, when I try to create a virtual machine, the required flag "Operating system" dropdown list is empty, so I cannot create a vm.

I am on Fedora server 38
![image](https://github.com/cockpit-project/cockpit/assets/76854136/ae1eb631-c400-4000-aafd-9cdbada21570)

I have also checked cockpit-project/cockpit#15381 and I didnt find anything useful.

For `python3 getOSList.py`:
```
Traceback (most recent call last):
  File "getOSList.py", line 4, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

Try import `gi` in python3 console:
```
python3
Python 3.8.12 (default, Mar 14 2023, 21:11:35)
[GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gi'
>>>
```

Try import `gi` in python console:
```
python
Python 3.11.3 (main, Apr  5 2023, 00:00:00) [GCC 13.0.1 20230401 (Red Hat 13.0.1-0)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>>
```

Running `getOSList.py` with python:
(A large array of output)

`ls -la $(which python)`:
```
lrwxrwxrwx. 1 root root 9  4月  5 08:00 /usr/bin/python -> ./python3
```

### Version of Cockpit

250.1.1

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Fedora

### Server operating system version

Fedora server 38

### What browsers are you using?

Chrome, Edge, Brave

**Comment by martinpitt** [comment]
You need to install the `python3-gobject-base` package. cockpit-machines already `Recommends:` it, but apparently you disabled recommendations?

**Comment by ItzMiracleOwO** [comment]
![image](https://github.com/cockpit-project/cockpit-machines/assets/76854136/608e66b5-6893-4594-9c0e-3e63f560a8fb)
`python3-gobject-base` is already installed

**Comment by martinpitt** [comment]
Hmm, if it is installed, but `python3 -c 'import gi'` fails (as you already tried above), then there's something wrong with your Python installation.

**Comment by ItzMiracleOwO** [comment]
Hm, do I reinstall python3 then?

**Comment by ItzMiracleOwO** [comment]
I reinstalled python3 by:
`sudo dnf reinstall "python3*"`
The command `python3 -c 'import gi'` still fails

**Comment by martinpitt** [comment]
Now I finally spotted it: Your `python3` command is something old:

> Python 3.8.12 (default, Mar 14 2023, 21:11:35)

Fedora 38 has Python 3.11, and python3-gobject is built against that, not 3.8.

So I suppose you have some /usr/local/bin/python3, or something in your $HOME. Check with `which python3`.

**Comment by ItzMiracleOwO** [comment]
![image](https://github.com/cockpit-project/cockpit-machines/assets/76854136/4983c8df-49fe-403c-8340-8829e502a20e)

Here it is, what do I do to fix that?

**Comment by martinpitt** [comment]
Well, how did you install it in the first place? :grin: Of course you can just rename/delete /usr/local/bin/python3 , but presumably you had some reason to install it in the first place?

**Comment by ItzMiracleOwO** [comment]
> Well, how did you install it in the first place? 😁 Of course you can just rename/delete /usr/local/bin/python3 , but presumably you had some reason to install it?

Hm no I dont thing I have reason to keep python3 there, but if i delete that do I need to link `/usr/bin/python` to `/usr/local/bin/python3`?

**Comment by wolf-yuan-6115** [comment]
> Well, how did you install it in the first place? :grin: Of course you can just rename/delete /usr/local/bin/python3 , but presumably you had some reason to install it?

Normally every python3 will install to /usr/bin/python3, idk why we have /usr/bin/python3 linking to python

**Comment by wolf-yuan-6115** [comment]
@martinpitt Thanks for your help, hard linking /usr/local/bin/python3 -> /usr/bin/python do the trick.

![Screenshot_20230528-205610.png](https://github.com/cockpit-project/cockpit-machines/assets/58245644/6f0d9076-d3a9-4045-b619-5591940f3197)

**Comment by wolf-yuan-6115** [comment]
@martinpitt Thanks for your help, hard linking /usr/local/bin/python3 -> /usr/bin/python do the trick.

**Comment by KKoukiou** [comment]
> @martinpitt Thanks for your help, hard linking /usr/local/bin/python3 -> /usr/bin/python do the trick.

Just to avoid other users following this suggestion, this *is not* an accepted solution, as system installed python should be put in /usr/bin/ from the package manager, not user symlinking it.

**Comment by wolf-yuan-6115** [comment]
I tried to avoid that but I can't find out why python is installed there.
