### ISSUE TITLE
REQ: Resize disks

### ISSUE THREAD

**Issue by Larse99** [cockpit-project/cockpit-machines#1099]
Hi!

I would like the option to dynamically resize disks while VM's are running. I can achieve just that by running the following command:

virsh blockresize <machine> /path/to/disk.qcow2> <new_size>

Would be cool to include this in the GUI, since it can come quite handy :).

**Comment by KKoukiou** [comment]
Closing as duplicate of https://github.com/cockpit-project/cockpit-machines/issues/358

This is not in our backlog but it's definitely an interesting feature so gladly would accept contributions if you have the capacity / knowledge for this. Thx
