### ISSUE TITLE
Some selects get rendered in the wrong position for a flash second 

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit-machines#1102]
[Screencast from 2023-06-07 11-28-35.webm](https://github.com/cockpit-project/cockpit-machines/assets/14921356/6b012672-5e8c-431d-9156-22bd78286ecf)

**Comment by garrett** [comment]
I think this was fixed in https://github.com/patternfly/patternfly-react/pull/9339... but still isn't in any release yet?
