### ISSUE TITLE
"Shut down" should be a secondary button

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-machines#1136]
While running a VM should probably still be a primary button on a details page (and secondary on the list view), "Shut down" should be a secondary button everywhere (including the details page).

In other words, we probably want to demote "Shut down" on the details page to a secondary button.

I noticed it on this test result: ![image](https://github.com/cockpit-project/cockpit-machines/assets/10246/4992b934-d0f6-4139-9735-f755d1bbc459)

(Regardless of that button, we still need to move to the new design for the console. But that's an entirely different discussion.)

**Comment by Roshan-Pawar** [comment]
I would like to work on this, can you assign this to me

**Comment by jelly** [comment]
We don't assign issues, please work on them and make a PR if you are able, some hints:

How to develop for Cockpit: https://cockpit-project.org/external/source/HACKING.html

Our dev docs in general https://cockpit-project.org/external/wiki/Contributing.html

**Comment by Vishalydv07** [comment]
I can work on this issue if you assign me.

**Comment by shawakash** [comment]
@garrett i think i found the where the bug is but not able to setup the project.
please help me to setup

**Comment by martinpitt** [comment]
@shawakash Please follow https://github.com/cockpit-project/cockpit/blob/main/HACKING.md to set up a development environment and https://github.com/cockpit-project/cockpit-machines/blob/main/HACKING.md for learning how to do a change in c-machines. Good luck!
