### ISSUE TITLE
Add scheduled backup and prune options on virtual machines

### ISSUE THREAD

**Issue by Streifi89** [cockpit-project/cockpit-machines#1139]
It would be nice, that we have a section like snapshots for backups with prune options for example: "Least 3 Backups... 1 Week" and with scheduling like "every day at 12 pm".

**Comment by KKoukiou** [comment]
Hi thanks for opening this issue. From a quick search I found https://virt-backup.readthedocs.io/en/latest/ that could be used. I am not sure how stable/used it is and in which distros it's available. 

This feature request could be considered but will not be in the focus of the team in the foreseeable future. Patches are welcome!

**Comment by marusak** [comment]
This is very unlikely to be picket by the team. Closing.
