### ISSUE TITLE
isSelectableRaised property of a `Card` is deprecated

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit-machines#1167]
![image](https://github.com/cockpit-project/cockpit-machines/assets/67428/a7e96a44-51b1-43dd-bdd0-d616a674ce31)

Update it to what replaces `isSelectableRaised`.

**Comment by niladrix719** [comment]
can i work on this?

**Comment by martinpitt** [comment]
@niladrix719 Please do, thank you!

**Comment by jelly** [comment]
FYI, this commit deprecates the property https://github.com/patternfly/patternfly-react/commit/c3cf82326026a79df1ec2fecc249854d0ebbed99 this might actually already been solved by us setting `isSelectable` and `isClickable` in https://github.com/cockpit-project/cockpit-machines/pull/1162

**Comment by Kartikay5849** [comment]
Hi @martinpitt is this issue still open?

**Comment by martinpitt** [comment]
Current main still contains this twice:
```
src/components/aggregateStatusCards.jsx:                      isSelectableRaised
src/components/aggregateStatusCards.jsx:                      isSelectableRaised
```
