### ISSUE TITLE
jQuery not working in 215-1

### ISSUE THREAD

**Issue by ENT108** [cockpit-project/cockpit-machines#1176]
##Failed to load resource: the server responded with a status of 404 (Not Found)

![Screenshot 2023-08-08 at 19 06 52](https://github.com/cockpit-project/cockpit-machines/assets/25681316/fb98d3ae-06fa-4f90-89b6-731f9c590ad5)

**Comment by KKoukiou** [comment]
This is a known issue that has  been fixed since ages. Please use backports to update this package.

See https://github.com/cockpit-project/cockpit-machines/issues/596#issuecomment-1053997161
