### ISSUE TITLE
internal error: client socket closed

### ISSUE THREAD

**Issue by tkennertas** [cockpit-project/cockpit-machines#1193]
Hello,

i am not sure if I am at the right place with the following error. I am using cockpit and cockpit-machines to manage my virtual machines on a RHEL 9 server. I am using the COPR Repository for my cockpit instance. The latest version is installed:
![cockpit_machines_socket_closed_error_00](https://github.com/cockpit-project/cockpit-machines/assets/128036200/6d2f4d03-8621-4df7-ae24-379a7474c37a)

I have several network shares mounted / as pools defined:
![cockpit_machines_socket_closed_error_04](https://github.com/cockpit-project/cockpit-machines/assets/128036200/6e8a4076-b5bc-4fa7-a45c-ab0d23e04d21)

I can see the shares in cockpit under storages:
![cockpit_machines_socket_closed_error_01](https://github.com/cockpit-project/cockpit-machines/assets/128036200/fbc6effb-6c02-43d5-b321-a0b39fb3ec74)

I can see them in "virt-manager" too:
![cockpit_machines_socket_closed_error_05](https://github.com/cockpit-project/cockpit-machines/assets/128036200/74212bd7-c012-43e3-b59d-9a80f13352c4)

When I want to take a look at the pools in the "Storage pools" section of cockpit-machines, I am getting the following error:
![cockpit_machines_socket_closed_error_02](https://github.com/cockpit-project/cockpit-machines/assets/128036200/3662ed26-7431-4673-afc4-d40701d3c4a5)
![cockpit_machines_socket_closed_error_03](https://github.com/cockpit-project/cockpit-machines/assets/128036200/d9d22f95-8396-47fb-9df3-4bdb0d534bf8)

This error prevents me to a) install a new virtual machine and b) to edit current disks of virtual machines via cockpit

I am not sure if this is a cockpit-machines bug/error. I would appreciate if you could help me to identify what the actual problem is and/or help me to address this error to the right place.

Thank you in advance!

**Comment by aininot260** [comment]
I solved the same problem. I make the output of the 'getfacl /var/lib/libvirt/images' like that:
```
[admin@server ~]$ getfacl /var/lib/libvirt/images
getfacl: Removing leading '/' from absolute path names
# file: var/lib/libvirt/images
# owner: root
# group: root
user::rwx
group::--x
other::--x
```
and using the following cmd:
```
sudo chown -R root:root /var/lib/libvirt/images
```
I keep the config file /etc/libvirt/qemu.conf like that:
```
# The user for QEMU processes run by the system instance. It can be
# specified as a user name or as a user id. The qemu driver will try to
# parse this value first as a name and then, if the name doesn't exist,
# as a user id.
#
# Since a sequence of digits is a valid user name, a leading plus sign
# can be used to ensure that a user id will not be interpreted as a user
# name.
#
# Some examples of valid values are:
#
#       user = "qemu"   # A user named "qemu"
#       user = "+0"     # Super user (uid=0)
#       user = "100"    # A user named "100" or a user with uid=100
#
#user = "qemu"

# The group for QEMU processes run by the system instance. It can be
# specified in a similar way to user.
#group = "qemu"
```
no need to uncomment the above configs.

after reboot, the problem fixed.
