### ISSUE TITLE
Permission denied when loading a qcow2 file

### ISSUE THREAD

**Issue by voltagex** [cockpit-project/cockpit-machines#1245]
I can't access my VM's disk for some reason

![image](https://github.com/cockpit-project/cockpit-machines/assets/83080728/fb487f08-674f-4914-aa03-08b7d94ec31e)
```
internal error: process exited while connecting to monitor: 2023-10-07T05:52:05.491532Z qemu-system-x86_64: -blockdev {"driver":"file","filename":"/pool/zstd/vm/haos_ova_64g.qcow2","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"}: Could not open '/pool/zstd/vm/haos_ova_64g.qcow2': Permission denied
```

![image](https://github.com/cockpit-project/cockpit-machines/assets/83080728/454de4a3-9120-46d0-af46-55475427576d)
`Cannot access storage file '/pool/zstd/vm/haos_ova_64g.qcow2' (as uid:64055, gid:64055): Permission denied`

```
voltagex@scratch:/pool/zstd/vm$ getfacl -e haos_ova_64g.qcow2
# file: haos_ova_64g.qcow2
# owner: voltagex
# group: libvirt-qemu
user::rwx
group::rwx
other::---
```

**Comment by KKoukiou** [comment]
Is your user in the libvirt-qemu group?

https://wiki.debian.org/KVM#Installation

**Comment by voltagex** [comment]
@KKoukiou thanks for that link. No change after adding my user account to both `libvirt` and `libvirt-qemu`

**Comment by KKoukiou** [comment]
Forgot to mention, @voltagex you need to always restart the libvirt main daemon when you make changes to the users/groups.

Depending on the libvirt version you 're using it might be, `systemctl restart libvirtd` or `systemctl restart virtqemud` for newer.

If this does not work, try spawning the VM from CLI with `virt-install` directly to identify if the problem is on the cockpit-machines side of it's some wrong setup on the libvirt configuration on your system.

**Comment by voltagex** [comment]
@KKoukiou I suspect this is a libvirt issue. I get the same error if I use `virsh start`

However, on the cockpit-machines side, it would be nice for it to warn about configuration errors like this - even if it didn't help in this case.

**Comment by KKoukiou** [comment]
Yes this makes sense to try to detect possible configuration issues, but it's quite complicated as groups for virtualization tool vary per distribution and even libvirt major releases sometimes. Its nonetheless valid RFE.

**Comment by voltagex** [comment]
@KKoukiou I've raised https://gitlab.com/libvirt/libvirt/-/issues/546 and am closing this issue. Appreciate the help.
