### ISSUE TITLE
rawhide testWatchdog failure

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit-machines#1249]
On rawhide

![image](https://github.com/cockpit-project/cockpit-machines/assets/67428/c98fe5d3-c8dd-4512-a291-6aa386210445)

Packages compared to F39

```
  libvirt-client (9.7.0-1.fc39 -> 9.8.0-1.fc40)
  libvirt-daemon-common (9.7.0-1.fc39 -> 9.8.0-1.fc40)
  libvirt-daemon-config-network (9.7.0-1.fc39 -> 9.8.0-1.fc40)
  libvirt-daemon-driver-interface (9.7.0-1.fc39 -> 9.8.0-1.fc40)
  libvirt-daemon-driver-network (9.7.0-1.fc39 -> 9.8.0-1.fc40)
  libvirt-daemon-driver-nodedev (9.7.0-1.fc39 -> 9.8.0-1.fc40)
  libvirt-daemon-driver-qemu (9.7.0-1.fc39 -> 9.8.0-1.fc40)
  libvirt-daemon-driver-storage-core (9.7.0-1.fc39 -> 9.8.0-1.fc40)
  libvirt-daemon-driver-storage-disk (9.7.0-1.fc39 -> 9.8.0-1.fc40)
  libvirt-daemon-driver-storage-iscsi (9.7.0-1.fc39 -> 9.8.0-1.fc40)
  libvirt-daemon-driver-storage-iscsi-direct (9.7.0-1.fc39 -> 9.8.0-1.fc40)
  libvirt-daemon-driver-storage-logical (9.7.0-1.fc39 -> 9.8.0-1.fc40)
  libvirt-daemon-log (9.7.0-1.fc39 -> 9.8.0-1.fc40)
  libvirt-libs (9.7.0-1.fc39 -> 9.8.0-1.fc40)
  qemu-audio-spice (2:8.1.1-1.fc39 -> 2:8.1.1-1.fc40)
  qemu-block-curl (2:8.1.1-1.fc39 -> 2:8.1.1-1.fc40)
  qemu-char-spice (2:8.1.1-1.fc39 -> 2:8.1.1-1.fc40)
  qemu-common (2:8.1.1-1.fc39 -> 2:8.1.1-1.fc40)
  qemu-device-usb-host (2:8.1.1-1.fc39 -> 2:8.1.1-1.fc40)
  qemu-device-usb-redirect (2:8.1.1-1.fc39 -> 2:8.1.1-1.fc40)
  qemu-guest-agent (2:8.1.1-1.fc39 -> 2:8.1.1-1.fc40)
  qemu-img (2:8.1.1-1.fc39 -> 2:8.1.1-1.fc40)
  qemu-kvm-core (2:8.1.1-1.fc39 -> 2:8.1.1-1.fc40)
  qemu-system-x86-core (2:8.1.1-1.fc39 -> 2:8.1.1-1.fc40)
  qemu-ui-opengl (2:8.1.1-1.fc39 -> 2:8.1.1-1.fc40)
  qemu-ui-spice-core (2:8.1.1-1.fc39 -> 2:8.1.1-1.fc40)
```

**Comment by jelly** [comment]
Clicking `add` without any selection now gives a different error then previously. However this should never happen, as a user needs to make a selection the `add` button should be disabled unless a selection is made.

**Comment by skobyda** [comment]
> Might be worth reporting however that we used to get `unsupported configuration` instead of an xml error. @skobyda is this libvirt-dbus?

No need to report it, libvirt just changed the error message at https://www.mail-archive.com/libvir-list@redhat.com/msg239931.html , bu the functionality is the same.

Additionally I agree that it should be disabled. It seems that the "no-device" value comes from my code: https://github.com/cockpit-project/cockpit-machines/blob/main/src/components/vm/overview/watchdog.jsx#L71 . The "no-device" doesn't do anything, it's not used nor compared to anything anywhere, and it never was expected value by libvirt. No idea why I used that value (maybe it had some meaning which was lost in various refactorings...)
Anyway, disabling the "Add" button when user doesn't select any watchdog action makes sense, I'll start working on it first thing morning

**Comment by skobyda** [comment]
Ahh, now I remember why we don't disable the button. When no watchdog is yet attached to a VM, then no action is pre-selected by default (which is correct). However if we decide to disable the button when no selection is made, the "Add" button would be disabled immediatelly as user opens the dialog.

[Screencast from 2023-10-12 10-50-54.webm](https://github.com/cockpit-project/cockpit-machines/assets/42733240/7ba16088-159f-4852-be4a-99fa08bb4ab7)

Now I remember that we had discussion about this when implementing watchdog, and decided that this is not good user experience. I.e. user only opens dialog, they didn't do anything yet, and we are basically telling them that something is already wrong by having a disabled button. That's confusing.

So instead, I think we should just have some validation when user clicks on "Add"  to check that user selected something, and disable button only as a result of said validation.
