### ISSUE TITLE
Can't install the VM

### ISSUE THREAD

**Issue by jc-discdev** [cockpit-project/cockpit-machines#1266]
Hi, the program just freezes before start, it gives this error: ERROR internal error: process exited while connecting to monitor: 2023-10-19T16:09:26.837304Z qemu-system-aarch64: can't apply global cortex-a57-arm-cpu.hv-relaxed=on: Property 'cortex-a57-arm-cpu.hv-relaxed' not found Domain installation does not appear to have been successful. If it was, you can restart your domain by running: virsh --connect qemu:///system start LVM_UbuntuTest otherwise, please restart your installation, it also can't find vgabios-virtio.bin.

How could I fix it? Thanks.

**Comment by jc-discdev** [comment]
Ubuntu 22.04LTS

**Comment by jelly** [comment]
On what kind of hardware is this? It sounds like an ARM board?

**Comment by KKoukiou** [comment]
Try setting "copy host CPU configuration".

**Comment by sumguy774** [comment]
I had an issue with installing on Ubuntu server latest and then I simply just did sudo apt install cockpit-machines and it worked for me

**Comment by marusak** [comment]
No reply, closing
