### ISSUE TITLE
Add a button to export vm

### ISSUE THREAD

**Issue by Ludo-code** [cockpit-project/cockpit-machines#1268]
Hello,

I have one idea, it's simply to add an export button for virtual machine, I think i'ts would be nice if we can with this export button to export on another volume, or simply download it...

**Comment by KKoukiou** [comment]
If you 're trying to move the VM to another server you want to take a look at VM migration.
If you want to download the disk or snapshots to another server, this is not a scenario we want to support, as it's not anyhow a common usecase. Please use scp from terminal.
