### ISSUE TITLE
empty Operating System list

### ISSUE THREAD

**Issue by MoscowStyle** [cockpit-project/cockpit-machines#129]
Hi
VM stopped being created
why did it break?
Centos 8

![vm](https://user-images.githubusercontent.com/79848497/115843307-5c0d7e00-a427-11eb-9302-698930359b25.JPG)

**Comment by martinpitt** [comment]
What do you mean "break"? As the dialog says, you need to pick an Operating System.

**Comment by MoscowStyle** [comment]
> Что значит «перерыв»? Как говорится в диалоговом окне, вам нужно выбрать операционную систему.

sorry for my bad english
there is nothing in the choice of operating systems
![vm](https://user-images.githubusercontent.com/79848497/115847204-629df480-a42b-11eb-8475-317c674e4c9b.JPG)

**Comment by martinpitt** [comment]
I see, thanks! that wasn't clear in your original report. @KKoukiou , missing libosinfo? does that ring a bell?

**Comment by MoscowStyle** [comment]
> Ясно спасибо! это не было ясно в вашем исходном отчете. @KKoukiou , отсутствует libosinfo? это звонит в колокол?
installed- libosinfo-1.8.0-1.el8.x86_64

**Comment by MoscowStyle** [comment]
> I see, thanks! that wasn't clear in your original report. @KKoukiou , missing libosinfo? does that ring a bell?

installed- libosinfo-1.8.0-1.el8.x86_64

**Comment by KKoukiou** [comment]
@MoscowStyle What version of osinfo-db do you have installed? `rpm -qi osinfo-db`

Also please check for errors in the browser console and paste here if you see something that looks suspicious.

**Comment by MoscowStyle** [comment]
> @MoscowStyle Какую версию osinfo-db вы установили?`rpm -qi osinfo-db`
> 
> Также проверьте наличие ошибок в консоли браузера и вставьте сюда, если увидите что-то подозрительное.

![vm](https://user-images.githubusercontent.com/79848497/115852135-6b44f980-a430-11eb-9040-905041232c11.JPG)

**Comment by MoscowStyle** [comment]
![vm](https://user-images.githubusercontent.com/79848497/115853626-0e4a4300-a432-11eb-886e-977559ce42a4.JPG)

**Comment by KKoukiou** [comment]
@MoscowStyle This looks ok as well. So there was a report sometime ago, which looked similar, but we never figured out what it actually caused, just that it was a python versoin issue.

See https://github.com/cockpit-project/cockpit/issues/15381#issuecomment-781983826

Do you want to try to ran that script as well locally, with python3 and see if you are getting any results? The output of the script is JSON, so pipe it to `jq` command to be human readable.

`python3 this-script.py | jq`

In addition you might want to check your browser console for errors.

**Comment by MoscowStyle** [comment]
added file with output

[call.txt](https://github.com/cockpit-project/cockpit-machines/files/6364622/call.txt)

**Comment by KKoukiou** [comment]
@MoscowStyle I just tried out your output from the script, basically replaced the script's output on my system with that, and even after all the filtering we do in the operating systems list in the UI I still had some operating systems in the dialog field. 

So the last thing that remains here, is really that this script fails to get called from inside cockpit on your system.
It really looks very similar to the issue I pasted above.

Would you be interested to build cockpit from sources? In that case i can send you a patch with extra debug messages and we can dig it deeper from there on. (I am sorry that there is not an easy solution for you here)

**Comment by MoscowStyle** [comment]
@KKoukiou thanks for the help, I found the problem was incorrect permissions on the /home/$USER/.config/ folder
fixed the rights to the folder and it worked!

**Comment by KKoukiou** [comment]
Can you elaborate more so that we can can help users with the same problem in the future?
How does you config folder affect the operating system listing?

**Comment by MoscowStyle** [comment]
@KKoukiou In Centos8, there are several configuration files in the /home/$USER/.config/libvirt/ folder
I had rights not from the owner to this folder
after correcting the rights, everything worked.
it was my mistake from the very beginning

**Comment by KKoukiou** [comment]
Super thanks for figuring this out and getting back to us.
