### ISSUE TITLE
Make is failing on install

### ISSUE THREAD

**Issue by mkono87** [cockpit-project/cockpit-machines#1306]
Ubuntu 22.04

While using the commands to install this when it gets to make it fails with a syntax error.

`make package-lock.json && NODE_ENV= ./build.js
make[1]: Entering directory '/home/mike/cockpit-machines'
tools/node-modules make_package_lock_json
  REMOVE   node_modules
  CLONE    node_modules  [ref: 54816a80fde3539ab9a94d64f410b097f9910843]
  COPY     package-lock.json
make[1]: Leaving directory '/home/mike/cockpit-machines'
file:///home/mike/cockpit-machines/build.js:19
const esbuild = (await import(useWasm ? 'esbuild-wasm' : 'esbuild'));
                 ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
make: *** [Makefile:98: dist/manifest.json] Error 1`

**Comment by martinpitt** [comment]
Unfortunately Ubuntu 22.04's nodejs version is too old (12), you need at least version 16. Do this [in our development container](https://github.com/cockpit-project/cockpit/blob/main/HACKING.md#setting-up-development-container) (recommended), use [npm's n](https://www.npmjs.com/package/n), or on a newer Ubuntu release.
