### ISSUE TITLE
The VM could not be created with a SSH key and without "User password"

### ISSUE THREAD

**Issue by yunmingyang** [cockpit-project/cockpit-machines#1314]
Description of problem:
Create a VM with a SSH key and without "User password", there will be an warning shown below "User password" and the creation is blocked.

Version-Release number of selected components (if applicable):
cockpit-300.1-1.el8_9.x86_64
cockpit-machines-301.1.2.gb0140b7-1.fc38.noarch
libvirt-dbus-1.3.0-2.module+el8.9.0+18724+20190c23.x86_64

How reproducible:
100%

Steps to Reproduce:
1 Create a VM with a SSH key and without "User password"

Actual results:
1 There will be an warning shown below "User password" and the creation is blocked

Expected results:
1 The VM could be created with a SSH key and without "User password", and the SSH key could be put in the guest correctly

Additional info:

**Comment by KKoukiou** [comment]
I believe that's desired behavior as root ssh access is disabled by default. So the user would need to exist, and in order to create a user ones need to also set the user password.

**Comment by yunmingyang** [comment]
Emmm...but refer to some cloud platform, like openstack, some VM will have a user created and no password for this user. If user want to connect with the VM, they need to user the credential file. So I think maybe we could support this scenario

**Comment by martinpitt** [comment]
It would mean that there is no way to do any administration on that VM though, as that user is the only way to log in, and `sudo` can't work without a password. Or would that be passwordless sudo then?

Sorry that this slipped through the cracks, we are seriously understaffed now..
