### ISSUE TITLE
Creating a new VM cannot select stored ISO: watching is not implemented, use fswatch1

### ISSUE THREAD

**Issue by codykoppelman** [cockpit-project/cockpit-machines#1353]
I Updated Cockpit to the latest version (264 before update) Running Ubuntu 22.04 LTS
I've always had my ISO stored under /srv/iso/

1. Create VM
2. Installation Type: Local Install Media
3. Installation Source: I start typing in my path and I receive this message below: 
`watching is not implemented, use fswatch1`
5. If I put in the full path it cannot be found: Screenshot

Any other information needed I'll be happy to provide.
Cockpit Version: 306-1~bpo22.04.1
![Full path](https://github.com/cockpit-project/cockpit-machines/assets/17027197/9cd22c4e-c884-4b84-bbd2-269df4268938)
![image](https://github.com/cockpit-project/cockpit-machines/assets/17027197/e11f2ed9-a847-4e3a-829e-9ab7b8d0c2b5)

**Comment by jelly** [comment]
What version of machines do you have installed? It looks like you updated cockpit without updating machines?

**Comment by codykoppelman** [comment]
> What version of machines do you have installed? It looks like you updated cockpit without updating machines?


I apologize. Since I used apt backports to install the newest cockpit, I did not even think that I would have to do the same for all of my plugins.

I updated cockpit-machines using the backports repo and it works now. Thanks!

I'll Close this. However, this should be apart of the instructions when installing cockpit or documented somewhere because there are no search results relating to this.

**Comment by garrett** [comment]
@codykoppelman: It's been on the website for a while:

https://cockpit-project.org/running.html#ubuntu

> When updating Cockpit-related packages and any dependencies, make sure to use -t ...-backports as above, so backports are included.

Is there a way we can better phrase this or highlight it that would make it more obvious? Or is it just too easy to overlook a message like that?
