### ISSUE TITLE
Source path is always empty when picking host directories

### ISSUE THREAD

**Issue by matriculus** [cockpit-project/cockpit-machines#1367]
### Explain what happens

1. Install `cockpit` for ubuntu as defined in the official documentation.
2. Install `cockpit-*` to install additional features for storage, network, vm, etc.
3. Create a vm (any setting) with iso file located in host (error)
![image](https://github.com/cockpit-project/cockpit/assets/10431830/9a90fbe4-c58d-4244-9c73-3cd7aac099d3)

5. when step 3 fails, create vm by giving url for iso and create vm
6. share a directory from host to vm (error)
![image](https://github.com/cockpit-project/cockpit/assets/10431830/29eab833-5b34-4bca-964a-a483d22a2e42)

### Version of Cockpit

306-1~bpo22.04.1

### Where is the problem in Cockpit?

Storage

### Server operating system

Ubuntu

### Server operating system version

22.04.3

### What browsers are you using?

Chrome

**Comment by mauroao** [comment]
I have the same problem here

**Comment by M4urici0GM** [comment]
same

**Comment by M4urici0GM** [comment]
Update:
It seems a problem with current apt version, i was able to resolve the issue removing the current version and install latest:
```
sudo apt remove --purge cockpit-machines
sudo apt install -y cockpit-machines=303-1~bpo22.04.1
```
If the above version is not available, search the latest version with `apt search '^cockpit-machines.*'`
install, restart cockpit, the issue should be gone.

**Comment by Ejz9** [comment]
I downloaded the latest tar file from the releases tab. From there I ran `tar xf (that file you downloaded)` to extract it. Then I ran make install in the folder and voila (at least for me).

**Comment by matriculus** [comment]
I will try this out then

**Comment by chiennht** [comment]
> I downloaded the latest tar file from the releases tab. From there I ran `tar xf (that file you downloaded)` to extract it. Then I ran make install in the folder and voila (at least for me). I originally was using version 265 from apt.
> 
> Version: Ubuntu Latest.

work for me, from 265 to 304 Ubuntu 22.04.04

**Comment by ilmtr** [comment]
How do I install this on Ubuntu 22.04.04 LTS?  As I only have version 265 available and that seems to be the default version for Ubuntu 22.04.04 LTS.  https://packages.ubuntu.com/jammy/s390x/cockpit-machines

`user@server:~$ apt search '^cockpit-machines.*'
Sorting... Done
Full Text Search... Done
cockpit-machines/jammy 265-1 all
  Cockpit user interface for virtual machines`

**Comment by martinpitt** [comment]
@ilmtr Right, from backports. Looks like it's fixed for you now?
