### ISSUE TITLE
test flake: virtinterfaced crashes in g_malloc()

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit-machines#1391]
Tests failed on 6d895592995552c7aeae4b0a9918413f51705cb9, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240118-015433-6d895592-fedora-39-updates-testing/log.html)
[bodhi updates](https://bodhi.fedoraproject.org/updates/?search=&status=testing&status=stable&releases=F39)

**Comment by jelly** [comment]
```
Module libvirt.so.0 from rpm libvirt-9.7.0-2.fc39.x86_64
Module virtinterfaced from rpm libvirt-9.7.0-2.fc39.x86_64
Stack trace of thread 2317:
#0  0x00007fcb9d58e834 __pthread_kill_implementation (libc.so.6 + 0x90834)
#1  0x00007fcb9d53c8ee raise (libc.so.6 + 0x3e8ee)
#2  0x00007fcb9d5248ff abort (libc.so.6 + 0x268ff)
#3  0x00007fcb9d5257d0 __libc_message.cold (libc.so.6 + 0x277d0)
#4  0x00007fcb9d5987a5 malloc_printerr (libc.so.6 + 0x9a7a5)
```

Seems libvirt crashed

**Comment by martinpitt** [comment]
I've seen this in other PRs as well (also e.g. in c8s), it's not specific to updates-testing. It's just a rare crash. I've tried for 30mins to reproduce it locally and then gave up.

**Comment by martinpitt** [comment]
The annoying thing is that it crashes with an ABRT but doesn't actually print any assertion message. So I didn't file a bug report either.

**Comment by martinpitt** [comment]
Then again, this ABRTs in malloc(), so maybe it's just running out of memory? I'm not sure if it's the same crash that I looked at last week, I didn't keep the URL.

**Comment by martinpitt** [comment]
Same failure in https://cockpit-logs.us-east-1.linodeobjects.com/pull-1393-20240118-214818-cddb5e8b-fedora-39-devel/log.html#69

**Comment by martinpitt** [comment]
https://cockpit-logs.us-east-1.linodeobjects.com/pull-1399-20240124-130142-e14a91d3-fedora-38/log.html#80

**Comment by martinpitt** [comment]
https://cockpit-logs.us-east-1.linodeobjects.com/pull-1429-20240208-095258-546ddf20-fedora-39-devel/log.html#37

**Comment by jelly** [comment]
And: https://cockpit-logs.us-east-1.linodeobjects.com/pull-1432-20240208-104519-fcd215b4-fedora-38/log.html#57

**Comment by martinpitt** [comment]
Today: https://cockpit-logs.us-east-1.linodeobjects.com/pull-5903-20240212-230634-e54961ef-fedora-39-firefox-cockpit-project-cockpit-machines/log.html#60

**Comment by martinpitt** [comment]
The journal actually shows this:

    virtinterfaced[2702]: free(): invalid pointer

So it's memory corruption, not OOM or similar. However, it occured to me that we don't restart the daemon in between destroying and restoring the data dirs -- that might confuse it? Let's try to do that.

**Comment by martinpitt** [comment]
There's actually more than one crash here: In [this one](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1432-20240208-104519-fcd215b4-fedora-38/log.html#57), that's a destructive test, and it crashes pretty much right after startup in `udevInterfaceLookupByMACString()`:
```
Feb 08 10:59:50 fedora-38-127-0-0-2-2201 systemd[1]: Started virtinterfaced.service - Virtualization interface daemon.
Feb 08 10:59:52 fedora-38-127-0-0-2-2201 systemd-coredump[1949]: Process 1858 (virtinterfaced) of user 0 dumped core.
virtinterfaced[1858]: Assertion '*q > 0' failed at src/libudev/libudev.c:91, function udev_ref(). Aborting.
```

There is no matching bugzilla or Google hit for that.

[This](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5903-20240212-230638-e54961ef-fedora-39-cockpit-project-cockpit-machines/log.html) and [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5903-20240212-230638-e54961ef-fedora-39-cockpit-project-cockpit-machines/log.html#9) failure are similar, they also crashed in `udevInterfaceLookupByMACString()`, albeit with a slightly different error:
```
virtinterfaced[2379]: malloc(): unaligned fastbin chunk detected
```

**Comment by martinpitt** [comment]
Naughtied in https://github.com/cockpit-project/bots/pull/5981
