### ISSUE TITLE
Unable to create external snapshot on VM with cdrom device that contains no media

### ISSUE THREAD

**Issue by briansmith0** [cockpit-project/cockpit-machines#1433]
Using Fedora rawhide with:

cockpit-310.1-1.fc40.x86_64
cockpit-machines-306-1.fc40.noarch

I am unable to create an external snapshot if the VM has a cdrom device that contains no ISO media (see error screenshot below).  This is a likely scenario for any VM's installed from an ISO image.  

![Screenshot from 2024-02-08 11-52-52](https://github.com/cockpit-project/cockpit-machines/assets/60192516/a55924df-60e1-4def-b640-ed83b245a7a3)

**Comment by martinpitt** [comment]
Thanks @briansmith0 ! I can reproduce and created a test case for it.
