### ISSUE TITLE
Error log full of "multiple matching interfaces found: the MAC address '<snip>' matches multiple interfaces" messages

### ISSUE THREAD

**Issue by JeffWDH** [cockpit-project/cockpit-machines#1458]
OS: Oracle Linux 9 

Issue:
On a system with multiple VLANs and a bridge per VLAN, browsing to the cockpit-machines page causes many "error" messages. So much so that it can cause real error messages to get lost. 

How to reproduce:
- Have multiple VLAN and Bridge interfaces. These share the mac address of the source interface by default. Note, in my case I have 6 VLAN interfaces, and 6 Bridges for VMs to be able to access the specific VLANs. 
- Browse to https://system:9090/machines
- View logs at https://system:9090/system/logs#/?priority=err

Example logs:
![image](https://github.com/cockpit-project/cockpit-machines/assets/13274150/f4fb7781-6a2f-4a9d-a68b-6cacc11e3ad2)

Full error details:
```
multiple matching interfaces found: the MAC address '<snip>' matches multiple interfaces

CODE_FILE
    ../src/rpc/virnetclientprogram.c
CODE_FUNC
    virNetClientProgramDispatchError
CODE_LINE
    172
LIBVIRT_CODE
    59
LIBVIRT_DOMAIN
    26
LIBVIRT_SOURCE
    util.error
PRIORITY
    3
SYSLOG_FACILITY
    3
_BOOT_ID
    16610a484a1e428099b7af72d723f627
_CAP_EFFECTIVE
    1ffffffffff
_CMDLINE
    /usr/sbin/virtqemud --timeout 120
_COMM
    virtqemud
_EXE
    /usr/sbin/virtqemud
_GID
    0
_HOSTNAME
    <snip>
_MACHINE_ID
    bde131f89a8442ff825c161adaf66635
_PID
    1265
_RUNTIME_SCOPE
    system
_SELINUX_CONTEXT
    system_u:system_r:virtd_t:s0-s0:c0.c1023
_SOURCE_REALTIME_TIMESTAMP
    1708717123631215
_SYSTEMD_CGROUP
    /system.slice/virtqemud.service
_SYSTEMD_INVOCATION_ID
    5c0696069fca415ab5b53c10fd42c06b
_SYSTEMD_SLICE
    system.slice
_SYSTEMD_UNIT
    virtqemud.service
_TRANSPORT
    journal
_UID
    0
__CURSOR
    s=20779a93dee74b229c907bfa5d27c257;i=923;b=16610a484a1e428099b7af72d723f627;m=4babcc58;t=61211b52cf8b5;x=2b2830867c210d34
__MONOTONIC_TIMESTAMP
    1269550168
__REALTIME_TIMESTAMP
    1708717123631285
```

The same error can be triggered with this virsh command:
```
[root@system]# virsh iface-name <snip>
error: failed to get interface '<snip>'
error: multiple matching interfaces found: the MAC address '<snip>' matches multiple interfaces
```

I understand that it is libvirt triggering this error but cockpit seems to be attempting to do this many times when trying to access the web interface Any suggestions on how to filter these messages from the logs would be appreciated as they are mostly useless.

**Comment by JeffWDH** [comment]
This seems to have went away after updating the OS to 9.4.

**Comment by garrett** [comment]
This doesn't look Cockpit related, but related to libvirt.

I'm, happy upgrading fixed it for you!
