### ISSUE TITLE
IP isn’t showing.

### ISSUE THREAD

**Issue by AllyPallies** [cockpit-project/cockpit-machines#147]
Cockpit version: Latest
OS: Ubuntu
Page: VM page

looked everywhere I can’t figure out why my VM’s fail to show IP’s of the VM it’s using.

Steps to reproduce

1. Head to the VM page
2.click on any VM
3.head to the network interface I’m unable to see the VM’s IP for FreeBSD, Ubuntu and Windows I’m very unclear how to fix this or what package the VM’s need to install.

**Comment by KKoukiou** [comment]
@AllyPallies what's the output of:
```
$ sudo virsh domifaddr my-vm 
```
Does that contain an IP? Something like this:
```
 Name       MAC address          Protocol     Address
-------------------------------------------------------------------------------
 vnet0      52:54:00:b3:58:51    ipv4         192.168.122.225/24

```

If there is an IP listed there you should see it also in the VM details.
Make sure to replace 'my-vm' with your VM's name.

Also please note the exact cockpit-machines version, latest varies per distrobution and distro release so it's not very enlightening.

**Comment by AllyPallies** [comment]
@KKoukiou No that isnt showing anything honestly its like a package is missing or something odd is going on.
here is the output
willzor@mainserver:~$ sudo virsh domifaddr OpenSense
[sudo] password for willzor:
 Name       MAC address          Protocol     Address
-------------------------------------------------------------------------------

willzor@mainserver:~$ sudo virsh list
 Id   Name        State
---------------------------
 1    pfsense     running
 2    FreeNAS     running
 4    OpenSense   running

willzor@mainserver:~$ sudo virsh domifaddr FreeNAS
 Name       MAC address          Protocol     Address
-------------------------------------------------------------------------------

**Comment by KKoukiou** [comment]
@AllyPallies as you show above, it's not a problem of the UI, the cli can't detect any IP address either. Check this thread here, https://unix.stackexchange.com/a/549474/163281 

It has to do with how you have configured the NICs of your VM. I will move this issue to the discussion section, since it is something specific to your confuguration and I 'd like to keep issues list for generic bugs.
