### ISSUE TITLE
🔴 Machines pixels changed with  chromium 122

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit-machines#1472]
Tests failed on 23a551d1bb25a80cc78dfc85d4abbc799dbf1e77, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240301-015150-23a551d1-fedora-39-updates-testing/log.html)
[bodhi updates](https://bodhi.fedoraproject.org/updates/?search=&status=testing&status=stable&releases=F39)

**Comment by martinpitt** [comment]
This looks like fallout from yesterday's Chromium update? I'll send a PR.
