### ISSUE TITLE
nightly failure: virtinterfaced crashed in udevConnectListAllInterfaces

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit-machines#1490]
The job `fedora-39/updates-testing` failed on commit 669ecd3a9b6fcb2520747814b1bf033a512ef808.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-669ecd3a-20240312-014207-fedora-39-updates-testing/log.html

**Comment by martinpitt** [comment]
This is similar to https://github.com/cockpit-project/bots/issues/5979 but apparently some violation.
