### ISSUE TITLE
Creating a Virtual Network, IPv4 address or IPv4 address space?

### ISSUE THREAD

**Issue by brwnrclse** [cockpit-project/cockpit-machines#1567]
When trying to define a virtual network I'm met with an error that I can't understand. When defining a network I assume the 'IPv4 address' field means the 'Network Address' but an error occurs that says "IPv4 address cannot be same as the network identifier".
 
![image](https://github.com/cockpit-project/cockpit-machines/assets/22730252/6cad9c27-43dc-45e9-9efa-750a31f0164d)

Looking at [virt-manager](https://virt-manager.org) documentation/screenshots, here I see a 'Network' field and not an 'IPv4 address'  field (see [here](https://wiki.libvirt.org/TaskRoutedNetworkSetupVirtManager.html))

![image](https://virt-manager.org/static/virt-manager-host-networks.png)
![image](https://wiki.libvirt.org/images/Virtual_network_wizard_routed_02_choose_ipv4_range.png)

What should I enter in cockpit under 'IPv4 address' if not the network address?

![image](https://github.com/cockpit-project/cockpit-machines/assets/22730252/d3360dc9-756a-4422-8cda-778c59c50d91)

**Comment by mvollmer** [comment]
> What should I enter in cockpit under 'IPv4 address' if not the network address?

The "IPv4 address" will be the address of the bridge device on the host. Most often this will probably be the first address in the network, such as 192.168.122.1.  The "Create virtual network " dialog has this as the default in the "IPv4 address" field.

**Comment by brwnrclse** [comment]
Is it possible to just mimic the behavior of virt-manager, I don't need anything clever or silently changed? No device should be assigned the network address so not sure why cockpit is producing a difference output than virt-manager for the same input

See here:

![image](https://wiki.libvirt.org/images/Virtual_network_wizard_routed_04_choose_network_type.png)

From https://wiki.libvirt.org/VirtualNetworking.html#routed-mode-example

![image](https://github.com/cockpit-project/cockpit-machines/assets/22730252/a147fc6c-c1e1-43dc-9db4-c22a19e12f54)

**Comment by brwnrclse** [comment]
Why open a pull request before we've even agreed on what needs to be done? A network identifier is not always .0 and a gateway is not always .1

**Comment by brwnrclse** [comment]
Is cockpit asking for the gateway host ip address here? 

![cockpit-virtual-network-001](https://github.com/cockpit-project/cockpit-machines/assets/22730252/2a959db2-6c1d-4e2e-a581-d602817b1aba)

**Comment by brwnrclse** [comment]
If I'm able to enter my network configuration in virt-manager the way I need would cockpit see that configuration? Or am I locked to this interface

**Comment by brwnrclse** [comment]
The pull request attached to this issue does not resolve the issue so I'll close this now and reopen another to try and explain again

**Comment by martinpitt** [comment]
@brwnrclse Please let's keep the discussion in one place, i.e. this one. The attached PR wasn't even reviewed, let alone landed -- that can/should certainly be changed.

**Comment by mvollmer** [comment]
> If I'm able to enter my network configuration in virt-manager the way I need would cockpit see that configuration?

Yes, both virt-manager and Cockpit work via the same API and can see and modify the same virtualization configuration. You could also use `virsh`, for example, if you are more comfortable on the command line.

**Comment by mvollmer** [comment]
> The pull request attached to this issue does not resolve the issue so I'll close this now and reopen another to try and explain again

Right, I didn't understand that you were trying to create a specific mode. As far as I can see, Cockpit does not support the "routed" mode yet.

**Comment by mvollmer** [comment]
> And for my curiosity, if the 'routed' mode is not supported what does 'Open' forward mode in cockpit do?

My understanding is that it sets `<forward mode="open" />` in the network XML definition, which is documented here:

    https://libvirt.org/formatnetwork.html

as

> As with mode='route', guest network traffic will be forwarded to the physical network via the host's IP routing stack, but there will be no firewall rules added to either enable or prevent any of this traffic. When forward='open' is set, the dev attribute cannot be set (because the forward dev is enforced with firewall rules, and the purpose of forward='open' is to have a forwarding mode where libvirt doesn't add any firewall rules). This mode presumes that the local LAN router has suitable routing table entries to return traffic to this host, and that some other management system has been used to put in place any necessary firewall rules. Although no firewall rules will be added for the network, it is of course still possible to add restrictions for specific guests using [nwfilter rules](https://libvirt.org/formatnwfilter.html) on the guests' interfaces.) Since 2.2.0


When I activate such a network, a new "virbr" device is created and the address from the "IPv4 address" field is assigned to it. The same thing happens with mode="nat" and mode="route". The differences between these modes must be somewhere else, I have no experience with this.

In any case, there seems to be a bridge device also with "open" mode, and thus asking for a IP address for it doesn't immediately strike me as wrong.

**Comment by mvollmer** [comment]
> I admittedly haven't looked over everything in the repository so apologies if not supporting 'routed' mode is already stated somewhere. 

I think we should consider supporting this mode. The mode does not seem to effect more than a single attribute in the XML definition.
