### ISSUE TITLE
migration: consider using host name instead of libvirt URI for the migration destination  

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit-machines#163]
Reported here: https://github.com/cockpit-project/cockpit-machines/pull/15#issuecomment-838755703

* Typing the qemu+ssh:// prefix and the /system suffix are both quite cumbersome and error prone. As we don't currently support any other protocol nor session qemu, we should simplify this to just typing the destination host name IMHO.

**Comment by martinpitt** [comment]
@skobyda replied to that: "Other protocols, such as qemu+tcp, are supported and would work fine with what this PR provides.
Also user can migrate from a system to a session connection and vice versa, so '/system' and '/session' should be kept editable
The only thing which could be not editable is just the "qemu" part."

So I suppose that's ok for now.

**Comment by garrett** [comment]
What happens if someone just enters the hostname? Will it choose a default protocol or will it just error out?

**Comment by skobyda** [comment]
> What happens if someone just enters the hostname? Will it choose a default protocol (and reuse the /system or /session from the existing VM on the origin host) or will it just error out?

If you input only the address, let's say "192.168.12.1", it will result in an error message `error: no connection driver available for URI '192.168.12.1' does not include a driver name`. So the driver, the `qemu+ssh://` prefix, is compulsory.

The driver consists of qemu part, which is the only one supported by the cockpit, and transport protocol. Multiple transport protocols are supported `tls|unix|ssh|ext|tcp|libssh2|libssh` for user to use.

the `system / session` suffix is optional. You don't have to input it and libvirt will choose the default for given user (system for admin, session for local user)

**Comment by KKoukiou** [comment]
Do we really support / want to support migration between system and session connection type?  That's pretty useless I feel. I would just always choose the connection that VM is currently using.
