### ISSUE TITLE
Delete storage from origin host after migration

### ISSUE THREAD

**Issue by skobyda** [cockpit-project/cockpit-machines#165]
Created from @garrett comment in #15 

> ![117332031-a535e700-ae97-11eb-8538-8475268e6fc4](https://user-images.githubusercontent.com/42733240/117972110-0132bc80-b32b-11eb-9454-d1b9989d6627.png)
> 
> The checkbox is "progressive disclosure" and only appears when the radio above is selected. But, again: This shouldn't land in this PR. I'm just finding a place for it in the design so we don't have to "shoehorn" it in later. (That is, so we don't have to find a place to shove it in without having consideration in the first place.)

**Comment by KKoukiou** [comment]
Since on RHEL this subfeature is not present let's not put more effort into this.
