### ISSUE TITLE
Raspberry Pi 5 | After installing cockpit-machines error 'operation failed: Cannot find CPU model with PVR 0xd0b' is logged

### ISSUE THREAD

**Issue by ps1noob** [cockpit-project/cockpit-machines#1652]
1. Installing cockpit on Raspberry Pi OS (Bookworm) 
2. Installing cockpit-machines
3. Error from title is logged

Right now (i've not created any virtual machines) i am not having any difficulties, just wanted to report this.

**Comment by jelly** [comment]
Is that logged in the browser console? Or is it shown in the UI?

We check if you can run virtualization with:
```
virt-host-validate qemu | grep 'Checking for hardware virtualization
```

So maybe the output is from that command?

**Comment by ps1noob** [comment]
The log entry comes from the libvirtd.service, here the output from the "Logs" view:

> operation failed: Cannot find CPU model with PVR 0xd0b
> CODE_FILE
> ../../src/cpu/cpu_arm.c
> CODE_FUNC
> virCPUarmDecode
> CODE_LINE
> 641
> LIBVIRT_CODE
> 9
> LIBVIRT_DOMAIN
> 31
> LIBVIRT_SOURCE
> util.error
> PRIORITY
> 3
> SYSLOG_FACILITY
> 3
> _BOOT_ID
> feb1cfe36a25456dabeb7aaafb2b9f3f
> _CAP_EFFECTIVE
> 1ffffffffff
> _CMDLINE
> /usr/sbin/libvirtd --timeout 120
> _COMM
> libvirtd
> _EXE
> /usr/sbin/libvirtd
> _GID
> 0
> _HOSTNAME
> thepirouter
> _MACHINE_ID
> 29fdb3409ccb4292bc3fa560c51d1091
> _PID
> 4791
> _RUNTIME_SCOPE
> system
> _SOURCE_REALTIME_TIMESTAMP
> 1716750844885271
> _SYSTEMD_CGROUP
> /system.slice/libvirtd.service
> _SYSTEMD_INVOCATION_ID
> 3614e5c287374371b74ca6be92f39cf2
> _SYSTEMD_SLICE
> system.slice
> _SYSTEMD_UNIT
> libvirtd.service
> _TRANSPORT
> journal
> _UID
> 0
> __CURSOR
> s=8e7641175f9244c8a2914ea19af5b877;i=4363;b=feb1cfe36a25456dabeb7aaafb2b9f3f;m=1a865125;t=619603446fa99;x=46d1efd82bb6242a
> __MONOTONIC_TIMESTAMP
> 445010213
> __REALTIME_TIMESTAMP
> 1716750844885657
> __SEQNUM
> 17251
> __SEQNUM_ID
> 8e7641175f9244c8a2914ea19af5b877

What i also have found so far is the "4x unknown" entry under "System information" next to "CPU".

Here the output from the command you posted:

> root@thepirouter:~# virt-host-validate qemu | grep 'Checking for hardware virtualization'
> root@thepirouter:~# virt-host-validate qemu
>   QEMU: Checking if device /dev/kvm exists                                   : PASS
>   QEMU: Checking if device /dev/kvm is accessible                            : PASS
>   QEMU: Checking if device /dev/vhost-net exists                             : PASS
>   QEMU: Checking if device /dev/net/tun exists                               : PASS
>   QEMU: Checking for cgroup 'cpu' controller support                         : PASS
>   QEMU: Checking for cgroup 'cpuacct' controller support                     : PASS
>   QEMU: Checking for cgroup 'cpuset' controller support                      : PASS
>   QEMU: Checking for cgroup 'memory' controller support                      : WARN (Enable 'memory' in kernel Kconfig file or mount/enable cgroup controller in your system)
>   QEMU: Checking for cgroup 'devices' controller support                     : PASS
>   QEMU: Checking for cgroup 'blkio' controller support                       : PASS
>   QEMU: Checking for device assignment IOMMU support                         : WARN (Unknown if this platform has IOMMU support)
>   QEMU: Checking for secure guest support                                    : WARN (Unknown if this platform has Secure Guest support)

**Comment by jelly** [comment]
```
operation failed: Cannot find CPU model with PVR 0xd0b
CODE_FILE
../../src/cpu/cpu_arm.c
```

Seems libvirtd is not happy on the Raspberry Pi 5. I don't think this is a Cockpit problem but more a general ARM and libvirt issue. I don't have a RPI5 to replicate this so I cannot give any useful suggestions (except asking libvirt / searching on the web).

> What i also have found so far is the "4x unknown" entry under "System information" next to "CPU".

That's expected as ARM makes it harder to get the CPU model name. It would be nice if it didn't show unknown however.

**Comment by ps1noob** [comment]
Thanks for the clarification! So, i will look further into this issue at libvirt.
