### ISSUE TITLE
Research switch from internal to external snapshots

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit-machines#169]
libvirt  and qemu teams are promoting external snapshots usage against internal ones.
The 'revert' operation for the latter is missing still from he API however.

Doc links to read:
https://libvirt.org/kbase/merging_disk_image_chains.html
https://libvirt.org/kbase/incrementalbackupinternals.html
https://libvirt.org/kbase/live_full_disk_backup.html

**Comment by marusak** [comment]
This is happening in https://github.com/cockpit-project/cockpit-machines/pull/1280 but the support for external shapshot is still in progress from libvirt
