### ISSUE TITLE
Watching is not implemented, use fswatch1

### ISSUE THREAD

**Issue by piotrszpruta** [cockpit-project/cockpit-machines#1695]
### Explain what happens

While I'm trying to setup virtual machine from cockpit and select local iso, the only think appears as path is /.
When I'm trying to paste direct path I get this notification and cannot move forward.
![image](https://github.com/cockpit-project/cockpit/assets/38475451/af56fe16-ea79-4b9a-8d50-51ee02818aed)

### Version of Cockpit

311-1~bpo22.04.1

### Where is the problem in Cockpit?

None

### Server operating system

None

### What browsers are you using?

Chrome

**Comment by martinpitt** [comment]
Hmm, that sounds like https://github.com/cockpit-project/cockpit/commit/a3fad8f6e710 but that was fixed long ago in version 284 . Can you please give the output of `dpkg -l | grep cockpit`?

**Comment by piotrszpruta** [comment]
> Hmm, that sounds like [cockpit-project/cockpit@a3fad8f6e710](https://github.com/cockpit-project/cockpit/commit/a3fad8f6e710) but that was fixed long ago in version 284 . Can you please give the output of `dpkg -l | grep cockpit`?

Sure:
```
zcoder@zcoder-macmini:~$ dpkg -l | grep cockpit
ii  cockpit                                    311-1~bpo22.04.1                        all          Web Console for Linux servers
ii  cockpit-bridge                             311-1~bpo22.04.1                        amd64        Cockpit bridge server-side component
ii  cockpit-machines                           265-1                                   all          Cockpit user interface for virtual machines
ii  cockpit-networkmanager                     311-1~bpo22.04.1                        all          Cockpit user interface for networking
ii  cockpit-packagekit                         311-1~bpo22.04.1                        all          Cockpit user interface for apps and package updates
ii  cockpit-pcp                                264-1ubuntu0.22.04.1                    amd64        Cockpit PCP integration
ii  cockpit-storaged                           311-1~bpo22.04.1                        all          Cockpit user interface for storage
ii  cockpit-system                             311-1~bpo22.04.1                        all          Cockpit admin interface for a system
ii  cockpit-ws                                 311-1~bpo22.04.1                        amd64        Cockpit Web Service```

**Comment by martinpitt** [comment]
Ah yes, your cockpit-machines version is very old. Please also install the backports version (310). We don't test/support mixing backported cockpit base packages with old "extension" packages.

**Comment by piotrszpruta** [comment]
> Ah yes, your cockpit-machines version is very old. Please also install the backports version (310). We don't test/support mixing backported cockpit base packages with old "extension" packages.

The 310 or any newer version than 265-1 for cockpit-machines is not available on apt. Should I follow instructions from cockpit-machines repository?

**Comment by piotrszpruta** [comment]
> `sudo apt install -t jammy-backports cockpit-machines cockpit-pcp` (while you are at it..) should work.

Thank you, seems like this problem is solved. 
I have another one but will try to settle this up by myself.
