### ISSUE TITLE
"Launch remove viewer" does not download the "download" virt-viewer file. 

### ISSUE THREAD

**Issue by carbajgu** [cockpit-project/cockpit-machines#1799]
After clicking in the "Launch remove viewer" button, browser is no longer downloading the "download" file. Tested in Chrome and Firefox. This started to fail like three weeks ago. Alternative, I manually run: "virt-viewer" and pick the one started.
From cockpit/applications uninstalled/installed "machines", no luck.
New version was released but the issue still remains...

This is Fedora 40 with gnome.

**Comment by garrett** [comment]
I can reproduce this here too.

DevTools console in Firefox says:

> Content-Security-Policy: The page’s settings blocked the loading of a resource (frame-src) at data:application/x-virt-viewer,%5Bvirt-v… because it violates the following directive: “default-src 'self'” index.html

**Comment by garrett** [comment]
On Matrix, @jelly mentioned CSP changed in 0dcf8640b04cebccaec167718337d84523bf6f30, which is probably causing this.
