### ISSUE TITLE
Creating a VM should enforce libvirt's lower memory limit

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit-machines#188]
I run this in a standard `TEST_OS=fedora-34 make vm; bots/vm-run -s cockpit.socket fedora-34` VM from current main.

There are > 600 MB available:
```
total        used        free      shared  buff/cache   available
Mem:           1.1Gi       216Mi       614Mi       3.0Mi       263Mi       734Mi
```

I try to create a new VM with 300 MB of RAM, which should fit well:

![image](https://user-images.githubusercontent.com/200109/120425844-3d2bd100-c36f-11eb-9cb6-684342f4910a.png)

This fails:

![image](https://user-images.githubusercontent.com/200109/120425927-63ea0780-c36f-11eb-908c-eab8408e7a34.png)

Same error in the journal:

    libvirtd[590]: internal error: qemu unexpectedly closed the monitor: 2021-06-02T04:54:22.562549Z qemu-system-x86_64: -object memory-backend-ram,id=pc.ram,size=1610612736: cannot set up guest memory 'pc.ram': Cannot allocate memory

So somehow it tried to allocate 1.6 GB of RAM, even though it's supposed to be only 300 MB. I tried to change the RAM to different values, but it always seems to use that number.

When I use "PXE boot" instead, it uses `-object memory-backend-ram,id=pc.ram,size=314572800` which is correct.

FTR, this is my standard approach of testing PF/react-console updates like #184. I'd rather use "download an OS" so that I can test the keyboard as well; with PXE boot it doesn't get very far, and you only get the early BIOS boot screens, which don't allow any keyboard interactivity.

**Comment by martinpitt** [comment]
> which don't allow any keyboard interactivity.

FTR, that's actually wrong -- if you press Ctrl+B quickly enough, you get an iPXE interactive promt, and can test the keyboard.  So that's good enough for testing the VNC console (still no serial console test, though)

**Comment by KKoukiou** [comment]
Hey Martin, thanks for taking the time to report this. I tried to reproduce it locally but I fail to. When I create the VM I check the generated virt-install command, with ps aux | grep virt-install, to ensure that the memory parameter is passed correctly. I also checked the qemu command ran, in the /var/log/libvirt/qemu/vm.log.
There is see:
```
-object memory-backend-ram,id=pc.ram,size=314572800 \
```

When you have time can you check as well the virt-install cmd generated by your execution? and we can compare the qemu/libvirt versions we are using. 
I am on:
qemu-kvm-5.2.0-7.fc34.x86_64
libvirt-daemon-7.0.0-4.fc34.x86_64

**Comment by martinpitt** [comment]
As I said, I use our official fedora-34 test image, with a slightly older qemu:

    qemu-kvm-5.2.0-5.fc34.1.x86_64
    libvirt-daemon-7.0.0-4.fc34.x86_64

virt-install command looks correct to me:
```
/usr/bin/python3 /usr/bin/virt-install --connect qemu:///system --name test1 --os-variant centos7.0 --memory 300 --quiet --disk none --check path_in_use=off --noautoconsole --wait -1 --install os=centos7.0 --graphics spice,listen=127.0.0.1 --graphics vnc,listen=127.0.0.1
```

[/var/log/libvirt/qemu/test1.log](https://github.com/cockpit-project/cockpit-machines/files/6583543/test1.log) has it wrong, though:

    -m 1536 -object memory-backend-ram,id=pc.ram,size=1610612736 \

Running the above virt-install command on the shell reproduces it. But when reducing it a little bit, it's clear why:

```
# virt-install --name test1 --os-variant centos7.0 --memory 300 --disk none --wait -1 --install os=centos7.0
Using centos7.0 --location http://mirror.centos.org/centos-7/7/os/x86_64/
WARNING  Requested memory 300 MiB is less than the recommended 1024 MiB for OS centos7.0
WARNING  Unable to connect to graphical console: virt-viewer not installed. Please install the 'virt-viewer' package.

Starting install...
Retrieving file vmlinuz...                                                                                 | 6.5 MB  00:00:00     
Retrieving file initrd.img...                                                                              |  53 MB  00:00:04     
WARNING  Overriding memory to 1536 MiB needed for centos7.0 network install.
ERROR    internal error: process exited while connecting to monitor: 2021-06-02T09:54:47.558784Z qemu-system-x86_64: -object memory-backend-ram,id=pc.ram,size=1610612736: cannot set up guest memory 'pc.ram': Cannot allocate memory
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start test1
otherwise, please restart your installation.
```

So it's indeed libvirt-install second-guessing the RAM specification, unfortunately even with `--check all=off`. `--check=?` does not have anything specific to RAM size.

When I start the VM with `bots/vm-run -M 2048 -s cockpit.socket fedora-34` this works better, both with the above CLI command, and the GUI. This time I didn't touch the RAM setting:

![image](https://user-images.githubusercontent.com/200109/120461319-31093900-c39a-11eb-883a-37d5aae4f3ed.png)

(when I flip "GB" to "MB", I get "Up to 1976 MiB available on the host", so the "Up to 1 GiB available" is a gross rounding). It still overrides the chosen RAM setting:

![image](https://user-images.githubusercontent.com/200109/120461579-69107c00-c39a-11eb-965b-662fd935991e.png)

but at least it's running:

![image](https://user-images.githubusercontent.com/200109/120461737-8e9d8580-c39a-11eb-816f-dbde8a490a07.png)

(And ugh, it starts graphical anaconda.. So yes, that will not work with just 300 MB. I had thought it would be a CLI)

**Comment by martinpitt** [comment]
OK, so this is not "our" bug directly, at least not until there is a `--check ram=off`. But "our" parts are:

 - we should probably go back to enforced lower memory limits, and only keep the "warning, but use anyway" for disk (as that is not enforced)
 - the default should be ≥ the minimum size for that OS (i.e. 1.5 GiB in the above case, instead of 1 GB)

**Comment by KKoukiou** [comment]
@martinpitt I am a bit on the fence about this. 
We currently
* Prefill the dialog with the minimum recommeded memory when the user selected OS and when they insert the media and OS autodetections happens
* We show a warning about the minimum memory requirements.

![Screen Shot 2021-09-08 at 16 24 43](https://user-images.githubusercontent.com/14921356/132528051-886078f0-33d3-4012-9ca0-c8ada2dff410.png)

If the user decides to anyway use less than the recommended memory (which the dialog suggest) that means they took their steps to bypass the default options, and I feel we should allow them to do so.

**Comment by martinpitt** [comment]
@KKoukiou : Ack, agreed about the UI. This bug is somewhere in virt-install: It ignores the specified amount of RAM (`--memory 300`) and tells QEMU to allocate 1.5 GiB (`-m 1536 -object memory-backend-ram,id=pc.ram,size=1610612736`).  That's what should really be fixed.
