### ISSUE TITLE
The description is not entirely displayed if the description is too long during setting the VM description

### ISSUE THREAD

**Issue by yunmingyang** [cockpit-project/cockpit-machines#1888]
Description of problem:
When setting the VM description, if the string is too long, the description may not be entirely displayed

Version-Release number of selected components (if applicable):
cockpit-machines-322-11-g63ac3f46

**Comment by mvollmer** [comment]
This is too vague.

**Comment by yunmingyang** [comment]
![Screenshot from 2024-11-04 13-51-54](https://github.com/user-attachments/assets/b02507da-3430-4a4c-b39b-b70563dfd63b)
@mvollmer please see the picture, this description is 400 length 's', and you could see that the description is not fully displayed. So maybe we could compress the description, and instread with a hint, maybe like that
![Screenshot from 2024-11-04 14-48-22](https://github.com/user-attachments/assets/0a3ee8cb-6943-41bc-bdab-96c325fe2062)
Not sure whether patterfly has a internal style to implement that

**Comment by garrett** [comment]
FWIW: The description shouldn't truncate arbitrarily, but should wrap around.

**Comment by mvollmer** [comment]
> please see the picture, this description is 400 length 's', and you could see that the description is not fully displayed.

Ah, I see, thanks! Please try to provide concrete steps for reproduction in the future. Screenshots are indeed very helpful.
