### ISSUE TITLE
TestMultiMachineVNC fails on multihost warning with cockpit 329

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit-machines#1913]
The job `fedora-40/updates-testing` failed on commit 5baebf863be2f6f7ede5e5ab2bef165457ecbe6f.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-5baebf86-20241121-021953-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment]
Haha -- this is our multihost warning. So we either need to conditionally click this away with `self.system_before(329)` or configure that off in `cockpit.conf`. @mvollmer you should know what to do, right?

**Comment by martinpitt** [comment]
We have too many open pilot things, so taking this quick one for some co-piloting.
