### ISSUE TITLE
Cockpit KVM mouse controller issue

### ISSUE THREAD

**Issue by brunomgrocha** [cockpit-project/cockpit-machines#225]
Cockpit version: 239-1~bpo10+1
OS: Debian
Page:

**Comment by KKoukiou** [comment]
This has been also reported on Bugzilla, it's indeed still not fixed. https://bugzilla.redhat.com/show_bug.cgi?id=1913548

**Comment by KKoukiou** [comment]
Closing a duplicate of https://github.com/cockpit-project/cockpit-machines/issues/29
