### ISSUE TITLE
Don't offer live migration on non-shared storage

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit-machines#247]
According to the libvirt team, this is the support status:

Supported: Copy a disk from a shutdown VM (simple cp/scp)

Grey area: Live migrate a VM with shared storage

Not supported: Live Migrate a VM with non-shared storage

I am not sure, but I believe we currently offer the third scenario. Let's disable this then. That's the one which I was already wondering about in https://github.com/cockpit-project/cockpit-machines/pull/15#issuecomment-828969408 (most of the discussion happened on IRC, sorry), as that's not robust by design -- trying to copy a moving target.

I realize that we have to trust the user's input for "shared storage", as that's not something which we can detect. But we already have an option for it, and we do know whether the VM is running or paused/shut down.

**Comment by garrett** [comment]
This means we'll also need to either:
- redesign the migration dialog
- make it clear that the machine will be shut down (if it is running) and copied over when migrating
