### ISSUE TITLE
Unable to delete VM

### ISSUE THREAD

**Issue by nknguyengl** [cockpit-project/cockpit-machines#266]
Description of problem:
Failed to delete the vm disk images as expected on Confirm deletion dialog

Version-Release number of selected component (if applicable):
ubuntu 20.04
cockpit-machines 238
cockpit 248

Steps to Reproduce:
1. Install cockpit-machines package
2. Create a VM
3. Click the delete button
4. On confirm dialog, choose to delete associated storage files including disk image

![Snag_46d8ff4](https://user-images.githubusercontent.com/33523971/126633265-a0fad113-7237-4d97-b93d-164d3bbdbf50.png)

**Comment by KKoukiou** [comment]
Can you please try to upgrade to 248, it's available on backports.
I just tried to reproduce it and I don't see an issue here.  

If the failure persists I will ask you for more debug info.

**Comment by KKoukiou** [comment]
This was fixed in commit b5850e7539211ce6df77008c05ae5b61fcf6bc28.

The fix is already present in version 244.1.

https://github.com/cockpit-project/cockpit-machines/issues/178#issuecomment-845782019

**Comment by KKoukiou** [comment]
Hey sorry, I see now that ubuntu has no newer cockpit-machines. Please follow the conversation here https://github.com/cockpit-project/cockpit-machines/issues/275#issuecomment-886872671
