### ISSUE TITLE
Cant delete a VM

### ISSUE THREAD

**Issue by tgwaste** [cockpit-project/cockpit-machines#275]
Cockpit-machines version: 238
OS: Ubuntu 20.04.2 LTS

When trying to delete a VM I get an Ooops! in the upper right corner.
Nothing that tells me why.
The VM is powered off.
This happens if I have the path to the image checked or not.

When I look in /var/lib/libvirt/images it doesnt look like the image is there anymore.

**Comment by martinpitt** [comment]
What is your version of cockpit-machines? That standalone source/package isn't in Ubuntu yet, so presumably it's a relatively old version. Can you please open the JS console (Ctrl+Shift-J), then provoke the crash, and copy&paste the console output here? Thanks!

**Comment by tgwaste** [comment]
```
# dpkg -l | grep cockpi
ii  cockpit                              248-1~ubuntu20.04.1                   all          Web Console for Linux servers
ii  cockpit-bridge                       248-1~ubuntu20.04.1                   amd64        Cockpit bridge server-side component
ii  cockpit-machines                     238-1~ubuntu20.04.1                   all          Cockpit user interface for virtual machines
ii  cockpit-networkmanager               248-1~ubuntu20.04.1                   all          Cockpit user interface for networking
ii  cockpit-packagekit                   248-1~ubuntu20.04.1                   all          Cockpit user interface for packages
ii  cockpit-pcp                          248-1~ubuntu20.04.1                   amd64        Cockpit PCP integration
ii  cockpit-storaged                     248-1~ubuntu20.04.1                   all          Cockpit user interface for storage
ii  cockpit-system                       248-1~ubuntu20.04.1                   all          Cockpit admin interface for a system
ii  cockpit-ws                           248-1~ubuntu20.04.1                   amd64        Cockpit Web Service
```
Ctrl+Shift-J doesn't work.  Maybe it's different on Mac?

**Comment by tgwaste** [comment]
`index.js:31 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' https://host:9090". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.`

**Comment by KKoukiou** [comment]
This looks like https://github.com/cockpit-project/cockpit-machines/issues/178#issuecomment-845782019 but this was fixed in cockpit-machines 244.1

**Comment by tgwaste** [comment]
How do I get and apply this fix?

**Comment by KKoukiou** [comment]
@tgwaste sorry I just noticed that the update is not available on ubuntu.

@martinpitt can we get the new released cockpit-machines on ubuntu backports as we did cockpit https://packages.ubuntu.com/hirsute-backports/cockpit ? 


These versions are incompatible, and the new cockpit breaks the older cockpit-machines.

**Comment by tgwaste** [comment]
Any rough time frame on when I can expect this update to pop up ?

**Comment by martinpitt** [comment]
I'm on it -- yesterday evening I [uploaded 248 to Debian](https://tracker.debian.org/news/1245030/accepted-cockpit-machines-248-1-source-into-experimental/), now I [synced it over to Ubuntu impish](https://launchpad.net/ubuntu/+source/cockpit-machines/) (current development release). Once it landed there, I'll update the backports. This should take about a day.

**Comment by martinpitt** [comment]
The machinery is progressing, 248 is now in all stable ubuntu releases in backports: https://launchpad.net/ubuntu/+source/cockpit-machines/

It'll still take a few hours for the archive mirrors to catch up, though.

**Comment by tgwaste** [comment]
Updated.  Everything appears to be working fine now.  Many Thanks!
