### ISSUE TITLE
Allow swapping of cdrom image for VMs

### ISSUE THREAD

**Issue by wzzrd** [cockpit-project/cockpit-machines#283]
Page: Virtual machines

Currently it is only possible (or I'm missing it) to add a virtual cdrom drive during VM creation. After that, the only thing that can be added are hard disk images. Neither can the cdrom image "in" the cdrom drive be swapped for another (or, again, I'm missing how to do it).

It would be great if it were (a) possible to add a cdrom drive after VM creation, but more importantly, if it were possible to swap out the ISO image present "in" the virtual cdrom drive.

Reasoning: reinstalling existing VMs, with existing MAC addresses, existing DHCP reservations etc. for a new OS, upgrading the existing OS, installing software into the VM from a CD ISO etc.

**Comment by KKoukiou** [comment]
@wzzrd this is possible from cockpit-machines UI since https://cockpit-project.org/blog/cockpit-238.html

See 'Machines: VM disk creation supports a custom path' section.

**Comment by wzzrd** [comment]
Hi @KKoukiou,

Thanks for the reply, and thanks for the fix for one of my problems, but the second problem (unable to switch cdrom image) still remains, unless I'm overlooking something again. Is it possible to swap cdrom images? Or is the expected way to do that to remove and recreate the virtual cdrom drive?
