### ISSUE TITLE
Clarify exact meaning & limitations of 'direct attachment' network interface type

### ISSUE THREAD

**Issue by yrro** [cockpit-project/cockpit-machines#285]
When adding a network interface, there are three options for Interface Type.

* Virtual network: pretty clear what this means - attaches to a libvirt-defined network
* Bridge to LAN: pretty clear what this means - attaches to an existing bridge
* Direct Attachment: the mystery option!

I've done some rudimentary user research and when googling for [cockpit "direct attachment"](https://www.google.com/search?hl=en&q=cockpit%20%22direct%20attachment%22) there are not so many hits explaining what "Direct Attachment" means\*, but several from users puzzled as to why their newly created virtual machine is able to reach other hosts on their lan, but not the host running the VM, or other VMs on the same host.

* https://forum.openmediavault.org/index.php?thread/33829-virtual-machine-with-cockpit-with-networking-set-to-direct-attachment-issue/
* https://serverfault.com/questions/1013111/guest-vms-and-host-cant-ping-each-other
* https://github.com/cockpit-project/cockpit/issues/14676 😉

My first thought was changing the option to "Direct Attachment (macvtap)". But `macvtap` probably won't mean much to the users who asked the above questions (I happily used it myself for quite a while before I ever tried to create a second VM on the same host, and discovered the limitations of `macvtap` the hard way...

So my suggestion is to display some helpful text when "Direct Attachment" is chosen, explaining the following:

1. "Direct Attachment" requires `eth0` to be attached to a switch operating in Virtual Ethernet Port Aggregator (VEPA) mode for full network functionality.
2. Without a switch operating in VEPA-mode, the network interface will not be be to communicate with other virtual machines running on the same host, nor with the host itself.
3. If this communication is desired then try using 'Virtual network' or 'Bridge to LAN' instead.

I guess the text _could_ mention that the interface can be run in bridge/private/passthrough mode as well, but I don't think there's a way to change the mode in the `cockpit-machines` UI so probably best to omit this information.

Alternative text for the first paragraph above:

1. "Direct Attachment" attaches the guest to `eth0` via a `macvtap` interface. ~~As such,~~ for full network functionality, `eth0` must be attached to a switch operating in Virtual Ethernet Port Aggregator (VEPA) mode.

This is better in that it has the magic word `macvtap`, so people who already knows what that implies will instantly understand what it implies. But it's worse in that it front loads the explanation with more jargon.

----

\* unless you know enough about the software stack to dig into [RHEL's virtualization manual](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_virtualization/configuring-virtual-machine-network-connections_configuring-and-managing-virtualization#direct-attachment-of-the-virtual-network-device_types-of-virtual-machine-network-connections), or the 101-page long [libvirt Domain XML Format](https://www.libvirt.org/formatdomain.html#elementsNICSDirect) page.

**Comment by yrro** [comment]
#361 could do with a `detailHeadline` explaining the points above. Shall I just send a PR with some suggested wording?

**Comment by KKoukiou** [comment]
@yrro Hey thanks a lot for rechecking this! Indeed now that I re-see it some information about the VEPA limitations should be included. You can also take the info from here https://libvirt.org/formatdomain.html#direct-attachment-to-physical-interface


I am very happy to review your PR :)  thanks!
