### ISSUE TITLE
Add a way to select which console to attach to

### ISSUE THREAD

**Issue by yrro** [cockpit-project/cockpit-machines#286]
I've got VMs that look like this:

```
    <console type='pty' tty='/dev/pts/0'>
      <source path='/dev/pts/0'/>
      <target type='serial' port='0'/>
      <alias name='serial0'/>
    </console>
    <console type='pty'>
      <source path='/dev/pts/1'/>
      <target type='virtio' port='1'/>
      <alias name='console1'/>
    </console>
```

Cockpit and `virsh console vmname` connect to the first console.

`virsh console vmname --device console1` connects to the second console. It would be nice if there was a menu that allowed me to pick the second console in `cockpit-machines` too.

**Comment by KKoukiou** [comment]
@yrro I am on the way to implement a solution for that, but OOI what's the usecase of that, having multiple PTY consoles per VM?

**Comment by yrro** [comment]
It's not exactly a vital enhancement, but I find screen updates on the virtio-serial port are a bit less laggy.

But GRUB and other bootloaders can't use virtio-serial ports, so I ended up configuring an emulated serial console for disaster recovery, and a virtio-serial port for 'normal' use.

**Comment by KKoukiou** [comment]
@yrro for your interest this feature request has been implemented and released in cockpit-machines 256 https://cockpit-project.org/blog/cockpit-257.html
