### ISSUE TITLE
Mouse clicks does not work

### ISSUE THREAD

**Issue by brunomgrocha** [cockpit-project/cockpit-machines#29]
Hi,

I'm using cockpit with my KVM server, but since last update i can´t install anything using the web console because my clicks on the mouse doesn't reflect on the screen. Do you know how to fix this?
Thank you

**Comment by KKoukiou** [comment]
Hi @brunomgrocha you seem to be  facing this issue, https://bugzilla.redhat.com/show_bug.cgi?id=1913548 

Try to expand the Vm's console which will open it in a new window.

**Comment by brunomgrocha** [comment]
> Hi @brunomgrocha you seem to be facing this issue, https://bugzilla.redhat.com/show_bug.cgi?id=1913548
> 
> Try to expand the Vm's console which will open it in a new window.

Hi 
I can only expand in the same windows, can't expand to a new windows. 
Can you please show me how to do that?
thank you

**Comment by KKoukiou** [comment]
@brunomgrocha Which version of cockpit-machines are you using? 
You need at least cockpit-machines-231 for the console expand feature. See second screenshot in https://cockpit-project.org/blog/cockpit-231.html

**Comment by brunomgrocha** [comment]
> @brunomgrocha Which version of cockpit-machines are you using?
> You need at least cockpit-machines-231 for the console expand feature. See second screenshot in https://cockpit-project.org/blog/cockpit-231.html

Hi, I'm using version 237

**Comment by brunomgrocha** [comment]
> > @brunomgrocha Which version of cockpit-machines are you using?
> > You need at least cockpit-machines-231 for the console expand feature. See second screenshot in https://cockpit-project.org/blog/cockpit-231.html
> 
> Hi, I'm using version 237

If you want i can upload a screenshot or a small movie of the issue.

**Comment by KKoukiou** [comment]
@brunomgrocha Yes that would be helpful :) any of the two, maybe I misunderstand the issue you have.

**Comment by KKoukiou** [comment]
This is probably the same issue as discussed here https://bugzilla.redhat.com/show_bug.cgi?id=1913548

**Comment by 1ras** [comment]
Just to note, this also occurs in expanded view, depending on guest resolution and browser window size (whenever scaling takes place).

**Comment by garrett** [comment]
Yes, the VNC library we use doesn't map mouse clicks 1:1 when the virtual display of the machine is larger than the region it is in. (In other words, if it is scaled.)

The only things you can do right now are:

- Make sure the resolution of the VM is smaller than the expanded version of the screen.
- Use an external SPICE or VNC server 

...until the VNC library is fixed or we find a workaround to implement in Cockpit.

If you are in expanded mode and it doesn't map the cursor as you expect, then you need to resize your browser to be larger or reduce the resolution of your VM. Apologies.
 
I do have some redesigns of the console area (which aren't specifically about this bug, but would improve it overall); hopefully we can prioritize it soon and possibly find a fix along the way.
