### ISSUE TITLE
Can't Reduce VM Ram Below 2GiB

### ISSUE THREAD

**Issue by stanleyshly** [cockpit-project/cockpit-machines#308]
I can't seem to create a VM with RAM size below 2GiB or 2048Mib.
![image](https://user-images.githubusercontent.com/37353586/128423123-88849e4e-0a79-40c3-8376-4a958fc55033.png)
In Virsh-manager, the default one in ubuntu, I can set the ram as low as I want, and Ubuntu Focal Server has a minimum ram requirment of 512 Mib, so I can't seem to find a reason why I can't lower the ram allocation any more.
Is this capped manually, and if so, is there any way to change this to allow for creation of VMs with less memory?

**Comment by martinpitt** [comment]
AFAIR we made the osinfo limits a recommendation/warning only for storage size. We definitively discussed that for memory as well, but I can't remember the outcome any more. @KKoukiou, do you?

**Comment by martinpitt** [comment]
@stanleyshly : Which cockpit-machines version are you using? On the current one (249) this works fine, you just get a warning:

![image](https://user-images.githubusercontent.com/200109/128464966-f0dfab2b-8e3c-4471-a893-e13299a38341.png)

**Comment by martinpitt** [comment]
Right, your version must be pretty old -- can you please try the current versions from Ubuntu backports?

**Comment by stanleyshly** [comment]
Alright, will do, I think I just installed with sudo apt-get install cockpit, so I need to update quite a bit.

**Comment by KKoukiou** [comment]
This was fixed with https://github.com/cockpit-project/cockpit/commit/23bc0d997119ff21cf968f0ed4d2c5deea0b39c6 thus the fix is present since cockpit-machines 240
