### ISSUE TITLE
Fedora 34 and CentOS 8 stream cloud image booting fails

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit-machines#309]
cockpit-machines 249

For investigating a [recent downstream bug](https://bugzilla.redhat.com/show_bug.cgi?id=1990003), I tried to boot a cloud image. Specifically Fedora 34:

    curl -L -o /var/tmp/f34.qcow2 https://download.fedoraproject.org/pub/fedora/linux/releases/34/Cloud/x86_64/images/Fedora-Cloud-Base-34-1.2.x86_64.qcow2

I don't actually care about creating a new volume, it'd be just fine to boot the cloud qcow as-is. But it seems I have to create or pick an existing one, so I went with the "create new" default:

![image](https://user-images.githubusercontent.com/200109/128465929-cff674de-55ae-406d-a11f-9ba3633553ec.png)

But this fails to boot:

![image](https://user-images.githubusercontent.com/200109/128466025-e2ae4398-1302-421e-b120-e306f91a8ade.png)

Maybe I am doing something wrong, but to me this naïvely appears to be *the* way to boot a cloud image? "Import VM" sounds plausible as well, but that dialog does not offer cloud-init parameters.

**Comment by martinpitt** [comment]
I downgraded to 248:

    dnf install https://kojipkgs.fedoraproject.org//packages/cockpit-machines/248/1.fc34/noarch/cockpit-machines-248-1.fc34.noarch.rpm

and I get the same result, so it's not just a regression from the Python rewrite.

I tried this again with the current GenericCloud CentOS 8 image from https://cloud.centos.org/centos/8-stream/x86_64/images/ . This seemed marginally better in the sense that it at least seems to know about "grub", so it's not entirely blank:

![image](https://user-images.githubusercontent.com/200109/128466743-c7e38fc0-6c16-4b6e-a87d-ea80cf2c0861.png)

and now I see that the image is not actually empty, it's an overlay:

```
# file /var/lib/libvirt/images/t1.qcow2 
/var/lib/libvirt/images/t1.qcow2: QEMU QCOW2 Image (v3), has backing file (path /var/tmp/CentOS-Stream-GenericCloud-8-20210603.0.x86_64.qcow2), 1073741824 bytes
```

So what are we doing wrong here? Both of these cloud images boot just fine directly with QEMU.

**Comment by KKoukiou** [comment]
@martinpitt you just need to use the original backing file, aka  /var/tmp/CentOS-Stream-GenericCloud-8-20210603.0.x86_64.qcow2 and not the overlay you created manually. When doing so a new image overlay will be created for you instead.

Importing directly a qcow2 and passing cloud init metadata to it is not implemented on our side/

**Comment by martinpitt** [comment]
@KKoukiou : I did not create any manual overlay. I downloaded the /var/tmp/CentOS-Stream-GenericCloud-8-20210603.0.x86_64.qcow2 image, and then the only thing I did was to use the "Create VM" dialog as in  my screenshot. Supposedly it's virt-install which creates the /var/lib/libvirt/images/t1.qcow2 overlay?

> Importing directly a qcow2 and passing cloud init metadata to it is not implemented on our side/

Oh, hmm -- but then when *does* the cloud-init bit work? Aside from public cloud specific formats like AMI, pretty well *all* the distros offer qcow2 cloud images for local running (at least Fedora, RHEL, Debian, and Ubuntu do).

**Comment by martinpitt** [comment]
I tried this:
```
qemu-img create -f qcow2 ~/tmp/libvirt-images.qcow2 40G
bots/vm-run -M 4096 -S ~/tmp/libvirt-images.qcow2 fedora-34
```
and inside:
```
mkfs -t xfs /dev/sda
mount /dev/sda /var/lib/libvirt/images/
restorecon /var/lib/libvirt/images/
```

With that I can indeed successfully create a cloud image. With just 1 GiB storage it fails. So I suppose "not a bug"?
