### ISSUE TITLE
The demand to create a virtual machine and turn on VT

### ISSUE THREAD

**Issue by Adsryen** [cockpit-project/cockpit-machines#310]
The creation of the virtual machine, installed with WIN10's system, but need to turn on VT before you can use the Android simulator. VT has been enabled in the host, but the BIOS of the virtual machine cannot be entered on the virtual system, so it is impossible to open VT manually. I hope to enable visual VT control in cockpit! 
Hope to adopt it!

**Comment by Adsryen** [comment]
The cpu on the host supports enabling VT. It is hoped that the virtual virtual machine can also enable VT separately.

**Comment by KKoukiou** [comment]
@Adsryen we need a clarification on this enhancement request. Is this about enabling nested virtualization? https://docs.fedoraproject.org/en-US/quick-docs/using-nested-virtualization-in-kvm/#_enabling_nested_virtualization

If so you can already choose CPU mode -> host-passthrough from the c-machines UI.
