### ISSUE TITLE
Dependencies seem to use LGPL-3.0+

### ISSUE THREAD

**Issue by AdamMajer** [cockpit-project/cockpit-machines#311]
Cockpit version: 238.1

From the dependencies,

```
    "@patternfly/react-console": {
      "version": "1.10.46",
      "resolved": "https://registry.npmjs.org/@patternfly/react-console/-/react-console-1.10.46.tgz",
      "integrity": "sha512-uk84hxQ1OjfJwctikPX/jfYxVLHG6pqA+EH7l2BcDDEDqfm0yBqa859Klg6z2wxRt30erGy0ag4tHOQIx2MymA==",
      "requires": {
        "@novnc/novnc": "^1.0.0",
        "@spice-project/spice-html5": "^0.2.1",
```

The spice-html5 is licensed under LGPL-3.0+. Does this mean that Cockpit should be licensed under LGPL-3.0+ instead now as the spice-project is incorporated in the generated files?

**Comment by martinpitt** [comment]
I reviewed all licenses of all our node_modules, filtering out the ones which have no copyleft:
```
❱❱❱ grep '"license":' node_modules/*/package.json node_modules/*/*/package.json | grep -Ev 'MIT|BSD|ISC|MPL|Artistic|Apache'
node_modules/caniuse-lite/package.json:  "license": "CC-BY-4.0",
node_modules/deep-is/package.json:  "license": {
node_modules/language-subtag-registry/package.json:  "license": "ODC-By-1.0",
node_modules/mdn-data/package.json:  "license": "CC0-1.0",
node_modules/po2json/package.json:  "license": "LGPL-2.0-or-later",
node_modules/spdx-exceptions/package.json:  "license": "CC-BY-3.0",
node_modules/spdx-license-ids/package.json:  "license": "CC0-1.0",
node_modules/@spice-project/spice-html5/package.json:  "license": "LGPL-3.0-or-later",
```
Most of these are build time devDependencies only, which don't apply to the shipped code. Terser's dist/index.js.LICENSE.txt.gz output only shows MIT, but I think it might miss some bits. So indeed the only possibly problematic one from above is spice-html5. cockpit-machines does not use this directly, and indeed none of its code actually makes it into cockpit-machine's webpack. I checked quite a few of its files, in particular string constants (which can't be minimized), and several identifiers (which stay as-is in my development build without minimization).

So I think at least right now there is nothing wrong with the license. There is nothing in our build process which actually enforces this, though.
