### ISSUE TITLE
[Request/Question] How to just show Cockpit-machines pages when entering Cockpit, nothing else

### ISSUE THREAD

**Issue by q2dg** [cockpit-project/cockpit-machines#325]
Hello. I want to use Cockpit-machines but I don't want to use any of the other funcionality Cockpit provides: nor Storage nor System nor anything: just Cockpit-machines. So I have two questions that maybe you find useful to document in order to get a more streamlined experience to just manage VMs in substitution of virt-manager or similar:

-Which Cockpit packages (like "cockpit-storaged", "cockpit-packagekit"...) could be safe to remove from my system (I'm using Fedora)? 
-Is there some trick to hide lateral menu (because it's not useful yet) and to redirect Cockpit main page to Cockpit-machines' one?

Thanks a lot and sorry if this kind of question is not suitable for this place, I understand.

**Comment by marusak** [comment]
> Which Cockpit packages (like "cockpit-storaged", "cockpit-packagekit"...) could be safe to remove from my system (I'm using Fedora)?

All of them. If you are running cockpit on different machine only `c-machines` and `c-bridge` is needed on the remote machine. If you want to run it locally you also need `cockpit-ws` and `cockpit-system`. That also ships a few basic pages as well though.

> Is there some trick to hide lateral menu (because it's not useful yet) and to redirect Cockpit main page to Cockpit-machines' one?

Unfortunately not.

**Comment by q2dg** [comment]
Thanks a lot for your kind answer.
I'll close this "issue", then.
Thanks!
