### ISSUE TITLE
machines: Removing shared directories doesn't remove <memoryBacking> from domain XML

### ISSUE THREAD

**Issue by yunmingyang** [cockpit-project/cockpit-machines#342]
Versions:
cockpit-250-1.fc34.x86_64
cockpit-machines-250-1.fc34.noarch
libvirt-dbus-1.4.0-3.fc34.x86_64

Steps:
1. Prepare a shutoff VM,
2. Create a shared directory for the VM
3. Click "Remove" button of the shared directory created in step 1
4. Check the VM XML, and there is \<memoryBacking\> left
5. Re-click "Add shared directory", and extend additional options, "Memory backing" will disappear.

**Comment by KKoukiou** [comment]
I am on the fence here. When adding shared filesystems we need to ensure that there is memory backing configured. Therefore we show the field in the dialog if memoryBacking is not already present in the XML.

When removing filesystem elements from the XML, we could theoretically only remove the memoryBacking when the last filesystem present is being removed.

However, we can't really know if that memoryBacking element was added by us (when adding filesystems), or was present in the XML before. 

For this reason I believe we should not remove this.

@skobyda any objection on this?

**Comment by KKoukiou** [comment]
As of my comment above, and since there was not any further bug report against this behavior, I will consider this as expected.
