### ISSUE TITLE
machines: There should be no "enable/disable" in xattr text 

### ISSUE THREAD

**Issue by yunmingyang** [cockpit-project/cockpit-machines#347]
Version: 
cockpit-250-1.fc34.x86_64
cockpit-machines-250-1.fc34.noarch
libvirt-dbus-1.4.0-3.fc34.x86_64

Steps:
1. Prepare a shutoff VM
2. Enter the VM detail page
3. Click "Add shared directory", then click "Extend additional options"
4. Check the text of "Extended attributes", if checking the checkbox of "Extended attributes", I think it means enable "extended attributes (xattr) on files and directories". So it is a little duplicate to add "enable/disable" in "Enable/disable extended attributes (xattr) on files and directories"

**Comment by KKoukiou** [comment]
We could replace this with a PF4 switch with:
* label = "Extended attributes  are enabled"
* labelOff = "Extended attributes are disabled"
