### ISSUE TITLE
'Ipv4 network' field is misleading in virtual networks

### ISSUE THREAD

**Issue by NovaDecker** [cockpit-project/cockpit-machines#36]
In the "Virtual Machine" -> "Virtual Network" -> "Create virtual network", it was asking me for:
"Ipv4 network:", this should be changed to "Ipv4 address", as i did write xx.xx.xx.0 there, and was struggling in many days to figure why the VMs did not have network.
Based on how this is written and the rest of fields, it is easy to think it should be an address like 192.168.1.0.
So I just suggest to change that field to be more clearly written.

**Comment by skobyda** [comment]
So In the end I went with other solution that the one suggested by @KKoukiou discussed above. I think it's better to just change the input field name and add some additional checks so user doesn't input network identifier as address as was the case with @NovaDecker  which lead their virtual network not having connectivity. 
See my reasoning: in https://github.com/cockpit-project/cockpit-machines/pull/78
