### ISSUE TITLE
Wrong memory limit in create VM when libvirt is started for fist time via cockpit in a fresh install

### ISSUE THREAD

**Issue by lzap** [cockpit-project/cockpit-machines#37]
Cockpit version: cockpit-240-1.fc33.x86_64
OS: F33 with latest updates

Hey guys,

I just installed completely fresh F33, updated, rebooted, enabled Cockpit and when creating new VM the form does not allow me to put more than 1 GiB of memory while my host has 32 GB of RAM.

I have found this: I started libvirt from cockpit itself. Just to experience how it would be to install and manage services through cockpit, it was nice sure, but it looks like when the libvirt daemon is started through cockpit, some kind of maximum memory limit is applied (by systemd or namespaces?).

Anyway, workaround for the problem is to restart the libvirtd from a terminal and then it works.

Cheers!

**Comment by KKoukiou** [comment]
@lzap any update here?

**Comment by lzap** [comment]
Apologies my GH INBOX went insane, but I am good now:

```
# LC_ALL=C virsh nodeinfo
CPU model:           x86_64
CPU(s):              4
CPU frequency:       3000 MHz
CPU socket(s):       1
Core(s) per socket:  2
Thread(s) per core:  2
NUMA cell(s):        1
Memory size:         32794044 KiB
```

This is an Intel NUC 8th gen with 32 GB RAM, I would put more if I could but that is the maximum. Oh wait, you want me to start libvirtd via cockpit I guess. Yeah.

Hmm that is weird, I stopped and started libvirt from cockpit and I still see 32 GB via that command. And I do see "Up to 31 GiB available" now. I swear when this was completely clean installation and I started libvirt for the first time via cockpit, I could only see 1 GiB.

So I am unable to reproduce on a system where libvirt was already started via a terminal. I would need a fresh installation, unfortunately I cannot reinstall now and to test this bare-metal is very likely needed (can this be reproduced in nested KVM I am not sure).

**Comment by KKoukiou** [comment]
@lzap I will try to reproduce in a f33 VM.

**Comment by lzap** [comment]
Thanks, I mean, not a huge bug and probably quite edge case. I no longer can reproduce it too, so feel free to close at any point. Cheers.

**Comment by KKoukiou** [comment]
Possibly same as this bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1974223
