### ISSUE TITLE
Installation source in the 'Import VM' dialog should be renamed

### ISSUE THREAD

**Issue by lzap** [cockpit-project/cockpit-machines#38]
Hello,

I have an existing LVM volume group full of VMs and I reinstalled my OS and started using cockpit to manage those. However I am not able to create VMs as the selection of options is the following:

* Download OS
* Cloud-base image
* Local installation
* URL
* PXE

Neither of these options work for me, there is no "installation source" I want to use, my image already is installed.

I am leaving this here as a "nice to have" feature some day. Great job guys, love Cockpit from the day one! :-)

**Comment by KKoukiou** [comment]
As Martin mentioned above, the functionality is not missing, just not in the dialog you checked. If we misunderstood the issue feel free to reopen.

**Comment by lzap** [comment]
I am sorry for the delay, well, I am still confused.

The Import VM page indeed does exist and I have missed it, however it wants me to input full path to an "Installation source". Not sure what that is, I suppose this is actually path to an existing image. Also, in my case this would be an LVM logical volume.

Anyway, after I entered `/dev/mapper/volume` it worked. I think "Installation source" is a bit misleading here. Overall, I am good now, thanks.

**Comment by KKoukiou** [comment]
@lzap you re right, the wording is wrong, there is not installation going on when you import an image so this needs to be changed. Re-opening the issue.

**Comment by lzap** [comment]
Thank you, for better reading experience I took the opportunity to file a new issue and I am closing this one:

https://github.com/cockpit-project/cockpit-machines/issues/107
