### ISSUE TITLE
Support for LCX/LXD containers

### ISSUE THREAD

**Issue by lowski** [cockpit-project/cockpit-machines#385]
Hey,
Does `cockpit-machines` plugin support creating virtual machines using lxc/lxd containers? If so, do I need to install any packages to make the option available?

Thank you in advance for answering my question.

**Comment by marusak** [comment]
https://github.com/cockpit-project/cockpit/issues/8215

**Comment by KKoukiou** [comment]
Hey @lowski , there is currently no support for it and there are no plans from our team directly to support such this feature. The cockpit-machines plugin is developed with QEMU VMs in mind.

If someone would decide to write their own Cockpit plugin for LXC containers using the libivirt APIs - it would make a lot of sense to have cockpit-machines codebase as a starting point. Of course I would also be willing to help with reviews etc.

So short story is, this is too much of an effort for our team to invest in, closing this issue as WONTFIX. (Sorry)

**Comment by lowski** [comment]
Thank you for all the details!

**Comment by aliencrash** [comment]
Maybe adding directly to cockpit-machines?
