### ISSUE TITLE
Machines: It should stay on the vm details page after changing the name

### ISSUE THREAD

**Issue by cxhlunar** [cockpit-project/cockpit-machines#396]
Package:
cockpit-machines-252-1.el9_b.noarch

Steps:
1. Prepare a shutdown VM:cirros-old, enter vm details page
2. Click Rename and change to : cirros-new
There will be error:
_VM cirros-old does not exist on system connection_
And you have to enter VMs list to enter the vm details page again.

Expected result:
It should stay on the vm details page with the new name changed (Suggested), or at least can return to the VMs list page.

**Comment by KKoukiou** [comment]
Thanks for catching this. How embarrassing. I also tested it by doing the operation from the main page!

**Comment by cxhlunar** [comment]
Thanks, it seems ok now , but I saw there is still a page saying "VM cirros-old does not exist on system connection"  flash (I mean it appears like less than 1 second, then come back to the correct page.) 
Is that ok or we can still improve a bit? @KKoukiou
