### ISSUE TITLE
lvcreate fails with signature detection

### ISSUE THREAD

**Issue by lzap** [cockpit-project/cockpit-machines#408]
Hey,

probably some leftover data from my previous LVM volume caused this error:

```
# /usr/sbin/lvcreate --name stream8 -L 9437184K vg_virt
WARNING: dos signature detected on /dev/vg_virt/stream8 at offset 510. Wipe it? [y/n]: y
  Wiping dos signature on /dev/vg_virt/stream8.
  Logical volume "stream8" created.
```

This is a harmless thing which can be workarounded by passing `-y` (yes) option, however, cockpit does appear to use libvirt API. I am not sure if this isn't bug of libvirt.

Here is the error I see in the UI:

![Snímek obrazovky 2021-10-04 v 9 14 59](https://user-images.githubusercontent.com/49752/135808817-0ade0e87-dc63-4a22-812f-694c1911c596.png)

**Comment by marusak** [comment]
There is no API for this. It needs to be flagged against libvirt first. See https://libvirt.org/html/libvirt-libvirt-storage.html#virStorageVolCreateFlags
