### ISSUE TITLE
Allow adding authorized SSH keys when using cloud base images

### ISSUE THREAD

**Issue by currybullen** [cockpit-project/cockpit-machines#431]
Would it be possible to add the option to include one or more authorized SSH keys for the non-root user when creating a VM using the "Cloud base image" method? This would enable the user to SSH to the VM immediately after creation using pubkey authentication.

This could be as simple as adding another input field below the "User password" field: "Authorized SSH keys" where zero or more public keys can be supplied.

![image](https://user-images.githubusercontent.com/8695615/137801117-8aa6f897-facc-40db-89f9-e365ac4a9c57.png)

The authorized key(s) could then be passed along with the rest of the user data to `virt-install` using the `ssh_authorized_keys` field: https://cloudinit.readthedocs.io/en/latest/topics/examples.html#configure-instances-ssh-keys.

Another option I've been thinking about is if it would be possible to simply allow the user to supply their own cloud-init user data file, as it would provide the user a high degree of customization at their fingertips. The scope of such a solution would of course however be a bit larger.

**Comment by chrisweeksnz** [comment]
Adding the ability for users to supply their own cloud-init user data would also solve the problem of Fedora CoreOS not getting configured using a "Cloud based image'. Currently the VM gets deployed correctly, but as Fedora CoreOS requires an ignition file to be provided during cloud-init, the deployed host is unusable when ticking "Set cloud init parameters" and filling in details.

**Comment by garrett** [comment]
(@skobyda pinged me about this in the morning, so I'm replying here with my thoughts on it for now.)

I think it's a great idea to add this. However, I also think the create VM dialog is quite large already so we can't just stuff these features into our current design. But we could readjust our dialog to make it more similar to [Cockpit-Podman's new container dialog](https://cockpit-project.org/blog/cockpit-257.html#podman-new-create-container-workflow) so we could have optional tabs for things like this.

The interface for Podman looks like these mockups:

![image](https://user-images.githubusercontent.com/10246/142425066-f6b9e47a-e871-442b-9fde-3d8d85b73183.png)

![image](https://user-images.githubusercontent.com/10246/142425133-bdab0f71-395c-448e-b77c-e87550c4f4e5.png)

And actual screenshots (from the blog post above):

![image](https://user-images.githubusercontent.com/10246/142425199-30f4c0b9-cac5-42c9-955c-bf1e6f6eb007.png)

![image](https://user-images.githubusercontent.com/10246/142425219-5dbf9ed7-3111-4623-a7f9-2ca2abd4374f.png)

(There are a few layout issues at the moment we're working on that happen in some screen sizes. Please overlook those. We're working on it.)

---

Of course, we would need to adapt this concept to the "Create new VM" modal, but the idea would be the same.

We would have basic settings needed for configuring every VM in the first tab and put everything optional, such as adding SSH keys and other cloud init settings in an optional tab.

**Comment by lachlan2k** [comment]
Now that the new "Automation" tab is complete, I'm wondering if there are any plans to get some motion on this? I look forward to hopefully seeing this implemented one day.

**Comment by skobyda** [comment]
> Now that the new "Automation" tab is complete, I'm wondering if there are any plans to get some motion on this? I look forward to hopefully seeing this implemented one day.

Yes, one of the motivations of redesign VM creation and adding that tab was to be able to integrate this functionality better in the UI. I plan to get around to implementing this feature in near future.
