### ISSUE TITLE
Cant see the 'add network interface' button 

### ISSUE THREAD

**Issue by chenoi** [cockpit-project/cockpit-machines#471]
Hi...I'm creating new vm ...everything looks normal...just from the cockpit network interfaces I couldn't see 'Add Network Interface' button. Thus, I could not add more network interface to my vm. Pls help. Thanks

**Comment by KKoukiou** [comment]
@chenoi please provide information for, what version of cockpit-machines are you using? 

I checked the code upstream, so latest release, and there is not condition to hide that button at all.

**Comment by KKoukiou** [comment]
Closing the issue as the reporter did not respond with further information.
