### ISSUE TITLE
create: "Generic Linux" missing from the operating system dropdown

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-machines#500]
The operating system selection should probably include "Generic Linux".

### Discussed in https://github.com/cockpit-project/cockpit-machines/discussions/486

<div type='discussions-op-text'>

<sup>Originally posted by **kinghat** December 15, 2021</sup>
home assistant distribute a qcow2 for people to setup their vm with but they suggest you use "Generic Linux" as the os variant but i dont see how i can do that in cockpit.</div>

**Comment by garrett** [comment]
In libosinfo it's known as "Unknown".

Additionally, when it's not detected in GNOME Boxes (which also uses libosinfo), it shows unknown and allows you to proceed with that selection.

---

Note: When running `osinfo-query os | grep -i unknown`, it returns the following:

Short ID | Name | Version | ID
-- | -- | -- | --
asianux-unknown | Asianux unknown | unknown | http://asianux.com/asianux/unknown
caasp-unknown | SUSE CaaS Platform Unknown | unknown | http://suse.com/caasp/unknown
circle-unknown | Circle Linux Unknown | unknown | http://cclinux.org/circle/unknown
circle8-unknown | Circle Linux 8 Unknown | 8-unknown | http://cclinux.org/circle/8-unknown
circle9-unknown | Circle Linux 9 Unknown | 9-unknown | http://cclinux.org/circle/9-unknown
fedora-unknown | Fedora | unknown | http://fedoraproject.org/fedora/unknown
nixos-unknown | NixOS |   | http://nixos.org/nixos/unknown
opensuse-unknown | openSUSE | unknown | http://opensuse.org/opensuse/unknown
rhel-unknown | Red Hat Enterprise Linux Unknown | unknown | http://redhat.com/rhel/unknown
rhel6-unknown | Red Hat Enterprise Linux 6 Unknown | 6-unknown | http://redhat.com/rhel/6-unknown
rhel7-unknown | Red Hat Enterprise Linux 7 Unknown | 7-unknown | http://redhat.com/rhel/7-unknown
rhel8-unknown | Red Hat Enterprise Linux 8 Unknown | 8-unknown | http://redhat.com/rhel/8-unknown
rhel9-unknown | Red Hat Enterprise Linux 9 Unknown | 9-unknown | http://redhat.com/rhel/9-unknown
rocky-unknown | Rocky Linux Unknown | unknown | http://rockylinux.org/rocky/unknown
rocky8-unknown | Rocky Linux 8 Unknown | 8-unknown | http://rockylinux.org/rocky/8-unknown
rocky9-unknown | Rocky Linux 9 Unknown | 9-unknown | http://rockylinux.org/rocky/9-unknown
scientificlinux7-unknown | Scientific Linux 7 Unknown | 7-unknown | http://scientificlinux.org/scientificlinux/7-unknown
silverblue-unknown | Fedora Silverblue | unknown | http://fedoraproject.org/silverblue/unknown
sle-unknown | SUSE Linux Enterprise Unknown | unknown | http://suse.com/sle/unknown
sle15-unknown | SUSE Linux Enterprise 15 Unknown | 15-unknown | http://suse.com/sle/15-unknown
sled12-unknown | SUSE Linux Enterprise Desktop 12 Unknown | 12-unknown | http://suse.com/sled/12-unknown
sles12-unknown | SUSE Linux Enterprise Server 12 Unknown | 12-unknown | http://suse.com/sles/12-unknown
unknown | Unknown |   | http://libosinfo.org/unknown

**Comment by garrett** [comment]
I'm not suggesting we add all of these. I'm just saying we may want to include just the generic unknown variant.

**Comment by KKoukiou** [comment]
We actually display generic linux.

![Screen Shot 2022-01-04 at 09 44 32](https://user-images.githubusercontent.com/14921356/148032677-a13c9d5b-86b2-493f-956b-86303c4cda69.png)

**Comment by garrett** [comment]
> We actually display generic linux.

Oh! I didn't see it locally on Fedora...

![image](https://user-images.githubusercontent.com/10246/148042818-0d299c5f-41f0-445c-9da5-00b19f1965a3.png)

**Comment by KKoukiou** [comment]
@garrett it's because you have 'Download an Os` as installation method. Of course that option, displays only OSes with installation media URL, which Generic linux does not have.
