### ISSUE TITLE
NIC model name missing in network interface settings dialog

### ISSUE THREAD

**Issue by WuSiYu** [cockpit-project/cockpit-machines#506]
In the "network interface settings" dialog (shows up when creating new network interface or edit the existing network interface of a VM), at the "Model" option, the nic model name (networkModel.name) is missing, it only shows the networkModel.desc.

<img width="876" alt="截屏2022-01-06 下午7 46 43" src="https://user-images.githubusercontent.com/6263652/148379301-3bdc7d99-ec04-450c-958a-40f8eef55ef9.png">

I search the code and found the issue may at [this line](https://github.com/cockpit-project/cockpit-machines/blob/fb0057a06b6c3d10e727d8fd2e536c0dec1e6c6d/src/components/vm/nics/nicBody.jsx#L59), it should using string concat like '+' rather than '&&'.

**Comment by marusak** [comment]
Thank you for the report!
I sent fix in https://github.com/cockpit-project/cockpit-machines/pull/507
