### ISSUE TITLE
Error when deleting VM

### ISSUE THREAD

**Issue by JDHarlequin** [cockpit-project/cockpit-machines#519]
Hi there,
On Debian 11 bullseye when trying to delete VM:

Uncaught TypeError: v.a.all is not a function
    at a (machines.js:362)
    at Object.DELETE_VM (machines.js:362)
    at machines.js:362
    at Object.dispatch (machines.js:362)
    at cs.delete (machines.js:367)
    at Object.s (machines.js:346)
    at p (machines.js:346)
    at machines.js:346
    at g (machines.js:346)
    at ot (machines.js:346)

qcow disk is deleted, VM stays.

Version:
root@#####:/# apt-cache policy cockpit-machines
cockpit-machines:
  Installed Version: 239-1
  Candidate:          239-1
  Version table:
     258-1~bpo11+1 100
        100 http://deb.debian.org/debian bullseye-backports/main amd64 Packages
 *** 239-1 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status

Replication steps:
1) Create VM
2) Switch VM off
3) Delete
4) Oops, check Control+Shift+J

**Comment by skobyda** [comment]
hello @JDHarlequin . Can you describe more how you create VM? What storage do you choose for it?
Ideally, can you share XML of the VM? (you can get it by running command `virsh dumpxml [vm_name]`)

**Comment by KKoukiou** [comment]
This is fixed in cockpit-machines 244.1 See also https://github.com/cockpit-project/cockpit-machines/issues/181
