### ISSUE TITLE
RFE: allow users to increase the vertical length of the expanded console

### ISSUE THREAD

**Issue by cxhlunar** [cockpit-project/cockpit-machines#52]
Page: cockpit-machines-232-1.fc33.noarch

1. Add narrow button since we have Expand button on specific vm console
2. Increase the vertical length of the expanded console to let the whole interface much bigger than now.
![screenshot-10 66 144 41_9090-2020 11 25-13_41_42](https://user-images.githubusercontent.com/12710195/100187877-01c5cb00-2f24-11eb-8a12-95f689a26445.png)

**Comment by KKoukiou** [comment]
This is resolved with latest cockpit-machines I checked.
