### ISSUE TITLE
Create a machine with the default network inactive fails

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit-machines#537]
When the default network is not "active" creating a machine fails, making the user fill in the whole dialog again. If we could check if the default connection exists and is activated before the click on create machine that would resolve this potential annoyance. Alternatively we disallow "start virtual machine after creation" if the default network is not active or does not exist.

![image](https://user-images.githubusercontent.com/67428/150566205-66b3ff65-2d20-4f82-aa52-b737a5882cb4.png)

**Comment by KKoukiou** [comment]
@jelly one comment to this. When we create VMs we don't specify explicitely the network device to be used. We leave it up to virt-install instead. Now quoting man pages:

```
       If --network is omitted a single NIC will be created in the guest. If there is a bridge device in the host with a physical interface attached, that will be used for connectivity. Failing that, the virtual network  called  de‐
       fault will be used. This option can be specified multiple times to setup more than one NIC
```

That means, that a check the the default network is active before creating the dialog, is wrong. We need to check first the condition of the existence of the bridge, and at this point, I think this is already too much to check ahead.

**Comment by KKoukiou** [comment]
This is too complicated and compared to the effort a very small enhancement. The default network should be active by default, and if not the user with activate it the first time it fails in this way and will never get bothered again.
