### ISSUE TITLE
Cockpit displays "Ooops" at the top, when clicking on Virtuel Machines Menu and cockpit-machines not working

### ISSUE THREAD

**Issue by BeFrankly** [cockpit-project/cockpit-machines#558]
Hello everybody,
I am testing Ubuntu Server 20.04 on a small PC that's CPU is capable of Intel Virtualization Technology and so I activated that in BIOS.
Libvirt is working but did not create any VM jet. 
I installed cockpit on the machine and after doing a workaround of a bug that blocked download from internet ([see here](https://github.com/cockpit-project/cockpit/issues/8477#issuecomment-630124971)) I installed cockpit-machines.
But when I open Cockpit and click on "Virtual Machines" Menu, I get a red "Ooops" Message at the top and when I click on in it says: 

> Unexpected error
>
> Cockpit had an unexpected internal error.
>
> You can try restarting Cockpit by pressing refresh in your browser. The javascript console contains details about this error (Ctrl-Shift-J
> in most browsers).

I am a totally newbie with Cockpit and its app and at the moment I think it's not the right Webadmin Interface for a Ubuntu Server 20.04. Can anybody guide me to the logs I have to investigate or the solutions that have to be apply?

**Comment by martinpitt** [comment]
Please check your installed versions of the `cockpit-system` and `cockpit-machines` packages. Chances are that you upgraded cockpit to the current backport, but not cockpit-machines?

**Comment by BeFrankly** [comment]
Dear @martinpitt , thank you very much. That's the solution. How come? I just write it down here for other newbies that have the same problem.
To install cockpit I followed the instruction [here](https://cockpit-project.org/running.html#ubuntu) and installed the base system with 
`. /etc/os-release`
`sudo apt install -t ${VERSION_CODENAME}-backports cockpit`
but cockpit machines just with 
`sudo apt install cockpit-machines`
so versions where 261 for -system and 215 for -machines. Now with
`sudo apt install -t ${VERSION_CODENAME}-backports cockpit-machines` it seams to work. Not created a VM yet but I look forward to it.
To my excuse: I have never worked with backports before ;-)

**Comment by martinpitt** [comment]
Glad to hear! Now you also have much more functionality in Machines :grin: Unfortunately we had to drop some obsolete API in cockpit-bridge at some point, but that old c-machines 215 version was still using it.
