### ISSUE TITLE
Virtual machines does not work for cockpit

### ISSUE THREAD

**Issue by Bazimek** [cockpit-project/cockpit-machines#565]
Ubuntu server 20.04

I installed it via apt install and when I click on virtual machines I just see error on top and nothing is loading.

**Comment by Bazimek** [comment]
Ubuntu 20.04 was installing 215 version. So I manually download the 251 version and it is working.

**Comment by KKoukiou** [comment]
You can use backports, no need to install manually. https://packages.ubuntu.com/focal-backports/cockpit-machines
