### ISSUE TITLE
machines: Address Machines details page changes in follow-ups

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-machines#57]
This is a meta-issue to cover additional issues brought up in cockpit-project/cockpit#14346. Ideally, we should handle these within the next few weeks:

- [ ] disk and networks list need to be adjusted as well (this needs design, it was created at some point but I can't find it)
- [x] autostart to be converted to switch (https://github.com/cockpit-project/cockpit-machines/pull/346)
- [ ] hide usage when machine isn't running (kk: I disagree with it as it will make the cards jump around when the user starts the VM)
- [x] expand icon should be changed to maximize / fit-to-screen icon and have some kind of text
- [x] hide expand arrow on console when machine isn't running (https://github.com/cockpit-project/cockpit-machines/pull/346)
- [x] move main VM list into a card
- [x] change ct-form info into some variant of a [PF4 description list](https://www.patternfly.org/v4/documentation/core/components/descriptionlist) (last usage is bootorder dialog which is about to get completely rewritten https://github.com/cockpit-project/cockpit-machines/pull/191)
- [x] change the title from Networks to Network interfaces
- [x] remove crufty legacy CSS
- [ ] Investigate showing logs per VM (I am not sure about this, we can show /var/log/libvirt/qemu/testvm.log but it's just qemu CLI)
- [x] change button priority — cockpit-project/cockpit#14593, but also consider this across all of Cockpit (this might be better as a Cockpit-wide PR)
- [ ] try to figure out what to do about the text-mode console (VNC mode is fine and scales)

What we cannot quickly address in this next round of changes should be moved out to separate issues.

**Comment by KKoukiou** [comment]
Most of the remaining items are not of high user impact and there are not designs even available. Since this plugin is in maintainance mode I close this as WONTDO.
