### ISSUE TITLE
Can't access Virtual Machines after latest package updates & reboot

### ISSUE THREAD

**Issue by Xenophilicy** [cockpit-project/cockpit-machines#578]
I could be doing something wrong as I'm very new to Cockpit (and libvirt in general), but I can no longer manage my VMs through the cockpit-machines application on Cockpit after installing the latest updates available in "Software Updates". 

Since performing the recommended post-update reboot, I get this message when navigating to the "Virtual Machines":
![image](https://user-images.githubusercontent.com/44390060/154617320-9add9bb9-9026-4806-b874-5d59da4f6915.png)

So, obviously the first thing I did was check the libvirtd service, but it started on boot just fine, and restarting the service (and related ones) had no effect:
![image](https://user-images.githubusercontent.com/44390060/154618616-18bb9059-6b2c-4ed9-a05d-340ea994e217.png)

I am logged into cockpit with the same user that I use for terminal commands, so the permissions are the same that I'm aware of - but I am using "Administrative access" through Cockpit.

I have two VMs that were previously created via Cockpit that do show up as running with `virsh list`:
```bash
 Id   Name      State
-------------------------
 1    utopian   running
 2    cosmic    running
```

I noticed that if I switch to "Limited access", I can at least view the "Virtual Machines" page, but none of my storage pools, networks, or VMs show up: 
![image](https://user-images.githubusercontent.com/44390060/154618394-86637d89-2858-4ec4-b57b-ed45dfdf5380.png)

Please let me know what I'm doing wrong, or if something is broken with my install.

**Comment by KKoukiou** [comment]
In which distro/release are you?
Libvirt has changed to use modular daemons instead of the `libvirtd` you check above in some distros. https://fedoraproject.org/wiki/Changes/LibvirtModularDaemons#Detailed_Description

So check the `virtqemud` and other daemons instead of the mentioned `libvirtd` if these are present.

**Comment by Xenophilicy** [comment]
I'm using Ubuntu Server 20.04. I've used `libvirtd` since the original install of Cockpit and it seemed to work just fine.

**Comment by Xenophilicy** [comment]
Any ideas on how I might fix this? I've reinstalled Cockpit and that still didn't solve my problem, nor did logging into Cockpit with root.

**Comment by KKoukiou** [comment]
Do you see any errors in the browser console? Also can you specify the version of cockpit-machines you 're using?

**Comment by KKoukiou** [comment]
You can also try to install the latest available version from backports. Find instructions [here](https://cockpit-project.org/running).

**Comment by Xenophilicy** [comment]
That's actually how I was installing Cockpit originally - from backports (because it's so easy, no source building or anything). 

I do see some errors in console:
![image](https://user-images.githubusercontent.com/44390060/155528275-3762a16d-3ce1-43a5-ba6d-ea1295df49ed.png)

I don't have any idea what they mean though. 

My Cockpit version is:
`cockpit/focal-backports,now 261-1~bpo20.04.1 all [installed]`

**Comment by KKoukiou** [comment]
If you re comfortable to build from sources, I would suggest this patch. https://github.com/cockpit-project/cockpit-machines/pull/594

Otherwise I am not very optimistic on figuring this out.

**Comment by Xenophilicy** [comment]
Yep, I just built it again and reinstalled, and I think we're getting somewhere. Your patch does reveal a new error in console:
![image](https://user-images.githubusercontent.com/44390060/155725077-8fd589a8-2888-412b-bf63-8910c0b957e7.png)

**Comment by Xenophilicy** [comment]
Okay, upon further searching, I found [this issue](https://github.com/cockpit-project/cockpit/issues/13343). I attempted the steps they mentioned at the issue's closure, but it did not work :(

**Comment by StevenJonSmith** [comment]
I too am seeing issues, after a full server rebuild. I have just reinstalled Ubuntu 20.04.4 and Cockpit, when I go to the Virtual Machines tab I get a blank screen and "Oops!" in the top bar. My web console looks like this:
![Screenshot 2022-03-14 144933](https://user-images.githubusercontent.com/36535597/158197362-dfc8c9b6-ba8d-4bfd-a85e-4b7a35a6710a.png)

Not sure that's really showing much, or even the same issue as others are seeing. But hopefully it helps.

**Comment by KKoukiou** [comment]
> I too am seeing issues, after a full server rebuild. I have just reinstalled Ubuntu 20.04.4 and Cockpit, when I go to the Virtual Machines tab I get a blank screen and "Oops!" in the top bar. My web console looks like this: ![Screenshot 2022-03-14 144933](https://user-images.githubusercontent.com/36535597/158197362-dfc8c9b6-ba8d-4bfd-a85e-4b7a35a6710a.png)
> 
> Not sure that's really showing much, or even the same issue as others are seeing. But hopefully it helps.

@StevenJonSmith your issue is https://github.com/cockpit-project/cockpit-machines/issues/596 - please upgrade. Seems however unrelated with the current issue report here.

**Comment by Xenophilicy** [comment]
Yep. I'm betting that if you installed the patch commit mentioned above,
you'd see the error message that was added (Libvirt/dbus error). I've
looked everywhere for a solution, but if it occurs for you, even after a
full reinstall, I'd say this is a major bug with Cockpit running on 20.04.

**Comment by StevenJonSmith** [comment]
I can confirm completing the install of cockpit-machines from backports resolved my issue.

**Comment by Xenophilicy** [comment]
Turns out, that fixed my issue too. I was installing the `cockpit` package via backports but never thought to install `cockpit-machines` from it as well... 

For anyone in the future needing a quick copy-paste command:
`sudo apt install -y -t ${UBUNTU_CODENAME}-backports cockpit-machines`

Thanks for all your help @KKoukiou
