### ISSUE TITLE
TestMachinesCreate.testCreateThenInstall fails on Testing Farm

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit-machines#581]
This test has [failed](http://artifacts.dev.testing-farm.io/438058c3-e338-4fd9-b055-293f6ac96adc/) for a while on Fedora; currently the test gets skipped on TF.

`TestMachinesCreate.testCreateThenInstall`: That `grep` in the test is meant to confirm the presence of the `METADATA` added by src/scripts/install_machine.py, and indeed it is completely absent. This seems to affect rawhide only, I now saw at least two F36 logs where this test worked. So let's land this one first, to cover F36.

I added a `sit()` in `_tryCreateThenInstall()` right after

    wait(lambda: dialog.name in self.machine.execute("virsh list --persistent"), delay=3)

and another one after the forceOff.

The `virt-install` command never finishes by itself, and the metadata never appears in dumpXml. Only after forceOff'ing the VM these two happen. So this is *not* a race condition (I can sit for quite long on either point) or a behaviour change in virt-install.

This still seems to be the case for F37, i.e. no change. However, it seems `inject_metadata()` from src/scripts/install_machine.py now does not get called any more.

Peeling off the UI, I copied that Python script into the VM, and gave it the JSON parameters that I got from `window.debugging = "machine"`:

    python3 /tmp/install_machine.py '{"connectionName":"system","memorySize":128,"os":"fedora28","profile":"jeos","rootPassword":"","source":"/var/lib/libvirt/novell.iso","sourceType":"file","startVm":false,"storagePool":"NoStorage","storageSize":0.125,"type":"create","unattended":false,"userLogin":"","userPassword":"","vmName":"subVmTestCreate1"}'

On both F35 and F37 that immediately exits, there is no running virt-install, and `virsh dumpxml subVmTestCreate1|head` shows the metadata. So apparently the UI calls this somehow differently, even though I can't see any substantial difference in `src/libvirtApi/domain.js`.

_Originally posted by @martinpitt in https://github.com/cockpit-project/cockpit-machines/pull/580#issuecomment-1046584712_

**Comment by martinpitt** [comment]
@skobyda : Can you please help me with this a bit? Do you know why running install_machine.py directly behaves so dramatically different from how c-machines calls it? (Hanging/blocking virt-install, metadata not written). How do you test/debug changes to the script?

**Comment by martinpitt** [comment]
@KKoukiou Or maybe you have a hint for me?

**Comment by KKoukiou** [comment]
@martinpitt I think there is some  confusion about what this test does, pls let me explain:

The main function of this test is https://github.com/cockpit-project/cockpit-machines/blob/main/test/check-machines-create#L1246

* It creates the VM by just defining without starting the installer, this is running the virt-install script with `startVm: false` as you exactly show it above in your comment. This is not supposed to hand, it just runs virt-install to get the VM XML, then we define the VM and exit.

The VM is in a shutoff state at this point and the metadata should be there.

* Then the test clicks the `Install` button which will call the virt-install script for a second time. This runs the installer, and only when virt-install command returns we add the metadata to the XML. https://github.com/cockpit-project/cockpit-machines/blob/main/src/scripts/install_machine.py#L289

So I think you mixed the two virt-install executions, there is not difference from running the install script from the UI and from the terminal.

**Comment by martinpitt** [comment]
Argh, stupid me -- thanks for PR #583. So this "regresses" because the test gets skipped entirely on F35/F36, and now that Rawhide is F37 it runs again. So it's probably worth checking that on a F35/F36 tmt VM, to make 100% sure it's not a regression, but a different VM setup.

**Comment by martinpitt** [comment]
As this is not new at all, and was just triggered by rawhide now moving from being "36" to "37", I sent PR #585 to adjust the FMF skips. We should still investigate this of course, but it's much less urgent now.
