### ISSUE TITLE
Machines: domain xml metadata lost when create-install are done in two steps

### ISSUE THREAD

**Issue by guerby** [cockpit-project/cockpit-machines#60]
Cockpit version: 221
OS: debian 10 with debian-backports for cockpit (221.1-1~bpo10+1)
Page: 
Machines

When I do on the cokpit web interface:
1/ create a VM without starting it (uncheck the start immediately) in cockpit machines, using URL
https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-10.4.0-amd64-netinst.iso
and OS type "debian 10"
2/ change the network interface (to a bridge vlan10)
3/ then edit it with virsh edit (add metadata and change network interface) 
metadata added:
```
    <ttnn:config xmlns:ttnn="http://tetaneutral.net/">
      <ttnn:network mode="routed">
        <ttnn:tap name="tapvm1">br0 U1 T10</ttnn:tap>
      </ttnn:network>
    </ttnn:config>
```
interface edited to an ethernet tap:
```
    <interface type='ethernet'>
      <mac address='52:54:00:d6:d4:e3'/>
      <target dev='tapvm1'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x01' slot='0x00' function='0x0'/>
    </interface>
```

3/ then click on "install" via cockpit, metadata I added is lost, interface change are overwritten
with virsh dumpxml after clicking on install shows metadata is lost:
```
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://debian.org/debian/10"/>
    </libosinfo:libosinfo>
  </metadata>
```

Attached files :

vm8-before.xml  => when I'm done with create without starting
vm8-edit.xml  => I add metadata and change interface with virsh edit
vm8-install.xml => I clicked on install

**Comment by KKoukiou** [comment]
Starting point: https://github.com/cockpit-project/cockpit-machines/blob/main/src/scripts/install_machine.py#L306
