### ISSUE TITLE
New Install - Virtual Machines page blank and Javascript errors

### ISSUE THREAD

**Issue by CameronMease** [cockpit-project/cockpit-machines#610]
This is a new install of Cockpit on a new Ubuntu Server 20.04.  I installed cockpit-machines using apt.  When I select the virtual machines page, the page is blank and Cockpit displays "oops").  There appear to be some Javascript errors:

<img width="455" alt="image" src="https://user-images.githubusercontent.com/2018275/157294061-cceb08db-a507-4ad2-9918-8a42c886f0b2.png">

**Comment by KKoukiou** [comment]
Please use backports to update to a newer version. You can find instructions here: https://cockpit-project.org/running.html#ubuntu

This is a duplicate of https://github.com/cockpit-project/cockpit-machines/issues/596
