### ISSUE TITLE
Failed to import vm with Alpine Linux 3.14 (ERROR Error: --memory 137.5367431640625: invalid literal for int() with base 10: '137.5367431640625')

### ISSUE THREAD

**Issue by cxhlunar** [cockpit-project/cockpit-machines#612]
Cockpit version: 
cockpit-264-1.fc35.x86_64
cockpit-machines-263-1.fc35.noarch
OS:Fedora35
Page: Vitual Machines
Chrome:Version 99.0.4844.51 (Official Build) (64-bit)

Failed to import vm with Alpine Linux 3.14 (ERROR Error: --memory 137.5367431640625: invalid literal for int() with base 10: '137.5367431640625')

Steps to reproduce
1. Prepare a vm image like cirros
2. Click "Import VM", and input needed field and "Alpine Linux 3.14" as operation system
3. Click Import
Creation of VM cirros failed 
ERROR Error: --memory 137.5367431640625: invalid literal for int() with base 10: '137.5367431640625'

**Comment by garrett** [comment]
So I downloaded Alpine and pointed the import to the iso. (Import is for a disk image, not an ISO, but I digress.) 

The memory was odd. We need to round the value appropriately.


![Screenshot from 2022-03-15 17-08-16](https://user-images.githubusercontent.com/10246/158421595-c8d4fc6d-fb93-478f-bd0b-f80217ea88d1.png)

Same error:

```
ERROR Error: --memory 137.5367431640625: invalid literal for int() with base 10: '137.5367431640625' 
```

When I use the URL of the ISO in the Create new VM dialog, I see the same memory prefilled:

![Screenshot from 2022-03-15 17-11-46](https://user-images.githubusercontent.com/10246/158422238-049b0c97-d860-4a8c-957f-689cc84f04f2.png)

Manually changing the value works:

![Screenshot from 2022-03-15 17-13-06](https://user-images.githubusercontent.com/10246/158422462-07e874c1-46b6-4bce-8b6b-f6863477f58d.png)

(This URL is https://dl-cdn.alpinelinux.org/alpine/v3.15/releases/x86_64/alpine-standard-3.15.0-x86_64.iso, found from the Alpine linux homepage.)

![image](https://user-images.githubusercontent.com/10246/158422585-59f70d4b-a531-4dbe-8904-b6fbd1d3feea.png)
