### ISSUE TITLE
Can't delete dhcp static host entries

### ISSUE THREAD

**Issue by ashrude** [cockpit-project/cockpit-machines#617]
I have an "open" network, and I have static host entries configured for all the machines on the network, but I cant seem to delete them, only add them.

**Comment by skobyda** [comment]
Hello. Thanks for bringing attention to this. It seems that the functionality of removing the HDCP static entries has not yet been implemented. 
From a technical standpoint, however, it seems easy to implement, so I can work on it and get it done soon.
In meantime, you can remove DHCP static host entry by running this command:
`virsh net-update --network [networkName] --command delete --xml "<host mac='[macAddressOfDhcpEntry]' ip='[IpAddressOfDhcpEntry]' />"`

**Comment by skobyda** [comment]
@garrett I'm thinking about adding functionality to delete DHCP static entries to virtual network. Currently it looks like this (you can  only add static entry by clicking 'static entry' button, but there is no functionality to remove it afterwards)
![Screenshot from 2022-03-14 13-36-04](https://user-images.githubusercontent.com/42733240/158173517-74c27ac3-3be8-4101-ba33-aa7334d6627d.png)

The most straighfowards solution I came up with is something like this:
![Screenshot from 2022-03-14 13-34-45](https://user-images.githubusercontent.com/42733240/158173610-fc1f3880-cf48-415e-8800-46734d8b2cc4.png)

WDYT?

**Comment by skobyda** [comment]
Currently, it's not possible to add static host entries for **IPv6 address**, but that functionality can be also implemented in the future.

**Comment by ashrude** [comment]
Thanks! that looks good, though maybe it could be a bit more structured like this?

![image](https://user-images.githubusercontent.com/49853479/158345330-54477b8a-458a-4b45-8e6d-f017dc7e8ed2.png)

I'm probably a bit out of my depth with this one though, I don't know if there are any cockpit design guidelines to be followed.

**Comment by ashrude** [comment]
Something like this would also be cool, though maybe outside the scope of this issue

![cockpit-dhcp-reservation-mockup](https://user-images.githubusercontent.com/49853479/158349104-9fbdb92a-5cd7-48d6-8d59-91b9a7715b72.png)
