### ISSUE TITLE
improve interaction between current and maximum memory sliders in "shut off" VMs

### ISSUE THREAD

**Issue by cxhlunar** [cockpit-project/cockpit-machines#634]
Cockpit version:
cockpit-264-1.fc35.x86_64
cockpit-machines-263-1.fc35.noarch
OS:Fedora35
Page: Vitual Machines
Chrome:Version 99.0.4844.51 (Official Build) (64-bit)

Steps to reproduce
1. Prepare a shutdown vm  like cirros
2. Click Edit after Memory
The minimum value of "current allocation" is offset when "Maximum allocation" setting to the minimum value 
Also a little bit weird to have the slider button showing alone for "current allocation", may be have the min and max all shown the same value and make the button gray seems nice to customer? 
Actually It's not a big problem, and totally ok just leave it like that since it does not affect any fucntion. Just a kindly reminder here.
![Memory](https://user-images.githubusercontent.com/12710195/159647683-c8be1c78-846e-48cd-8d49-3ad1c0f54832.png)

**Comment by garrett** [comment]
Are you asking for the current value to be disabled when the maximium is set to the smallest value? It's still an active value even when it's constrained like this.

As the maximum value constrains how much the current value can have, it might make sense to have it first. I think it's second as the current value is the amount actually given to the VM when it's running, whereas the maximum amount does not have an impact on what the virtual machine sees while the VM is running, just how much libvirt+qemu can adjust the current amount to.

In other words:
- The current amount is how much your VM is using and is adjustable while the virtual machine is running, up to the maximum amount. It's generally used for lowering the amount of memory your guest (VM) has, to reclaim it for the host (the server Cockpit is running on).
- The maximum amount is how much the current can be adjusted to while the machine is running, but the maximum amount can only be adjusted while the virtual machine is not running. 
- Adjusting the current memory on the fly when the machine is running requires that the operating system inside the VM must support "ballooning". Linux does by default, but Windows needs to have support added.

The modal dialog here could definitely explain this better. It's a tricky, advanced concept really.

Here's some more info on how this works:

https://pmhahn.github.io/virtio-balloon/

What _can_ (and should) be done in this case, is we could make the sliders interdependent, where current memory could always show all the available memory and then adjusting it above the maximum memory would increase maximum memory too. This would only work on a VM that's in a shut off state. For running VMs, then the current memory can only be adjusted between the minimum and the maximum, with the maximum fixed.

**Comment by cxhlunar** [comment]
Hi Garrett, thank you for the detailed reply. No I think the logic is ok to me , I just saw the number 128 is offset a bit , and there is no slider on the picture. But it's just a tiny not even a problem I think, because it doest not affect any function . And it's totally ok to close it just as it is now.
