### ISSUE TITLE
Using custom path to add disks lead to misconfiguration of disk formats

### ISSUE THREAD

**Issue by stopendy** [cockpit-project/cockpit-machines#639]
## Summary

When I add a disk which has **qcow2** format to a virtual machine (VM) **using 'Custom path'**, the disk is actually added as a disk with **raw** format.

So I doubt if cockpit-machine detects the disk format correctly.

I'm not sure this is a bug related to cockpit-machine, or other components such as libvirt. However it's good to share this problem to prevent other users from wasting time for troubleshooting.

I'm sorry if this is an expected behavior, or not related to cockpit-machines.

## Steps to reproduce

1. Prepare a qcow2 file for testing.
   * sample commands: `mkdir tmp; touch tmp/a; virt-make-fs -F qcow2 tmp/ tmp.qcow2`

```sh
pwd
# /tmp

mkdir tmp
touch tmp/a
virt-make-fs -F qcow2 tmp/ tmp.qcow2

file tmp.qcow2
# tmp.qcow2: QEMU QCOW2 Image (v3), 288768 bytes
```

2. Create a VM for testing on cockpit-machine UI. Let's say the VM's name is 'test'.
3. Go to the configuration page for the 'test', and click on 'add Disks'.
4. Add disks with following parameters:
   * source: 'Custom path'
   * Custom path: `<path-to-tmp.qcow2>`
   * Device: 'Disk image file'

![add_disks](https://user-images.githubusercontent.com/4696765/160270606-d35ea4fe-de31-4ac9-a4ee-fc657526136e.png)

## Expected result

If I execute `virsh dumpxml test` and verify the hardware configuration, I should be able to see the `tmp.qcow2` with **`type=qcow2`** as below.

```xml
    <disk type='file' device='disk'>

      <!-- here -->
      <driver name='qemu' type='qcow2'/>
      <!-- here -->

      <source file='/tmp/tmp.qcow2'/>
      <target dev='vdd' bus='virtio'/>
      <address type='pci' domain='0x0000' bus='0x0a' slot='0x00' function='0x0'/>
    </disk>
```

## Actual result

`virsh dumpxml test` outputs the following, which shows **`type=raw`**, although actual disk format is `qcow2`.

```xml
    <disk type='file' device='disk'>

      <!-- here -->
      <driver name='qemu' type='raw'/>
      <!-- here -->

      <source file='/tmp/tmp.qcow2'/>
      <target dev='vdd' bus='virtio'/>
      <address type='pci' domain='0x0000' bus='0x0a' slot='0x00' function='0x0'/>
    </disk>
```

## Impact of type misdetection

The added disk might not be even detected by the VM.

## Workaround

In 'Add disks', select the source 'Use existing' instead of 'Custom path'. Storage pool must be created beforehand, so it might lose some convenience. However the disk format is detected without any problem in this method.

## My environment

| item | version |
| --- | --- |
| OS | Fedora35 |
| cockpit | 265 |
| cockpit-machines | 264 |
| libvirt | 7.6.0 |

**Comment by jelly** [comment]
This is still a TODO in the current implementation:

```            
format: this.state.mode !== CUSTOM_PATH ? this.state.format : "raw", // TODO: let user choose format for disks with custom file path
```

**Comment by jelly** [comment]
libvirt-daemon-kvm pulls in libvirt-daemon-driver-qemu which requires qemu-img.
```
on-driver-qemu5-127-0-0-2-2201 ~]# dnf repoquery --requires libvirt-daemon-driver-qemu
Last metadata expiration check: 0:55:29 ago on Mon 28 Mar 2022 12:03:15 PM UTC.
/bin/sh
/usr/bin/qemu-img
```

ubuntu
```
root@ubuntu:~# apt-cache rdepends --installed  qemu-utils
qemu-utils
Reverse Depends:
  qemu-system-common
  qemu-system-x86
  qemu-system-common
  qemu-system-common
  qemu-block-extra
  virtinst
  qemu-system-x86
  qemu-system-common
  qemu-block-extra
```

**Comment by stopendy** [comment]
(I reopened this issue).

> This is still a TODO in the current implementation:
> 
> ```
> format: this.state.mode !== CUSTOM_PATH ? this.state.format : "raw", // TODO: let user choose format for disks with custom file path
> ```

I'll drop a link to that below.  
https://github.com/cockpit-project/cockpit-machines/blob/264/src/components/vm/disks/diskAdd.jsx#L595

> It would be nice to auto-detect the image type using qemu-img info --json $foo.img  
That'd be great. I know `virt-install` command automatically detects the disk format when an existing disk is specified using `--disk` option. And `virt-install` is backed by libvirt, which seems based on `qemu-img`.

So, `qemu-img` should be a valid approach if cockpit-machine tries to detect the disk format using a CLI tool, which also supports structured output such as json.

**Comment by stopendy** [comment]
@jelly 
Thank you very much for #646! I'm looking forward to it being merged.

**Comment by JacksonWrath** [comment]
Giving this a bump; I ran into this today not knowing it doesn't auto-detect. There should really be at least a warning on the Custom Path page that says it's going to use the raw format.

As a side note -- I "imported" a VM using these same disk files and it detected the format without a problem (hence my expectation that using a custom path would do the same). I haven't looked at the code yet, but is there a reason why that same functionality wasn't just replicated?

**Comment by will2022** [comment]
![image](https://user-images.githubusercontent.com/12783306/197753418-b6363112-8908-4e42-be13-6ab2e8d15089.png)
I've had some issues adding extra drives to my VM. The solution I ended up using was using `Custom path`, changing bus to `sata` and `virsh edit <instance name>` to change driver type from `raw` to `qcow2`. I don't know about the first issue and if it's a bug, but without the driver type automatically as `raw` it would've been easier to find a solution.
