### ISSUE TITLE
There will be two network interface attached, when creating a VM with "PXE" and without "immediately start VM"

### ISSUE THREAD

**Issue by yunmingyang** [cockpit-project/cockpit-machines#657]
Description of problem:
If creating a VM with "PXE" and without "immediately start VM", there will be two network interface attached.

Version-Release number of selected components (if applicable):
cockpit-254-1.fc35.x86_64
cockpit-machines-265.6.gae6a8aa8-1.fc34.noarch
libvirt-dbus-1.4.0-4.fc35.x86_64

How reproducible:
100%

Steps to Reproduce:
1 Login cockpit, then enter c-machines page
2 Click "Create VM"
3 Choose "Installation type" to "Network boot(PXE)", uncheck "immediately start VM", then fill the other fields
4 Click "Create", then enter the VM detail page

Actual results:
1 After step 4, there will be two network interface attached

Expected results:
1 After step 4, there should be one network interface attached

Additional info:

**Comment by skobyda** [comment]
I cannot reproduce it issue.

What "Installation source" do you choose for PXE installation? Do you choose some physical network interface, or virtual network? If it's a virtual network, can you post its XML (`virsh net-dumpxml networkName`)

**Comment by yunmingyang** [comment]
@skobyda I choose a physical network interface, but it seems that using virtual network could also reproduce. so I post the XML of the VM using virtual networ

[vm.txt](https://github.com/cockpit-project/cockpit-machines/files/8542466/vm.txt)

**Comment by KKoukiou** [comment]
@yunmingyang I also can't reproduce. Can you please retest with latest cockpit?

**Comment by yunmingyang** [comment]
@KKoukiou  I re-test with cockpit-281-1.fc37.noarch and cockpit-machines-278-1.fc37.noarch, it seems that the issue disappears. So feel free to close this issue. Many thanks.
