### ISSUE TITLE
Machines: look at libvirtd.socket

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit-machines#66]
Starting in Fedora 31, libvirt now ships a libvirtd.socket which can activate libvirtd.service on demand. That means that the Machines page's service detection should start to look at both, and not simply show the "service is not active" empty state pattern if libvirtd.socket is running, but libvirtd.service is not. This is aggravated by the fact that the empty state pattern doesn't go away when libvirtd.service starts.

**Comment by KKoukiou** [comment]
@martinpitt I think the current behavior is actually fine:

*  libvirtd.service -> inactive
* libvirtd.socket -> active 

Loading the page will actually make the API call to fetch the resources, therefore the service will get started by the socket, no empty state seen here all all, just the usual loading spinner.

**Comment by martinpitt** [comment]
Thanks for checking @KKoukiou !
