### ISSUE TITLE
Feature Suggestion - Company Banner

### ISSUE THREAD

**Issue by tgwaste** [cockpit-project/cockpit-machines#674]
It would be cool if you could upload a company banner or logo into this space:
<img width="1124" alt="Screen Shot 2022-04-19 at 10 34 30 AM" src="https://user-images.githubusercontent.com/690918/164062587-633198e8-25cd-4a81-b8d9-5d1dfe327626.png">

**Comment by martinpitt** [comment]
In that space the branding can only control the color. You *can* add an org/company logo on the login page
[branding docs](https://github.com/cockpit-project/cockpit/blob/main/doc/branding.md)

**Comment by KKoukiou** [comment]
This is not relevant feature for this plugin.
If this could ever be supported it could be discussed as part of the shell top navigation component. But as Martin suggests above the branding right now is available just from the login page.

Thanks for taking the time though for checking.
