### ISSUE TITLE
Filter out volume whose type is "dir" when adding disk

### ISSUE THREAD

**Issue by yunmingyang** [cockpit-project/cockpit-machines#686]
Related with https://bugzilla.redhat.com/show_bug.cgi?id=1748900, the BZ is "WONTFIX", but from c-machines side, we could filter out the volume whose type is "dir", for avoiding the error. so submit this issue, and also for tracking purpose

**Comment by KKoukiou** [comment]
This is too specific request and fixing this will introduce technical depth in cockpit-machines that does not belong there.
