### ISSUE TITLE
machines: consoles show/connect to local ports for VMs on remote machines

### ISSUE THREAD

**Issue by catborise** [cockpit-project/cockpit-machines#69]
Cockpit version: 197.3
OS: Oracle Linux 8.1
Page: Machines

When i click the console tab, it show another machines console. I think there are some problems with ports.
---
There are 2 different vm which names are test1, test2. they were created with virt-manager. They are working as expected. 
when i click the vm test1, it shows test2 console. and test2 show test1

![image](https://user-images.githubusercontent.com/1725643/70414968-a11c5480-1a6c-11ea-8574-16da14585a11.png)

**Comment by jonaharagon** [comment]
Came here to open this issue, I'm still seeing this with Cockpit 284.1 on Fedora 37 when managing virtual machines on a remote host.

**Comment by renich** [comment]
> Came here to open this issue, I'm still seeing this with Cockpit 284.1 on Fedora 37 when managing virtual machines on a remote host.

+1 on cs9's cockpit-machines-287-1

**Comment by pv4** [comment]
Hello!

The same on Ubuntu 22.04 LTS packages (version 264-1ubuntu0.22.04.1).

Any progress after 4+ years?

It's not very secure when an administrator opens a terminal to the-one.host and gets a terminal to another.host instead. If he doesn't pay much attention to login prompt inside the terminal area he will execute commands there meant for another server.

**Comment by jelly** [comment]
This issue feels related to https://github.com/cockpit-project/cockpit-machines/commit/6024303e1030fc196ac7ecc86c4a532edd9294e2 does Ubuntu backports have Cockpit-machines >= 303?

**Comment by garrett** [comment]
@pv4:

To add on to what @jelly says; here's a bit more detail about backports: https://cockpit-project.org/running.html#ubuntu

Which would (generically) look like this (which is mentioned in the docs linked above):

```
. /etc/os-release
sudo apt install -t ${VERSION_CODENAME}-backports cockpit-machines
```

Or, for _22.04 specifically_ (which is called 'jammy'), this would also work:

```
sudo apt install -t jammy-backports cockpit cockpit-machines
```

Doing this right now will give you Cockpit-Machines 307 (`307-1~bpo22.04.1`), which is a big upgrade from what Ubuntu 22.04 ships (`265-1`, from more than 2 years ago).

**Comment by pv4** [comment]
Thanks for the replies and for (I hope) the solution!

Unfortunatelly I'm unable to test the suggested solution right now. This issue is on my personal roadmap though so I will definitely do the test one day and reply here whether it worked or not.

**Comment by pv4** [comment]
@jelly @garrett I've just tested the version from ubuntu jammy-backports repo, and that version is not affected by this issue. Thank you very much for the help!

Though, it's strange the issue is still not closed as fixed...

**Comment by martinpitt** [comment]
Thanks for checking @pv4 !
