### ISSUE TITLE
machines: Add support for cloud-init options in create VM dialog

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit-machines#70]
Page: Machines

**As a sysadmin, I want to be able to create VMs from images that doesn't have a hardcoded root password and sign in to those easily**

If I download the RHEL 8.0 qcow2 image from redhat.com, it doesn't come with any account.
This is a pretty common issue, judging from the number of comments in the [solution article on redhat.com](https://access.redhat.com/discussions/664843)
There are a couple of ways to fix it, either do [some dance with guestfs](https://access.redhat.com/discussions/664843), use [virt-customize](https://access.redhat.com/discussions/664843#comment-1104641) or cloud-init.

This also goes for the qcow2 images built with Composer, where you don't hardcode a username and password into the image (and that might not always be desirable).

It would be great if cockpit could pass a cloud-init configuration on the fly. Ideally reusing credentials that's already on the host.

**Comment by KKoukiou** [comment]
This was implemented and released as part of https://cockpit-project.org/blog/cockpit-240.html

**Comment by fvzwieten** [comment]
I know this is closed. However, using this feature with the RHEL 8.4 KVM image results in this when using ssh:
Permission denied (publickey,gssapi-keyex,gssapi-with-mic)

Afaict pw auth is switched off by default in the RHEL KVM images. wouldn't it be better to simply accept cloud-init parameter string?

**Comment by martinpitt** [comment]
@fvzwieten : https://bugzilla.redhat.com/show_bug.cgi?id=1990003 got reported today, presumably triggered by you? So we now have an open bug to track this. Thanks!
