### ISSUE TITLE
[Feature request] Select Firmware while importing a virtual machine

### ISSUE THREAD

**Issue by lateo-net** [cockpit-project/cockpit-machines#702]
### Explain what happens

Working with 2 Fedora 35 machines : 1 laptop, 1 (air gapped) server. 

1. Create a virtual machine on the laptop (specifying : firmware = UEFI)
2. Copy qcow file(s) to server.
3. Use the import function in cockpit, view VM details before first boot : firmware = BIOS, and can't change it back to UEFI
=> Virtual system won't boot.

Did I miss something ?
Are there any config files I can edit to fix this ?
Or do I have to forget about UEFI mode, and restart building my VM from scratch :'( ? 

### Version of Cockpit

included in fedora 35, up to date

### Where is the problem in Cockpit?

Virtual Machines module

### Server operating system

Fedora

### Server operating system version

35

### What browsers are you using?

Firefox

**Comment by jelly** [comment]
A newer cockpit-machines has a `create and edit` option

![image](https://user-images.githubusercontent.com/67428/168103976-41c0969b-498f-4392-9b5b-4b46097c344d.png)

After that you end up with a page where you can change the default firmware:

![image](https://user-images.githubusercontent.com/67428/168104312-1feb7402-9674-4613-b0bf-e216f5ef6c8f.png)

I believe this was introduced in https://github.com/cockpit-project/cockpit-machines/releases/tag/266

**Comment by lateo-net** [comment]
@jelly 
"Create New Virtual Machine". Yes, that's how I created an UEFI VM.
Now try this while *importing* an existing VM. That's my issue.

**Comment by lateo-net** [comment]
Btw, I'm on my way to do it manually, some network issues left, but the `$ sudo virsh dumpfile.xml` works : the VM appears in Cockpit-Machines and I can then manage it (and it's imported as UEFI firmware all right).

**Comment by jelly** [comment]
Aha sorry, the import route indeed has no way to change the firmware even when you import & edit.

**Comment by lateo-net** [comment]
Ok I'm happy with the way the manual import went, and the understanding I got from this may prove useful some day.
I'll rename this ticket as a feature request.

**Comment by skobyda** [comment]
So it seems it's the reason why the ability to change firmware of an already installed VM is disabled is:
If user creates VM thru "Create VM" with one firmware, we want to prevent them from converting already installed VM from one firmware to another, as that is complex process which is not supported by cockpit.

But it seems it doesn't take into account importing VM, when user already imports VM wich a different firmware, and just wants to set a correct one (in this case, no conversion takes place.

So we can theoretically allow what @lateo-net, if we find a way how to prevent user from accidentally converting VM which was already installed with different firmware.
