### ISSUE TITLE
Machines: Improve virtual network layout

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-machines#72]
The layout in https://github.com/cockpit-project/cockpit/pull/11204 can be improved.

Currently, it looks like:

![example VM network layout](https://user-images.githubusercontent.com/42733240/53335873-ef58d080-38fc-11e9-8318-6ea9f7eb4755.png)

There's also a QoS section, like in this old (and problematic, due to vertical stretching) example:

![](https://user-images.githubusercontent.com/42733240/53095656-b0ea9c80-351d-11e9-88f4-22f0a0aa2db2.png)

**Comment by skobyda** [comment]
This is already very old issue. New layout which is already present pretty much fits what was suggested in this issue
![Screenshot from 2021-04-20 13-44-59](https://user-images.githubusercontent.com/42733240/115390621-bd8edc00-a1de-11eb-88f0-ea10d1bdab1c.png)

So I think it's safe to close this

**Comment by garrett** [comment]
The layout still is wonky, but less bad than before, I guess. It kind of misses the points I was making above.
