### ISSUE TITLE
No translation for "User session", "Create and run", "Create and edit", "Automation" and the hint in "Automation" tab

### ISSUE THREAD

**Issue by yunmingyang** [cockpit-project/cockpit-machines#720]
Description of problem:
If selecting "Display language" to "中文（中国）", there will be some options in "Create VM" dialog not translated.

Version-Release number of selected components (if applicable):
libvirt-dbus-1.4.0-4.fc35.x86_64
cockpit-268.1-1.fc35.x86_64
cockpit-machines-267.21.g9e471b20-1.fc34.noarch

How reproducible:
100%

Steps to Reproduce:
1 Login cockpit, with a non-root user. Then go to machine page
2 Select "Display language" to "中文（中国）"
3 Open "Create VM" dialog

Actual results:
1 After step 3, no translation for "User session", "Create and run", "Create and edit", "Automation" and the hint(which is "Enter root and/or user information to enable unattended installation.") in "Automation" tab

Expected results:
1 After step 3, all options should be translate

Additional info:

**Comment by skobyda** [comment]
Those strings you pointed out have a "fuzzy" translation: https://github.com/cockpit-project/cockpit-machines/blob/main/po/zh_CN.po#L219
It means that the translation may not be precise (especially in the context given) and need to be fixed/confirmed at webplate by a Mandarin Chinese speaker. Until that happens, fuzzy strings are generally not translated in the UI.
It's not really a bug, it's a standart process, so I think this issue can be closed
