### ISSUE TITLE
Is it possible to connect to a remote libvirt daemon?

### ISSUE THREAD

**Issue by bLuka** [cockpit-project/cockpit-machines#757]
Hello,
I'm struggling to have cockpit-machines working under a NixOS server.
After having tried different combinations, I'm wondering how I could replace the `qemu:///system` by a remote libvirt daemon, so I could just host Cockpit under a container/VM with supported distro :)

I saw this line, a bit below a `TODO: make this configurable by user`:
https://github.com/cockpit-project/cockpit-machines/blob/9e471b20e25aa97b085578ac134e6aac6199b90b/src/config.js#L31

Is it easy to overwrite?

**Comment by bLuka** [comment]
I see why it is more complicated than just updating `src/config.js` as `qemu:///system` is referenced in a lot of different places.
I wonder if we could easily rely on `/etc/libvirt/libvirt.conf`'s `uri_default` value instead?

**Comment by skobyda** [comment]
Hello. To make sure, you are talking about amending URL to access a remote point `qemu://skobyda@myremoteserver/system` ?

**Comment by bLuka** [comment]
Hello @skobyda,

> Hello. To make sure, you are talking about amending URI to access a remote point. Something like this `qemu://skobyda@myremoteserver/system` ?
Yes exactly.

I tried dumbly cloning the project and doing a search/replace of `qemu:///system` to `qemu+ssh://root@somehost/system` (and same for `qemu:///session`).

Looks like it is able to define and start the VM, but the listing always appear empty, and it looks like the install fails due to Cockpit to being able to fetch the machine state.

May I ask how the VM listing/fetching is done on the project? Isn’t it done using `virsh` CLI?

**Comment by skobyda** [comment]
> May I ask how the VM listing/fetching is done on the project? Isn’t it done using `virsh` CLI?

We use l[ibvirt-dbus](https://github.com/libvirt/libvirt-dbus/tree/master/data). But that doesn't really change anything, since for both libvirt-dbus and virsh we can specify a custom URI.

Btw, have you tried using host switching functionality of Cockpit? On the left panel, you can add a new host, which could be your remote host, and then just switching to it would allow you to manage VM resources there
![Screenshot from 2022-11-13 23-56-46](https://user-images.githubusercontent.com/42733240/201548999-ba0663c7-27df-4889-83e7-aa414e78cd4b.png)

**Comment by bLuka** [comment]
Hi @skobyda, thank you very much for your reply!

> Btw, have you tried using host switching functionality of Cockpit?

Yes, I tried. The issue with it is it needs to connect to a Cockpit daemon, not just a vanilla host, in order to manage everything. And there, the daemon is not available for NixOS (surely due to its kind of invasive behavior compared to NixOS’ readonly nature).

However, I still think Cockpit Machines does great to manage virtual machines and containers, especially for multiple users, where NixOS makes it difficult to do so.

To enable Cockpit Machines itself to manage a remote libvirt instance (with no Cockpit installed in it), I mentionned I tried to connect to a remote host by replacing occurrences of `qemu:///system` to `qemu+ssh://…`. I faced multiple issues where it tried to download/handle files to local storage instead of remote storage, tried to access local dbus, or to access to other local resources (not only filesystem), making it difficult to propose a PR to abstract the communication between Cockpit Machines and the target it manages. I even didn’t succeed to have a dirty workaround by passing through volumes (required directories, dbug sockets, …) to the Cockpit LXC to make it manage its host.

 I’d be really happy to have this ability implemented. I’m not against starting a draft to do so myself, but I’m not a great OSS contributor (yet?) and it’s hard to me to get a grasp of the architecture by myself. Can I ask for assistance? 🙂

**Comment by KKoukiou** [comment]
This usecase is valid but it's will add a lot of complexity and will diverge the architecture of this plugin to a new direction that we dont consider at this point supporting. 

Of course if this request reappears from the community we will consider it.
