### ISSUE TITLE
request: adding categories

### ISSUE THREAD

**Issue by Larse99** [cockpit-project/cockpit-machines#778]
Hey!

I would like to have the ability to have categories within the web interface, where I can filter on each category. I run a couple of "labs" which i want to categorize. At the moment I use prefixes, which get messy.

Something like VMWare Workstation, would be great.

**Comment by jelly** [comment]
I don't see anything in the libvirt API for adding categories to a machine. However it seems libvirt supports [custom metadata](https://libvirt.org/formatdomain.html#general-metadata) as another alternative would be using localstorage but that of course is not persistent.

**Comment by 1ras** [comment]
I was also surprised that libvirt has no concept of grouping, like e.g. [VirtualBox](https://www.virtualbox.org/manual/UserManual.html#gui-vmgroups). I'd like something like that too, but I also think it's a feature for libvirt.

**Comment by KKoukiou** [comment]
We dont want to support something on top of what libvirt supports. This will introduce technical depth to this plugin out of it's initial goal and is something the team does not work to support long term.
