### ISSUE TITLE
Explain "system" vs. "user session"

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-machines#792]
We should probably explain the difference between running as a system VM versus running in a user session, in a popover connected to a (?) icon.

It should probably simply state the benefits and drawbacks of each approach too.

**Comment by garrett** [comment]
(This is the same as https://github.com/cockpit-project/cockpit-podman/issues/1067, but for virtual machines.)

**Comment by GregJohnStewart** [comment]
So have to ask, since the change hasn't made it into the version of Cockpit on Fedora 37 yet.... what's the difference?

(Google search is pretty sparse)

**Comment by marusak** [comment]
You can see how it looks like in https://github.com/cockpit-project/cockpit-machines/pull/875

It was released in version cockpit-machines-281 which got into f-37 stable a day ago, see https://bodhi.fedoraproject.org/updates/FEDORA-2023-49b3964047
