### ISSUE TITLE
Strange message when attempting to remove an ISO when it is in use

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-machines#812]
When I tried to remove an ISO while the disk was in use, I got this confusing error message:

![Screenshot 2022-09-26 at 10-57-14 Virtual machines - garrett@Bolt](https://user-images.githubusercontent.com/10246/192236175-5fa4fd42-0cac-4f94-8e06-0ab8c091cbaf.png)

I think this error message is directly from libvirt, which is why it's so strange. We should rephrase the error to make it more straightforward. It could say something like the disc cannot be ejected as it is in use.

_Originally posted by @garrett in https://github.com/cockpit-project/cockpit/issues/13454#issuecomment-1257728993_

**Comment by shodanshok** [comment]
@garrett Please see https://github.com/cockpit-project/cockpit/issues/13454#issuecomment-1257761674 for the difference between removing a virtual *drive* and ejecting/changing a virtual *cdrom*

**Comment by garrett** [comment]
This issue is specifically for the error message when removing a disc drive that's in use (based on an ISO).

We should make eject the default and move removal to the ... menu.

For adding "Eject", please see https://github.com/cockpit-project/cockpit-machines/issues/814.

**Comment by KKoukiou** [comment]
Fixed by:
commit 6b812e87b85d14d12be880654ef9c6b03ade1699
Author: Simon Kobyda <skobyda@redhat.com>
Date:   Mon Oct 3 14:48:24 2022 +0200

    Implement media ejection from CDROM devices
