### ISSUE TITLE
qcow2 disk wrongly added as raw image

### ISSUE THREAD

**Issue by shodanshok** [cockpit-project/cockpit-machines#826]
When adding an existing qcow2 disk using the "custom path" option, the disk is added to the virtual machine as raw image rather than qcow2. The machine can not boot. This is the resulting xml file:

```
<disk type='file' device='disk'>
  <driver name='qemu' type='raw'/>
  <source file='/var/lib/libvirt/images/zzz.qcow2'/>
  <target dev='vda' bus='virtio'/>
  <address type='pci' domain='0x0000' bus='0x00' slot='0x08' function='0x0'/>
</disk>
```

If adding the very same disk using the "use existing" option, the disk is correctly added as a qcow2 image and the machine can boot correctly.

Adding disk via custom path:
![screenshot](https://user-images.githubusercontent.com/13137622/195153449-d2772157-82d8-4cc1-ae5e-019c4abf8cfc.jpg)

Machine can not boot (and disk size is not recognized):
![screenshot1](https://user-images.githubusercontent.com/13137622/195153485-a6f9039b-8597-499e-8f73-478ea382d2db.jpg)

See also: https://bugzilla.redhat.com/show_bug.cgi?id=2133871

**Comment by jelly** [comment]
For this we have https://github.com/cockpit-project/cockpit-machines/pull/646 which requires some more work.
