### ISSUE TITLE
Get Error from LIBVIRT by creating new VM from ISO

### ISSUE THREAD

**Issue by Sepp1911** [cockpit-project/cockpit-machines#858]
### Explain what happens

1. download any ISO (e.g. Lubuntu & Puppy)
2. check permissions (all users can read & write)
3. enter details & create VM
4. get error 
5. ![LIBVIRT ERROR](https://user-images.githubusercontent.com/118113254/201528186-149906c7-204b-4fce-8474-aa4ac746de28.png)

6. check ISO .. libvirt changed permissions to block all users except libvert
7. see screenshot
8. 
![lubunt iso](https://user-images.githubusercontent.com/118113254/201528230-073b41d9-1443-410a-ac34-02bb2a145fac.png)

9. change permissions on ISO again to all users
10. create again
11. same result
12. try different ISO
13. same result
14. try fixing libvirt
15. try creation again
16. same result

### Version of Cockpit

264-1ubuntu0.22.04.1

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Ubuntu

### Server operating system version

22.04.1 UBUNTU

### What browsers are you using?

Chrome

**Comment by KKoukiou** [comment]
The ISO file has to have the right permissions so the qemu process can read it. What you face is is not a bug in cockpit-machines itself, if you try directly virt-install from CLI you will have the exact same issue.

I see you already checked the ISO file permissions but there can also be a problem with SELinux / Apparmor.

One simple solution is to create a libvirt storage pool and move your ISO there.

**Comment by Sepp1911** [comment]
Thank you very much
Sepp

Thank you

***@***.***
SEPP
JOSEF LUDWIG SCHEMBERA
Owner
[Title: Facebook ***@***.***<https://t.me/dn4uau>BUSINESS[Title: Facebook icon]<https://www.facebook.com/smbtelnet>[Title: LinkedIn - Description: Linkedin icon]<https://www.linkedin.com/in/josef-sepp-schembera/>

Skype : Sepp.Schembera Email: ***@***.******@***.***> Web: www.smbtelnet.com<http://www.smbtelnet.com/>
Mobile: +63 9555441449
Landline: +63270043708
VIBER : 09555441449
WB : https://wa.me/+639555441449

Address:   Unit 10 F Tower 4 San Lorenzo Place Makati Manila Philippines
FACEBOOK PRIVATE https://www.facebook.com/sepp.schembera
FACEBOOK BUSINESS https://www.facebook.com/smbtelnet
WHATSAPP BUSINESS https://wa.me/message/XMFGYCUYK57IK1
LINKED IN https://www.linkedin.com/in/josef-sepp-schembera/


***@***.***
