### ISSUE TITLE
Please use GiB instead of GB to display the configured memory

### ISSUE THREAD

**Issue by 1ras** [cockpit-project/cockpit-machines#869]
It's just a minor thing, but "Memory" is shown in GB:
![screenshot-1669224618](https://user-images.githubusercontent.com/45467075/203612517-3d242253-7546-4056-aa17-393edbbabc9a.png)

Where "Usage" is in GiB:
![screenshot-1669224628](https://user-images.githubusercontent.com/45467075/203612540-a1bd881c-8dd8-4f8d-99a2-92c8a427edf8.png)

And if you click on the edit button to change the memory it's in MiB/GiB:
![screenshot-1669224655](https://user-images.githubusercontent.com/45467075/203612546-8cb50be3-3829-4fde-b900-7a1d6f9669a6.png)

**Comment by 1ras** [comment]
cockpit-machines is version 277

**Comment by KKoukiou** [comment]
@1ras you ;re right, I mischecked. Will take a look today.
