### ISSUE TITLE
How to change the storage of qcow2 VMs?

### ISSUE THREAD

**Issue by maravento** [cockpit-project/cockpit-machines#876]
### Explain what happens

They are currently saved in:
example: `/var/lib/libvirt/images/test.qcow2`

How can I select the path where the VM (qcow2) is going to be stored when creating it? (e.g.: external storage, another partition, etc.)

thanks in advance

### Version of Cockpit

264-1ubuntu0.22.04.1

### Where is the problem in Cockpit?

Storage

### Server operating system

Ubuntu

### Server operating system version

22.04

### What browsers are you using?

Firefox, Chrome

**Comment by KKoukiou** [comment]
You can change the default path for image storage by reconfiguring the `default` storage pool.

In cockpit-machines it;s not possible to edit pools, but you can undefine it and create a new one with the same name. 


The default pool can be seen in the screenshot as follows:

![Screen Shot 2022-12-03 at 11 58 29](https://user-images.githubusercontent.com/14921356/205437491-9178f1fe-2c5e-4a9d-95f5-417c25deafc4.png)

Deactivate and remove without deleting it's content, and then create a new 'dir' Storage pool by using the 'Create new storage pool' dialog in the same subpage.

**Comment by maravento** [comment]
ERROR Cannot access storage file '/home/user/ssd/vm/pool/ubuntu.qcow2' (as uid:64055, gid:993): Permiso denegado Domain installation does not appear to have been successful. If it was, you can restart your domain by running: virsh --connect qemu:///system start ubuntu otherwise, please restart your installation. Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'ubuntu24.04', '--reinstall', 'ubuntu', '--wait', '-1', '--noautoconsole', '--cdrom', '/home/user/ssd/iso/ubuntu-24.04.2-desktop-amd64.iso']' returned non-zero exit status 1.
