### ISSUE TITLE
Use GiB by default when showing VM memory

### ISSUE THREAD

**Issue by shodanshok** [cockpit-project/cockpit-machines#878]
VM Overview shows, and counts, VM memory in GB rather then in GiB. On the other side, the "edit" button specifies memory in MiB/GiB. 

Example:
![Cattura](https://user-images.githubusercontent.com/13137622/205438254-07501345-2fc3-4abb-a353-0e4d135d4415.JPG)

This results in "strange" (ie: non-integer) guest memory size. The proper solution is to show installed memory in power^2 size.

**Comment by KKoukiou** [comment]
Duplicate of https://github.com/cockpit-project/cockpit-machines/issues/869
Fixed in release 279. (This was released 2 days ago)

**Comment by shodanshok** [comment]
I missed it, thanks for the quick fix.
