### ISSUE TITLE
Unsuccessfully run of any SO on cockpit-machines

### ISSUE THREAD

**Issue by guercheLE** [cockpit-project/cockpit-machines#879]
Newbie to qemu/KVM virtualization, so gave cockpit-machines a try, but was never able to run any windows/linux on it.

1) Created or imported Windows or Linux SO
![SCR-20221204-o0s](https://user-images.githubusercontent.com/1792/205513627-df41f291-4d30-43cf-9cfc-d31b08cf6431.png)

2) When run it with firmware set to BIOS (default when imported or created), got the message "No bootable device"
![SCR-20221204-nqx](https://user-images.githubusercontent.com/1792/205513797-d7f31840-c3ce-4322-badc-5df5a1226c52.png)

3) Changed firmware to UEFI, the error message was gone, but SO never started. Progress bar always on, forever.
![SCR-20221204-nrx](https://user-images.githubusercontent.com/1792/205513818-90dd2d55-331e-49eb-b1ac-661861eff78c.png)

4) Even tried changing disk bus to USB and SATA, but to no success.
![SCR-20221204-o1c](https://user-images.githubusercontent.com/1792/205513831-1ac38b48-4d1f-4a34-8494-6a4aa5c7ab12.png)

**Comment by garrett** [comment]
Do you have virtualization turned on in your EFI/BIOS settings? It's often turned off by default and can cause problems when trying to run VMs when it's not enabled.

Why I ask:
- I noticed over the weekend that I actually had this off, which was the default, on my relatively new personal workstation.
- And I remember having to turn this on for one of my laptops (I forget if it was a personal or work one) a few years back.
- And we had an issue opened a couple of weeks ago who had problems with starting their VMs until they realized the problem.

So it's definitely something you should check.

(I'm not sure if it's something we can check in Cockpit... but if so, we should add a check and have a message that virtualization is not enabled and to enable it in EFI settings.)

Please check your computer's settings and let us know if this is the problem for you, or if it's something else.

**Comment by guercheLE** [comment]
Bingo! Man, I am astonished. You are completely right. All virtualization settings were off on BIOS.

Thank you very much. I appreciate it.
