### ISSUE TITLE
Virtual machine search should be case insensitive

### ISSUE THREAD

**Issue by shodanshok** [cockpit-project/cockpit-machines#885]
Virtual machine filter/search should be case insensitive by default - otherwise, one has to try various combination of upper/lower case when searching virtual machines.

For example, I have a virtual machine called "Hubble". However, searching for "hubble" shows no results:
![Cattura](https://user-images.githubusercontent.com/13137622/206841583-4913170a-4297-4f6f-bc5b-2c7011768a8f.JPG)

**Comment by garrett** [comment]
I agree :100:
