### ISSUE TITLE
Libvirtd unattended installation root password is wrong

### ISSUE THREAD

**Issue by NovaDecker** [cockpit-project/cockpit-machines#89]
Hi.
I am going to cockpit -> Virtual Machines -> Create new virtual machine -> Checking "Run unattented installation" -> Setting a root password.
That root password is wrong, and I always have to run this command on host machine:
virt-customize -a /raid5-array/virtual-machines/webserver.qcow2 --root-password password:FooBarPassword

(I have to install libguestfs-tools-c with this command yum install libguestfs-tools-c first, before running virt-customize, and the virtual machine have to be turned off)

**Comment by KKoukiou** [comment]
@NovaDecker thanks for the report. So this not broken on my system at least, can you please give me some more info to identify what breaks this functionality on your system?

So basically I just chose `Download an OS' option and then chose 'Unattended installtion' and set there only root password, foobar.

I clicked 'Create' and then checked what command was generated, in the Terminal I did, `ps aux | grep virt-install`.
The output was containing the following;
```
/usr/bin/virt-install --connect qemu:///system --name test --os-variant fedora33 --memory 3072 --quiet --disk size=10,format=qcow2 --noautoconsole --wait -1 --install os=fedora33 --graphics spice,listen=127.0.0.1 --graphics vnc,listen=127.0.0.1 --unattended profile=jeos,admin-password-file=/tmp/tmp.I0AI0o03M9
```
That last argument is how the root password is passed to virt-install:
```
$ cat /tmp/tmp.I0AI0o03M9 
foobar
```

So far all looked good. I followed the installation the the UI as well, and when I saw the login prompt I entered, root/foobar and i was authenticated as expected.

So I don't see many things that can go wrong here. Do you want you see some major differences between my steps and yours?

**Comment by NovaDecker** [comment]
CentOS 8 installation:
`root      344501  0.8  0.3 583608 102628 ?       Sl   11:19   0:01 /usr/libexec/platform-python /usr/share/virt-manager/virt-install --connect qemu:///system --name test --os-variant centos8 --memory 2048 --quiet --disk size=20,format=qcow2 --noautoconsole --wait -1 --install os=centos8 --graphics spice,listen=127.0.0.1 --graphics vnc,listen=127.0.0.1 --unattended ,admin-password-file=/tmp/tmp.SNUA6pUHeL,user-password-file=/tmp/tmp.CPXyN3NfYn,profile=jeos
`
`cat /tmp/tmp.SNUA6pUHeL
foobar`

Username: root
Password: foobar
Invalid login.


Fedora 35 installation:
`root      360490 16.0  0.3 510276 104512 ?       Sl   11:30   0:01 /usr/libexec/platform-python /usr/share/virt-manager/virt-install --connect qemu:///system --name test2 --os-variant fedora32 --memory 2048 --quiet --disk size=20,format=qcow2 --noautoconsole --wait -1 --install os=fedora32 --graphics spice,listen=127.0.0.1 --graphics vnc,listen=127.0.0.1 --unattended ,admin-password-file=/tmp/tmp.5WnIyPVB8b,user-password-file=/tmp/tmp.yfLSBD0UJU,profile=jeos
`
`cat /tmp/tmp.5WnlyPVB8b
foobar`

Also here incorrect login.
The host machine is CentOS 8, if it should matter.
Very strange issue, if it works for you.

Maybe you could check if the temporary password files got deleted after the installation was done? It does not delete here, the temporary password files are still there.

I also found this in logs:

`
internal error: child reported (status=125): unable to stat: /var/lib/libvirt/boot/virtinst-bksrkd8h-vmlinuz: No such file or directory
`

**Comment by KKoukiou** [comment]
@NovaDecker what version of cockpit-machines are you using? I have recently posted some fixes for these options, contained in release 240. Maybe try upgrading to cockpit-machines-240 as a blind fix. 

Do you also pass user password? I see in the CLI this is also passed, whilst on my system is not when I leave it blank in the UI. In any case, try upgrading, I have high hopes that this was fixed in the meantime.

**Comment by NovaDecker** [comment]
Version 224.2.
I found something.
When I did `cat /tmp/tmp.5WnIyPVB8b` to get admin password value, it says "foobar", right.

I did not set a user password, as i did not have any option to do that in the GUI. I cant see anywhere I can set a user password. But when I did `cat /tmp/tmp.yfLSBD0UJU` to get the user password (which i have not set), it says "undefined". 

And when i now tried
Username: root
Password: undefined
I got logged in.

**Comment by NovaDecker** [comment]
I am not sure how to upgrade to 240, as i do use yum, and it does not say it exist an update.

**Comment by KKoukiou** [comment]
@NovaDecker thanks for confirming, so indeed that was a bug which was fixed in the version i posted above. I had not realized it was so bad actually. :disappointed: 
Regarding the upgrade, it really depends on the distro you use. I guess you use centos, because of them YUM thingy, so unfortunately this does not have the 240 yet. If you 're really into it, you can always build from sources and I can guide you into that.

**Comment by NovaDecker** [comment]
Yes, please. I think I can make a try myself, but I am unsure which tar that is the correct source file:
https://github.com/cockpit-project/cockpit/releases/tag/240
Here it says:
cockpit-240.tar.xz
cockpit-cache-240.tar.xz
Source code (zip)
Source code (tar.gz)

Which one should I choose?

**Comment by NovaDecker** [comment]
I figured that out, i did choose the first one, cockpit-240.tar.xz, but it have dependices that i dont find with yum. So, what's the guide?

**Comment by marusak** [comment]
> I figured that out, i did choose the first one, cockpit-240.tar.xz, but it have dependices that i dont find with yum. So, what's the guide?

What OS are you using in what version?

**Comment by martinpitt** [comment]
@NovaDecker : Note that cockpit-machines was recently split out into this separate project, it's not part of cockpit any more. Try the current [cockpit-machines](https://github.com/cockpit-project/cockpit-machines/releases/tag/242.1) release, that's also much easier to build. In fact, you don't really need to build anything, you can just unpack the tarball and copy its `dist/` directory to ~/.local/share/cockpit/machines or /usr/share/cockpit/machines.

**Comment by NovaDecker** [comment]
> > I figured that out, i did choose the first one, cockpit-240.tar.xz, but it have dependices that i dont find with yum. So, what's the guide?
> 
> What OS are you using in what version?

Latest centos 8 server.

**Comment by martinpitt** [comment]
@NovaDecker : Ah, CentOS 8! If you prefer, you can then also use the Copr: https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/

**Comment by marusak** [comment]
For centos you can use https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/

**Comment by marusak** [comment]
Heh, pitti was faster :)

**Comment by NovaDecker** [comment]
Amazing! Just to show another people how we solved this:
I have CentOS 8 on the host machine.
Remember that I did this via the root user, and not a sudo user. If you do not do this via the root user, then add "sudo" before the commands.

First I did uninstall everything with cockpit (Not necessary, but I did anyway):
`yum remove cockpit*`

Then I did change dir to /etc/yum.repos.d/:
`cd /etc/yum.repos.d`

And downloaded the .repo file, it have to be placed in /etc/yum.repos.d. I found the link to the .repo file from the link from mursak above (https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/) I choosed the first file named Epel for CentOS 8.
`wget https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/repo/epel-8/group_cockpit-cockpit-preview-epel-8.repo`

Then updating the package list and something else, if it was updateable:
`yum update`

If you did have cockpit installed from before, and did not uninstall it, like I did, you then do not need to do anything more.
If you did not have cockpit installed, then install it:
`yum install cockpit`

After this, you have to enable cockpit:
`systemctl enable --now cockpit.socket`

And now, enjoy the fun!
http://your-server-ip:9090
