### ISSUE TITLE
import dialog: Indicate which disk formats are supported inside the UI, using a popover

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-machines#890]
In #883, we had a question where were were asked which disk formats are supported.

We _probably_ should show this inside the UI, likely in a popover, as the list could get long.

Otherwise, it might be a case of trial and error to try different disk formats (and converting to different types can take a while).

**Comment by KKoukiou** [comment]
@garrett when creating a VM always qcow2 is chosen. When creating a new disk, we show a dropdown with the formats we suggest.
If the user has an already existing VM created with some other tool, with some image format we don't expose in these UI options I guess it's something we dont want to analyze in the UI.

**Comment by garrett** [comment]
(Renamed to make it clearer.)

**Comment by marusak** [comment]
As mentioned above the list might be rather long so it must be in popover which is not that useful when looking for it. Libvirt also does not expose which formats it supports. For any normal usecases people will use disks they exported so they should know what they are looking for. It is valid request but very corner case.
