### ISSUE TITLE
Check if machine can run VMs (as some BIOS/EFI settings need to be enabled)

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-machines#891]
We had someone report in #879 that they could not run a VM. We diagnosed the issue as a result of the BIOS/EFI virtualization setting not being enabled.

Many laptops and desktops ship with virtualization off. It's possible some servers could too.

As people do also use Cockpit for staging systems on laptops and desktops — and there's a possibility that some server machines could also ship with this toggle — I think we need to check that a VM can run on the system and show an appropriate error message, with a hint that they might need to reboot into BIOS/EFI and enable virtualization.

I've added a question to the FAQ @ https://github.com/cockpit-project/cockpit-project.github.io/pull/594 — but even when we check in `cockpit-machines`, there will be older versions of Cockpit in use in Long Term Enterprise distros.

Hopefully we can resolve it rather soon for `cockpit-machines`, however.

Without this detection, it looks like `cockpit-machines` does not work, so it's both a bug an enhancement.

**Comment by garrett** [comment]
Since a machine may have multiple VMs set up (due to the toggle changing, which happens during BIOS/EFI updates sometimes, or multiple attempts at installing VMs), I think the right place might be to have a big error at the top of the page (in an alert or banner) and still show the VMs otherwise. It should provide details about how to fix the error (rebooting, hitting a key, changing a value).

There's text in the FAQ that I wrote which could be adapted for this.

**Comment by jelly** [comment]
We can detect this using:

```
[root@fedora-37-127-0-0-2-2201 ~]# lscpu | grep -i virt
Address sizes:                   39 bits physical, 48 bits virtual
Virtualization:                  VT-x
Virtualization type:             full
```

Or `grep -E --color=auto 'vmx|svm|0xc0f' /proc/cpuinfo` Not sure about ARM/s390x though.
