### ISSUE TITLE
VM has issues creating & Memory maxes at 1GB.

### ISSUE THREAD

**Issue by matrix2113** [cockpit-project/cockpit-machines#904]
I'm running the latest version of Cockpit and cockpit-machines with Ubuntu 20.04 LTS. When I try to make a VM, the memory tab is on the opposite side of the slider. Any ideas to fix this?

My hardware is `48x AMD EPYC 7402 24-Core Processor` with 128GB RAM.

Thanks

![image](https://user-images.githubusercontent.com/49132750/210274732-4fb9d190-55ca-457a-a22b-c3a09f186fa5.png)

**Comment by KKoukiou** [comment]
Hi @matrix2113 thanks for the report. Can you show please the output of, ```$virsh nodememstats` and `virsh nodeinfo`?

Looks like detection for the system max memory is wrong on your server.

**Comment by matrix2113** [comment]
Hey, I’m also receiving this error. I can’t find the service but all the libvirtd is running. Any ideas?
![406183D5-C4F5-44EF-8D16-0BD6069B9F64](https://user-images.githubusercontent.com/49132750/210315298-95112942-60f5-47bd-beb3-486d48244039.jpeg)

**Comment by matrix2113** [comment]
This is the output. 

```bash
root@ns1001159:~# virsh nodememstats
total  :            131727280 KiB
free   :            129251992 KiB
buffers:                66756 KiB
cached :               792416 KiB

root@ns1001159:~# virsh nodeinfo
CPU model:           x86_64
CPU(s):              48
CPU frequency:       2647 MHz
CPU socket(s):       1
Core(s) per socket:  24
Thread(s) per core:  2
NUMA cell(s):        1
Memory size:         131727280 KiB```

**Comment by KKoukiou** [comment]
@matrix2113 would you be interested to bring a newer version of cockpit-machines from ubuntu backports? It might solve your issue, and if not I can have easier undertanding what might be the issue.

 20.04 has 215-1 cockpit-machines which is a very old cockpit-machines version. Backports for 20.04 have 263.

https://packages.ubuntu.com/focal-backports/cockpit-machines

**Comment by matrix2113** [comment]
Looks like cockpit machines is already using 263. ```bash
cockpit-machines is already the newest version (263-1~bpo20.04.1).```

My cockpit version is `264-1ubuntu0.22.04.1~bpo20.04.1`. Installed both via backports. I believe (according to their docs).

**Comment by KKoukiou** [comment]
> Hey, I’m also receiving this error. I can’t find the service but all the libvirtd is running. Any ideas? ![406183D5-C4F5-44EF-8D16-0BD6069B9F64](https://user-images.githubusercontent.com/49132750/210315298-95112942-60f5-47bd-beb3-486d48244039.jpeg)

libvirtd is the old deamon. Newer libvirt versions use modular daemons by default. There are named `virtqemud` , `virtstoraged`, ... and so. Can you check these as well?

Btw since you get this error, how do you even manage to bypass it and get to the create-vm-dialog.?

**Comment by matrix2113** [comment]
That screenshot was earlier in the day. I re-formatted the server to install backports.

**Comment by matrix2113** [comment]
Neither of `virtqemud` nor `virtstoraged` is appearing in the services menu. Would a package purge and re-install fix this?

**Comment by KKoukiou** [comment]
> Neither of `virtqemud` nor `virtstoraged` is appearing in the services menu. Would a package purge and re-install fix this?

No , it's fine to use the old ones. It has to do with the libvirt version you 're using. Since updating fixed the Inactive empty page, (I think it was upstream commit <pre>b59da0d7b1d0dedefab7f0d6ab6678aa7547386a</pre> introduced in 252-29-gb59da0d7) let's not debug it further.

The memory issue is still unclear to me. The create vm dialog UI you show in the screenshot is not really aligned with the version you seem to have installed. 
The Ui from the version you claim to use (263) is quite different for the memory configuration. 
![Screen Shot 2023-01-03 at 09 32 22](https://user-images.githubusercontent.com/14921356/210322977-93bdde35-7a81-49b8-83b8-534a36aa3135.png)

**Comment by matrix2113** [comment]
Will double check but it would be best to use cockpit-machines and cockpit
on back ports such as the two versions I linked above?

Thanks

**Comment by KKoukiou** [comment]
> Will double check but it would be best to use cockpit-machines and cockpit on back ports such as the two versions I linked above? Thanks

yes, you will get so latest available features and bug fixes.

**Comment by KKoukiou** [comment]
@matrix2113 did you manage to ensure that you ;re using cockpit-machines from backports? If so can you please recheck the issue and post an up to date screenshot?

**Comment by KKoukiou** [comment]
@matrix2113 please comment to reopen if the issue was not resolved. thanks
