### ISSUE TITLE
Storage pools automatically created

### ISSUE THREAD

**Issue by cobi-s** [cockpit-project/cockpit-machines#923]
I have a cephfs filesystem mounted where I store ISOs. When using the 'Local installation medium' option when creating a new VM, a storage pool for this folder is created automatically. Is this behavior intended?

I could also see '/run/user/0' getting created as a storage pool automatically. It happened multiple times, but I was not yet able to define the steps neccessary for it to occur.

Apart from the 'default' storage pool, which I can change in the libvirt configuration, my expectation would be that no storage pools are automatically created.

**Comment by KKoukiou** [comment]
This is done by `virt-install`.
Command line reproducer:

```

[kkoukiou@fedora anaconda]$ virsh pool-list --all 
 Name       State    Autostart
--------------------------------
 default    active   yes
 images     active   yes
 images-1   active   yes

[kkoukiou@fedora anaconda]$ virt-install --connect qemu:///session --quiet --os-variant fedora37 --memory 10240 --name test --wait -1 --noautoconsole --disk size=10,format=qcow2 --graphics vnc,listen=127.0.0.1 --graphics spice,listen=127.0.0.1 --cdrom /home/kkoukiou/Downloads/Fedora-Workstation-Live-x86_64-37-1.7.iso

^CDomain install interrupted.
Installation aborted at user request

[kkoukiou@fedora anaconda]$ virsh pool-list --all 
 Name        State    Autostart
---------------------------------
 default     active   yes
 Downloads   active   yes
 images      active   yes
 images-1    active   yes
```


If you want you can take this reproducer and open an issue there; https://github.com/virt-manager/virt-manager/issues
