### ISSUE TITLE
Unable to bridge lan if the network is already being used?

### ISSUE THREAD

**Issue by ItzChr1s1** [cockpit-project/cockpit-machines#926]
Hi i'm kind of new to all this, I am able to successfully spin up a VM on the web ui, but having trouble with networking. I'm trying to bridge my wifi so each individual vm gets assigned an IP and connects to the internet.

but I am only able to use the option "Direct Attachment" enp4s0f0 or to an Ethernet to get internet? 

When I try to use wifi or ethernet for multiple VMs it says "Operation not supported" its like I have to plug multiple Ethernet cords for each individual virtual machine and use direct attachment?

Here is an example when I attempt to use wlp3s0 bridge to lan when the ubuntu server that is hosting cockpit is already using wlp3s0 as its main internet:
<img width="949" alt="Screen Shot 2023-01-29 at 5 33 04 PM" src="https://user-images.githubusercontent.com/49334413/215359776-898537c6-9552-493a-8680-23f25f1508a3.png">

**Comment by KKoukiou** [comment]
wlp3s0 is not a bridge. You can view existing bridges with `sudo ip link show type bridge` or create one in the cockpit's network page. Unfortunately the UI is not correct here, as we should not even show this device. There is already an [open issue](https://github.com/cockpit-project/cockpit-machines/issues/543#issuecomment-738784075) about fixing this.

**Comment by ItzChr1s1** [comment]
> 

using `sudo ip link show type bridge` all the bridges listed are still unable to give the VM internet access, even when I attempt to create a bridge in the Networking page for some reason it turns off wlp3s0 itself and is unable to be used unless I undo the bridge I created. The only thing that can give the VM internet is via ethernet and using direct attachment, but I have to choose which VM uses.
