### ISSUE TITLE
Virtual network failed to be created 

### ISSUE THREAD

**Issue by Justinzobel** [cockpit-project/cockpit-machines#944]
Sender is not authorized to send message

Error when creating a virtual network.

![image](https://user-images.githubusercontent.com/1370117/217818829-f03c641a-e0cd-41c8-b63b-78b91cf9b4a9.png)

I'm in "Limited access" mode. If I go to Administrative access I can't even access the Virtual machines page due to another error.

**Comment by KKoukiou** [comment]
@Justinzobel what version of cockpit is that?

**Comment by Justinzobel** [comment]
```
cockpit.x86_64                            284-1.fc37                       @updates     
cockpit-bridge.x86_64                     284-1.fc37                       @updates     
cockpit-machines.noarch                   282-1.fc37                       @updates     
cockpit-networkmanager.noarch             284-1.fc37                       @updates     
cockpit-packagekit.noarch                 284-1.fc37                       @updates     
cockpit-pcp.x86_64                        284-1.fc37                       @updates     
cockpit-storaged.noarch                   284-1.fc37                       @updates     
cockpit-system.noarch                     284-1.fc37                       @updates     
cockpit-ws.x86_64                         284-1.fc37                       @updates
```

**Comment by KKoukiou** [comment]
@Justinzobel following the instructions from https://www.libvirt.org/dbus.html#usage should fix your issue. Please comment to reopen if that's not the case.

**Comment by Justinzobel** [comment]
I thought the idea of cockpit was to not have to use ssh or a terminal to get things done.
