### ISSUE TITLE
Virtualization service (libvirt) is not active

### ISSUE THREAD

**Issue by Justinzobel** [cockpit-project/cockpit-machines#945]
Similar to #832 but that's closed.

I have installed Cockpit on my Fedora 37 server.

I can use the Virtual machines while I'm in "Limited access" mode but not "Administrative access" which seems somewhat backward.

**Comment by KKoukiou** [comment]
Can you please paste the browser console output and also from terminal show output of:
`systemctl status virtqemud`

**Comment by Justinzobel** [comment]
Looks like I got some updates last night, my server rebooted and now it works. :man_shrugging:

This is the list of packages that changed:
```
Packages Altered:
    Upgrade  dbus-broker-33-1.fc37.x86_64                @updates
    Upgraded dbus-broker-32-1.fc37.x86_64                @@System
    Upgrade  libffi-3.4.4-1.fc37.x86_64                  @updates
    Upgraded libffi-3.4.2-9.fc37.x86_64                  @@System
    Upgrade  python3-beautifulsoup4-4.11.2-1.fc37.noarch @updates
    Upgraded python3-beautifulsoup4-4.11.1-1.fc37.noarch @@System
    Upgrade  python3-rpmautospec-0.3.2-1.fc37.noarch     @updates
    Upgraded python3-rpmautospec-0.3.1-1.fc37.noarch     @@System
    Upgrade  rpmautospec-rpm-macros-0.3.2-1.fc37.noarch  @updates
    Upgraded rpmautospec-rpm-macros-0.3.1-1.fc37.noarch  @@System
    Upgrade  tpm2-tss-3.2.2-1.fc37.x86_64                @updates
    Upgraded tpm2-tss-3.2.1-1.fc37.x86_64                @@System
    ```
    
    However, maybe it was the reboot that happened after these updates that fixed the issue.
    
    I installed `cockpit-machines` 3 days ago but I don't think my machine was rebooted until last night.

**Comment by dingdang66686** [comment]
I meet this problem on my ubuntu 22.04 server. I tried updating cockpit from backports repository, but this problem still exists.

**Comment by KKoukiou** [comment]
> I meet this problem on my ubuntu 22.04 server. I tried updating cockpit from backports repository, but this problem still exists.

@dingdang66686 since you are using different distro and probably different version than the reporter, please open a new issue with information about cockpit-machines version, browser console and also output of `systemctl status virtqemud.socket`

**Comment by dingdang66686** [comment]
@KKoukiou Please look at #946

**Comment by subhoghoshX** [comment]
I can confirm this issue. I installed the plugin by cloning and building cockpit-machines.

It shows this:
![image](https://user-images.githubusercontent.com/108616679/224940125-1c4ac030-e29e-47ed-a1d1-def63410f872.png)

Browser console:
![image](https://user-images.githubusercontent.com/108616679/224940435-5a8cf01e-ca33-47d4-9876-eb8e192d1aaa.png)

Output of `systemctl status virtqemud`:
![image](https://user-images.githubusercontent.com/108616679/224940818-2c85a055-d5de-4b79-8b68-c067c5bedc88.png)

I'm using Fedora Workstation 37.

And as @Justinzobel mentioned, switching to limited access mode seems to work.

**Comment by subhoghoshX** [comment]
This issue of "Virtualization service (libvirt) is not active" was fixed for me after installing `libvirt-dbus`, suggested by someone in IRC.

It appears to be a common occurrence, as it was also mentioned in #832, #946, cockpit-project/cockpit#11807, and a few other places, including this one https://bugzilla.redhat.com/show_bug.cgi?id=2016601

It might be useful to have this in FAQ.

Though the solutions to this seems different in various situations. Sometimes it's missing dependency other times it being in the wrong user group.

**Comment by gitthangbaby** [comment]
I tried all the fixes, but the error is coming back in administrator mode, and it's not present in limited mode (but there are no machines listed). It comes back usually after a connection change (e.g. router restart).
I have no errors journal, or services, nor dbus strace, perhaps only this: 
_recvmsg(20, {msg_namelen=0}, MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)_

The fix is to keep restarting dbus service all day:
`$ gdbus call --system --dest org.libvirt --object-path /org/libvirt/QEMU --method org.libvirt.Connect.ListDomains 0`
`Error: Timeout was reached`
`$ systemctl restart libvirt-dbus`
`$ gdbus call --system --dest org.libvirt --object-path /org/libvirt/QEMU --method org.libvirt.Connect.ListDomains 0`
`([objectpath '/org/libvirt/QEMU/domain/_e764230c_c646_4b94_97cb_fd4ccbb54f2e', '/org/libvirt/QEMU/domain/_58702620_d203_471c_83d4_132ab0ab2192'],)`

**Comment by martinpitt** [comment]
@gitthangbaby Please report this as a bug against libvirt-dbus in https://bugzilla.redhat.com, together with the output of `journalctl -b`

**Comment by yeorinhieut** [comment]
same issue for me.
limited mode solved this issue, but I want admin mode..
