### ISSUE TITLE
Virtualization service (libvirt) is not active - dbus-daemon cannot launch services

### ISSUE THREAD

**Issue by dingdang66686** [cockpit-project/cockpit-machines#946]
Server system: ubuntu 22.04 wsl
Cockpit version:

> cockpit-bridge/jammy-updates,now 264-1ubuntu0.22.04.1 amd64 [已安装，自动]
> cockpit-machines/jammy,now 265-1 all [已安装]
> cockpit-networkmanager/jammy-updates,now 264-1ubuntu0.22.04.1 all [已安装，自动]
> cockpit-packagekit/jammy-updates,now 264-1ubuntu0.22.04.1 all [已安装，自动]
> cockpit-podman/jammy,now 45-1 all [已安装]
> cockpit-storaged/jammy-updates,now 264-1ubuntu0.22.04.1 all [已安装，自动]
> cockpit-system/jammy-updates,now 264-1ubuntu0.22.04.1 all [已安装，自动]
> cockpit-ws/jammy-updates,now 264-1ubuntu0.22.04.1 amd64 [已安装，自动]
> cockpit/jammy-updates,now 264-1ubuntu0.22.04.1 all [已安装]

> dilin@ubuntu:~$ systemctl status virtqemud
> Unit virtqemud.service could not be found.

**Comment by KKoukiou** [comment]
Oh virtqemud is not available. Maybe you use the old libvirt daemons? Please paste the output of `systemctl status libvirtd.socket`

**Comment by dingdang66686** [comment]
> dilin@ubuntu:~$ systemctl status libvirtd.socket 
> ● libvirtd.socket - Libvirt local socket
>      Loaded: loaded (/lib/systemd/system/libvirtd.socket; enabled; vendor preset: enabled)
>      Active: active (running) since Fri 2023-02-10 09:54:54 CST; 7h ago
>    Triggers: ● libvirtd.service
>      Listen: /run/libvirt/libvirt-sock (Stream)
>       Tasks: 0 (limit: 14351)
>      Memory: 0B
>         CPU: 1ms
>      CGroup: /system.slice/libvirtd.socket
> 
> 2月 10 09:54:54 ubuntu systemd[1]: Starting Libvirt local socket...
> 2月 10 09:54:54 ubuntu systemd[1]: Listening on Libvirt local socket.

**Comment by KKoukiou** [comment]
Ok that's fine, ubuntu 22 still uses the monolithic libvirt daemon. Can you check if we can talk over dbus to that daemon on your system? 

```
gdbus call --system --dest org.libvirt --object-path /org/libvirt/QEMU \
    --method org.libvirt.Connect.ListDomains 0
```

Does this print some array with the ids of the Vms on the system connection or it errors?

**Comment by dingdang66686** [comment]
If I use virt-manager to connect to it remotely, I can create and manage virtual machines.

**Comment by KKoukiou** [comment]
@dingdang66686 that's because virt-manager does not use libvirt-dbus, which cockpit-machines does. Seems like some issue specifically on libvirt-dbus, Maybe https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1802005 in fact.

Can you paste the output of `id libvirtdbus` ? Seems like some users reported there that adding libvirtdbus user to libvirt group solved that for them.

**Comment by martinpitt** [comment]
Indeed that looks very much like that old bug, perhaps it regressed somehow. Can you please give the output of
```
ls -l /var/run/libvirt/libvirt-sock
dpkg -l libvirt-dbus
```
?

**Comment by dingdang66686** [comment]
All command outputs below:

> dilin@ubuntu:~$ id libvirtdbus 
> uid=112(libvirtdbus) gid=121(libvirtdbus) groups=121(libvirtdbus),119(libvirt)
> dilin@ubuntu:~$ ls -l /var/run/libvirt/libvirt-sock
> srw-rw---- 1 root libvirt 0  2月 10 09:54 /var/run/libvirt/libvirt-sock
> dilin@ubuntu:~$ dpkg -l libvirt-dbus
> 期望状态=未知(u)/安装(i)/删除(r)/清除(p)/保持(h)
> | 状态=未安装(n)/已安装(i)/仅存配置(c)/仅解压缩(U)/配置失败(F)/不完全安装(H)/触发器等待(W)/触发器未决(T)
> |/ 错误?=(无)/须重装(R) (状态，错误：大写=故障)
> ||/ 名称           版本           体系结构     描述
> +++-==============-==============-============-=================================
> ii  libvirt-dbus   1.4.1-1ubuntu1 amd64        libvirt D-Bus API bindings

**Comment by KKoukiou** [comment]
@dingdang66686 I would try  to open up permissions on on the libvirt-socket a bit and see if that fixes the issue:

````
1. set in /etc/libvirt/libvirtd.conf
unix_sock_rw_perms = "0777"
(or any other perm that is sufficient for you)
2. restart libvirt
systemctl restart libvirtd
```

**Comment by dingdang66686** [comment]
> @dingdang66686 I would try to open up permissions on on the libvirt-socket a bit and see if that fixes the issue:
> 
> ```
> 1. set in /etc/libvirt/libvirtd.conf
> unix_sock_rw_perms = "0777"
> (or any other perm that is sufficient for you, I have 666 on my libvirt system socket )
> 2. restart libvirt
> systemctl restart libvirtd
> ```
This doesn't change anything...

**Comment by KKoukiou** [comment]
@dingdang66686 well it should change the permission of the socket.  aka the output of ls -l /var/run/libvirt/libvirt-sock at least.

**Comment by dingdang66686** [comment]
Sorry, I mean cockpit still complain about the service not active.

**Comment by martinpitt** [comment]
OK, then it's not that old bug. I don't have access to a Windows machine (with WSL). This is now at the point where it would require a full journal, strace, etc. to debug this. Do you see anything in `sudo journalctl -f` when you do the `gdbus` call from above?

**Comment by dingdang66686** [comment]
2月 10 19:07:23 ubuntu dbus-daemon[153]: [system] Activating service name='org.libvirt' requested by ':1.715' (uid=1000 pid=12146 comm="gdbus call --system --dest org.libvirt --object-pa") (using servicehelper)
2月 10 19:07:23 ubuntu dbus-daemon[153]: [system] Activated service 'org.libvirt' failed: Failed to execute program org.libvirt: Permission denied
2月 10 19:07:23 ubuntu dbus-daemon[153]: [system] Activating service name='org.libvirt' requested by ':1.715' (uid=1000 pid=12146 comm="gdbus call --system --dest org.libvirt --object-pa") (using servicehelper)
2月 10 19:07:23 ubuntu dbus-daemon[153]: [system] Activated service 'org.libvirt' failed: Failed to execute program org.libvirt: Permission denied

**Comment by martinpitt** [comment]
Hmm, that error message does not make sense at all.. "org.libvirt" is not a program, it's the D-Bus owner name. What is the output of `cat /usr/share/dbus-1/system-services/org.libvirt.service` ?

On a regular Ubuntu 22.04 as non-root user, with libvirt-dbus 1.4.1-1ubuntu1, I get
```
gdbus call --system --dest org.libvirt --object-path /org/libvirt/QEMU --method org.libvirt.Connect.ListDomains 0

(@ao [],)
```

**Comment by dingdang66686** [comment]
[D-BUS Service]
Name=org.libvirt
Exec=/usr/sbin/libvirt-dbus --system
User=libvirtdbus

**Comment by martinpitt** [comment]
OK, that's as expected.  The next step is to attach strace to dbus-daemon while doing the call, this smells like an oddity with WSL.

Run

    sudo strace -fvvs1024 -o /tmp/dbus.txt -p $(pgrep -f 'dbus-daemon.*system\b')

and in another terminal,

    gdbus call --system --dest org.libvirt --object-path /org/libvirt/QEMU --method org.libvirt.Connect.ListDomains 0

then press Control-C in the strace terminal. Please attach /tmp/dbus.txt here.

Thanks!

**Comment by dingdang66686** [comment]
[dbus.txt](https://github.com/cockpit-project/cockpit-machines/files/10712913/dbus.txt)

**Comment by martinpitt** [comment]
A-ha!
```
execve("/usr/lib/dbus-1.0/dbus-daemon-launch-helper", ["/usr/lib/dbus-1.0/dbus-daemon-launch-helper", "org.libvirt"] ... = -1 EACCES (Permission denied)
```

What is
    ls -l /usr/lib/dbus-1.0/dbus-daemon-launch-helper

for you? It should be

    -rwsr-xr-- 1 root messagebus 35112 Oct 25 13:15 /usr/lib/dbus-1.0/dbus-daemon-launch-helper

Please also give me the output of 

    cat /proc/$(pgrep -f 'dbus-daemon.*system\b')/status
    id messagebus

Note that without dbus-daemon-launch-helper, a *lot* of things on your system will be broken.

**Comment by martinpitt** [comment]
It's actually a bit curious as these days, systemd ought to launch the service, not dbus-daemon itself.

**Comment by dingdang66686** [comment]
dilin@ubuntu:~$ ls -l /usr/lib/dbus-1.0/dbus-daemon-launch-helper
-rwsr-xr-- 1 root 18 35112 10月 25 21:15 /usr/lib/dbus-1.0/dbus-daemon-launch-helper
---
dilin@ubuntu:~$ cat /proc/$(pgrep -f 'dbus-daemon.*system\b')/status
Name:   dbus-daemon
Umask:  0022
State:  S (sleeping)
Tgid:   143
Ngid:   0
Pid:    143
PPid:   1
TracerPid:      0
Uid:    102     102     102     102
Gid:    105     105     105     105
FDSize: 64
Groups:  
NStgid: 143
NSpid:  143
NSpgid: 143
NSsid:  143
VmPeak:     9348 kB
VmSize:     9348 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:      5212 kB
VmRSS:      5212 kB
RssAnon:            1268 kB
RssFile:            3944 kB
RssShmem:              0 kB
VmData:     1444 kB
VmStk:       132 kB
VmExe:       140 kB
VmLib:      5368 kB
VmPTE:        52 kB
VmSwap:        0 kB
HugetlbPages:          0 kB
CoreDumping:    0
THP_enabled:    1
Threads:        1
SigQ:   0/47838
SigPnd: 0000000000000000
ShdPnd: 0000000000000000
SigBlk: 0000000000000000
SigIgn: 0000000000001000
SigCgt: 0000000000004001
CapInh: 0000000000000000
CapPrm: 0000000020000000
CapEff: 0000000020000000
CapBnd: 000001ffffffffff
CapAmb: 0000000000000000
NoNewPrivs:     0
Seccomp:        2
Seccomp_filters:        1
Speculation_Store_Bypass:       thread force mitigated
SpeculationIndirectBranch:      conditional force disabled
Cpus_allowed:   ff
Cpus_allowed_list:      0-7
Mems_allowed:   1
Mems_allowed_list:      0
voluntary_ctxt_switches:        3695
nonvoluntary_ctxt_switches:     109
---
dilin@ubuntu:~$ id messagebus
uid=102(messagebus) gid=105(messagebus) groups=105(messagebus)

**Comment by dingdang66686** [comment]
I changed the group of dbus-daemon-launch-helper to messagebus and it just works. Thanks a lot!

**Comment by dingdang66686** [comment]
BTW, I don't know why the group of this executable is wrong. I didn't do anything to it.

**Comment by martinpitt** [comment]
No idea either, I'm afraid. But I suppose there's no way to figure that out any more.
