### ISSUE TITLE
Fix the "overview" card information classification

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-machines#971]
As seen in #969 (and before): The overview card is a monstrosity. It has grown organically and everything inside has been tossed in, mainly under "general". There's also "hypervisor details", which doesn't seem to be a useful group either, as these are all "details" of some sort (even under "general") and it's not clear what is what or how anything relates to each other.

**Comment by garrett** [comment]
Here's a screengrab from #969 to show what I'm talking about:

![image](https://user-images.githubusercontent.com/10246/222194248-682142bd-5005-47a9-9360-3117a2b42538.png)

We need to classify and organize this information.

For a start, I see at least the following types of information:

- type (system)
- state (state)
- system attributes (memory, vCPUs & type, hypervisor details)
- boot order
- configuration options (autostart, boot order)
- integration (vsock identifier perhaps?, watchdog)

Is this right? Is there a better way to group these?

Should we split this out to multiple cards?

@skobyda: WDYT? ("What do you think?")

**Comment by subhoghoshX** [comment]
We can probably look into existing tools like VirtualBox, Virt Manager etc.

From VirtualBox:
![image](https://user-images.githubusercontent.com/108616679/225386735-3c16e280-c32b-4f3c-a88f-948974c9421e.png)

Here System has Memory & Boot order. We can probably also put vCPUs and CPU type in there.

System:
1. Memory
2. Boot order
3. vCPUs
4. CPU type

Hypervisor details section from Virt Manager:
![image](https://user-images.githubusercontent.com/108616679/225387724-1cf3851b-27d4-4567-94c0-6170813d2099.png)

The current Hypervisor details sections seems okay.

Once you've reached a definite conclusion. I'd like to work on it, if it's okay :)

**Comment by skobyda** [comment]
> Hey, I think in close future GPU configuration also might get implemented in the overview card: #554 Let's account for that in the new design

**Comment by skobyda** [comment]
Closing in favor of https://github.com/cockpit-project/cockpit-machines/issues/1027
