### ISSUE TITLE
[Request] ability to configure number of VM CPU's when creating VM

### ISSUE THREAD

**Issue by briansmith0** [cockpit-project/cockpit-machines#987]
Currently, Cockpit allows users to configure the size storage device and the amount of memory, but does not allow users to configure the number of VM CPU's on the "Create new virtual machine" page.  CPU's are one of the core configuration items for a VM, and users frequently need to configure more than 1 CPU on VM's, so this should be configurable on this page.  

In addition, users migrating from virt-manager to Cockpit would be used to having the ability to configure CPU's during VM creation, as this is how virt-manager works.  

There is the "Create and edit" button currently available that can be used as a workaround for this, however it requires an extra step to configure a setting that frequently needs to be changed.  

(note: this is feedback I received from a user)

**Comment by martinpitt** [comment]
The functionality is available via "Create and edit" indeed. The creation dialog is already too large and complex, duplicating all other available knobs there would make it even more so. So this is a "wontfix".
