### ISSUE TITLE
confirmation for shutting down & rebooting

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-machines#994]
As mentioned in https://bugzilla.redhat.com/show_bug.cgi?id=2180281, it would be good to have confirmation prompts during shut downs and reboots.

I talked with a few people about this on IRC and it's probably best if we implement it this way:

For standard VMs, by default:

- no confirmation for standard VMs for normal shutdown and reboots
- confirmation for force shutdowns and force reboots (as it's similar to pulling the plug from the wall, except virtually, and unclean restarts can cause data loss)

@martinpitt mentioned the concept of marking a VM as "precious", which adds some protected from deletion and it could also show a confirmation dialog for _all_ shutdowns and reboots. (I've looked for documentation on "precious" in libvirt and couldn't find it, however. I didn't see the word "precious" used like this in the code either. Perhaps it's called something else? It looks like we'd have to fully implement this in Cockpit.)

The confirmation dialog would also ideally have the information necessary to decide if the machine should be restarted. I'm not sure what we can show on it, but it would be great to have the following information:

- VM name
- creation date?
- last used date (if it's not running)?
- distribution
- kernel version (if possible)
- uptime (if possible — could be either uptime from inside the VM or if there's a way to query libvirt for the total running time that would be good as well)

**Comment by martinpitt** [comment]
There is no official concept of "precious". It was just an idea that c-machines could mark a newly created machine (or also edit an existing one) with a new custom ttribute. I.e. one could put a little note like "unsafe to reboot" or "customer data, don't delete" or so into this, which we then could display on reboot/remove, etc. with a confirmation dialog.

I was quite sure that @skobyda once talked about this, could have been a PR, issue, or bz.

**Comment by garrett** [comment]
Aha, OK. So we could extend libvirt to add something like this. That would be useful. So we probably want a "protect". I wonder if we would want to expose this as options for each (protect from reboots, protect from deleting) or merge them into one toggle.

If it's just one, we could add it to a dropdown menu and show some kind of icon (like a padlock? although that's overloaded with security meanings too) next to the name of the VM in the details and also on the VM list.

**Comment by skobyda** [comment]
> I was quite sure that @skobyda once talked about this, could have been a PR, issue, or bz.

I'm sorry, but I don't remember discussion like that, are you sure it was me?

Anyway yeah we can definitely store this in VM's XML metadata, even [libvirt docs](https://libvirt.org/formatdomain.html#general-metadata) say that's their point: `The metadata node can be used by applications to store custom metadata in the form of XML nodes/tree`


> If it's just one, we could add it to a dropdown menu and show some kind of icon (like a padlock? although that's overloaded with security meanings too) next to the name of the VM in the details and also on the VM list.

I'm not sure icon in the dropdown next to an action is good idea, as that would make it look like the actions is locked/disabled and user has to do some steps to unlock it, no?
What about having some similar icon in the confirmation dialog, letting user know that they are trying to remove "protected" VM?

**Comment by martinpitt** [comment]
> are you sure it was me?

No, I'm not. :grin:

**Comment by skobyda** [comment]
New comment at bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2180281#c4 , where they want a confirmation dialog even for reboot and shutdown. 
While that's still compatible with marking some VMs as precious/valuable/production/etc., and showing confirmation dialog only for those, I think if that's only not an unnecessary overhead, since user would have to mark each VM manually in some with some checkbox, maybe in some modal, would require additional explanation and thus making the UI more comple. So I'm thinking if that's really more effective as just simply showing confirmation dialog for every VM.

**Comment by garrett** [comment]
OK, some thoughts:

- I suppose when shutting down within the VM, most OSes and desktops would have a confirmation prompt as well.

- And, on a server, in production, people probably wouldn't want to stop an important service.

- When testing things out, it does add a layer of annoyance, but that's not the general use case... just one of several.

- So,  I suppose we could add a confirmation modal to prevent accidental shutdowns.

- We should have information that makes it obvious which VM is being shut down. The name would be good. Perhaps also approximately how long it has been running, if we could get that information? Would there be anything else that might be useful to show in a confirmation modal?

- We could also have a secondary action to force shutdown too? We could combine both actions and make it more obvious. _On the other hand_, force shutting down is probably really a fallback measure in case shutting down doesn't work, so perhaps not. We therefore might want to leave that to the kebab menu, as is.

- Most OS shutdown dialogs have reboot. Perhaps we could have _reboot_ as a secondary action? 

- Along similar lines to reboot, _hibernate_ could also be a secondary action.

**Summary**: Sure. Let's go ahead and add a shutdown confirmation with some machine details.

---

Here's a mockup, once we get descriptions:

![Modal dialog (1)](https://user-images.githubusercontent.com/10246/233325435-e044b100-02ac-4741-9cb6-673b74827e14.png)

(Uptime is approximate. It probably doesn't live update. It doesn't show seconds. It's not so accurate, on purpose.)

Here's what it would look like without a description (even when we have description):

![Modal dialog (2)](https://user-images.githubusercontent.com/10246/233325441-205e45c6-5ae2-4913-8adb-8c500be0f751.png)

I also considered this variant as a warning. I'm not sure about it, however. If it was force shutdown, then it should definitely be a warning. This is a clean shutdown and reboot, so it should cleanly stop the machine (and possibly start it again).

![Modal dialog (3)](https://user-images.githubusercontent.com/10246/233325446-cfd1e633-5f5f-4083-b9f9-4a2617b53869.png)

We could also have an indication that there are pending changes and that they will be applied, when that is relevant. But for a first pass, I'd suggest implementing the middle of these mockups (well, the top would be the ideal, but we don't have descriptions yet, so it doesn't make sense at the moment).

**Comment by garrett** [comment]
Oh, the title here is a wonderful place to use the Markdown string for bolding, so translations could do `Shut down **SERVERNAME**` (which would then become something like `**SERVERNAME** abschalten`, perhaps, for example) and then it's rendered with bold in our UI without HTML escaping mess.
